-- 司机人意险模块建表脚本
DROP TABLE IF EXISTS BS_CARMAN_RISK_INSURANT;
DROP TABLE IF EXISTS BS_CARMAN_RISK_ITEM;
DROP TABLE IF EXISTS BS_CARMAN_RISK;

-- 司机人意险
CREATE TABLE BS_CARMAN_RISK (
	ID INT NOT NULL,
	UID_ VARCHAR(32) NOT NULL,
	CODE VARCHAR(255) NOT NULL,
	BUY_TYPE INT DEFAULT 0 NOT NULL,
	STATUS_ INT DEFAULT 0 NOT NULL,
	COMPANY VARCHAR(255) NOT NULL,
	HOLDER VARCHAR(255) NOT NULL,
	START_DATE DATE NOT NULL,
	END_DATE DATE,
	AUTHOR_ID INT NOT NULL,
	FILE_DATE TIMESTAMP NOT NULL,
	MODIFIER_ID INT,
	MODIFIED_DATE TIMESTAMP,
	CONSTRAINT BCPK_CARMAN_RISK PRIMARY KEY (ID),
	CONSTRAINT BSUK_CARMAN_RISK_CODE UNIQUE (CODE)
);
COMMENT ON TABLE BS_CARMAN_RISK IS '司机人意险';
COMMENT ON COLUMN BS_CARMAN_RISK.ID IS 'ID';
COMMENT ON COLUMN BS_CARMAN_RISK.UID_ IS 'UID';
COMMENT ON COLUMN BS_CARMAN_RISK.CODE IS '保单号';
COMMENT ON COLUMN BS_CARMAN_RISK.BUY_TYPE IS '购买类型 : 0-未知,1-公司,2-自买';
COMMENT ON COLUMN BS_CARMAN_RISK.STATUS_ IS '状态 : -1-草稿,0-正常,1-已禁用';
COMMENT ON COLUMN BS_CARMAN_RISK.COMPANY IS '保险公司';
COMMENT ON COLUMN BS_CARMAN_RISK.HOLDER IS '投保人';
COMMENT ON COLUMN BS_CARMAN_RISK.START_DATE IS '开始日期';
COMMENT ON COLUMN BS_CARMAN_RISK.END_DATE IS '结束日期 : 为空代表长期有效';
COMMENT ON COLUMN BS_CARMAN_RISK.AUTHOR_ID IS '创建人ID';
COMMENT ON COLUMN BS_CARMAN_RISK.FILE_DATE IS '创建时间';
COMMENT ON COLUMN BS_CARMAN_RISK.MODIFIER_ID IS '最后修改人ID';
COMMENT ON COLUMN BS_CARMAN_RISK.MODIFIED_DATE IS '最后修改时间';
ALTER TABLE BS_CARMAN_RISK ADD CONSTRAINT BCFK_CARMAN_RISK_MODIFIER FOREIGN KEY (MODIFIER_ID)
	REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE BS_CARMAN_RISK ADD CONSTRAINT BCFK_CARMAN_RISK_AUTHOR FOREIGN KEY (AUTHOR_ID)
	REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- 司机人意险的被投保人
CREATE TABLE BS_CARMAN_RISK_INSURANT (
	RISK_ID INT NOT NULL,
	MAN_ID INT NOT NULL,
	CONSTRAINT BCPK_CARMAN_RISK_INSURANT PRIMARY KEY (RISK_ID, MAN_ID)
);
COMMENT ON TABLE BS_CARMAN_RISK_INSURANT IS '司机人意险的被投保人';
COMMENT ON COLUMN BS_CARMAN_RISK_INSURANT.RISK_ID IS '所属人意险ID';
COMMENT ON COLUMN BS_CARMAN_RISK_INSURANT.MAN_ID IS '被保险人ID';
ALTER TABLE BS_CARMAN_RISK_INSURANT ADD CONSTRAINT BCFK_CARMAN_RISK_INSURANT_MANID FOREIGN KEY (MAN_ID)
	REFERENCES BS_CARMAN (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE BS_CARMAN_RISK_INSURANT ADD CONSTRAINT BCFK_CARMAN_RISK_INSURANT_RISKID FOREIGN KEY (RISK_ID)
	REFERENCES BS_CARMAN_RISK (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- 司机人意险购买的险种
CREATE TABLE BS_CARMAN_RISK_ITEM (
	ID INT NOT NULL,
	PID INT NOT NULL,
	ORDER_ INT NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	COVERAGE VARCHAR(255) NOT NULL,
	PREMIUM VARCHAR(255) NOT NULL,
	DESC_ VARCHAR(4000),
	CONSTRAINT BCPK_CARMAN_RISK_ITEM PRIMARY KEY (ID)
);
COMMENT ON TABLE BS_CARMAN_RISK_ITEM IS '司机人意险购买的险种';
COMMENT ON COLUMN BS_CARMAN_RISK_ITEM.ID IS 'ID';
COMMENT ON COLUMN BS_CARMAN_RISK_ITEM.PID IS '所属人意险ID';
COMMENT ON COLUMN BS_CARMAN_RISK_ITEM.ORDER_ IS '排序号';
COMMENT ON COLUMN BS_CARMAN_RISK_ITEM.NAME IS '名称';
COMMENT ON COLUMN BS_CARMAN_RISK_ITEM.COVERAGE IS '保额';
COMMENT ON COLUMN BS_CARMAN_RISK_ITEM.PREMIUM IS '保费';
COMMENT ON COLUMN BS_CARMAN_RISK_ITEM.DESC_ IS '备注';
ALTER TABLE BS_CARMAN_RISK_ITEM ADD CONSTRAINT BCFK_CARMAN_RISK_ITEM_PID FOREIGN KEY (PID)
	REFERENCES BS_CARMAN_RISK (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;

delete from BS_CARMAN_RISK_INSURANT;
delete from BS_CARMAN_RISK_ITEM;
delete from BS_CARMAN_RISK;

-- test
select m.status_,m.name,m.cert_fwzg,m.cert_identity
	,r.code,r.company,r.holder,r.buy_type,r.start_date,r.end_date
	from bs_carman_risk_insurant ri
	inner join bs_carman_risk r on r.id=ri.risk_id
	inner join bs_carman m on m.id=ri.man_id
	order by m.status_ desc, m.file_date desc;
	
select ri.man_id,r.id,r.end_date,case when r.end_date is null then '长期' 
	when r.end_date >= current_date then '有效' 
	else '已过期' end
	from bs_carman_risk_insurant ri
	inner join bs_carman_risk r on r.id=ri.risk_id
	where ri.man_id in (102170,10146395,10094646,10061248)
	order by r.end_date desc limit s;

update bs_carman_risk set end_date = null where id=10413412;
select current_date,current_time;
select id from bs_carman where name='杨富国';
