
DROP TABLE IF EXISTS BS_CAR_PREPARE_ITEM;
DROP TABLE IF EXISTS BS_CAR_PREPARE;

-- 车辆更新计划
CREATE TABLE BS_CAR_PREPARE (
	ID INT NOT NULL,
	UID_ VARCHAR(32) NOT NULL,
	STATUS_ INT DEFAULT 0 NOT NULL,
	CODE VARCHAR(255) NOT NULL,
	PLAN_DATE DATE NOT NULL,
	C1_PLATE_TYPE VARCHAR(255) NOT NULL,
	C1_PLATE_NO VARCHAR(255) NOT NULL,
	C1_COMPANY VARCHAR(255) NOT NULL,
	C1_MOTORCADE INT,
	C1_BS_TYPE VARCHAR(255),
	C1_SCRAPTO VARCHAR(255),
	C1_REGISTER_DATE DATE,
	C1_CONTRACT_END_DATE DATE,
	C1_COMMERIAL_END_DATE DATE,
	C1_GREENSLIP_END_DATE DATE,
	C2_INDICATOR VARCHAR(255),
	C2_PLATE_TYPE VARCHAR(255),
	C2_PLATE_NO VARCHAR(255),
	C2_ENGINE_No VARCHAR(255),
	C2_COMPANY VARCHAR(255),
	C2_BRANCH INT,
	C2_MOTORCADE INT,
	AUTHOR_ID INT NOT NULL,
	FILE_DATE TIMESTAMP NOT NULL,
	MODIFIER_ID INT,
	MODIFIED_DATE TIMESTAMP,
	CONSTRAINT BSPK_CAR_PREPARE PRIMARY KEY (ID),
	CONSTRAINT BSUK_CAR_PREPARE_CAR UNIQUE (C1_PLATE_TYPE, C1_PLATE_NO)
);
COMMENT ON TABLE BS_CAR_PREPARE IS '车辆更新计划';
COMMENT ON COLUMN BS_CAR_PREPARE.ID IS 'ID';
COMMENT ON COLUMN BS_CAR_PREPARE.UID_ IS 'UID';
COMMENT ON COLUMN BS_CAR_PREPARE.STATUS_ IS '状态 : 0-更新中,1-已完成';
COMMENT ON COLUMN BS_CAR_PREPARE.CODE IS '经营权号';
COMMENT ON COLUMN BS_CAR_PREPARE.PLAN_DATE IS '预计交车日';
COMMENT ON COLUMN BS_CAR_PREPARE.C1_PLATE_TYPE IS '旧车车牌归属 : 如粤A';
COMMENT ON COLUMN BS_CAR_PREPARE.C1_PLATE_NO IS '旧车车牌号 : 如471G7';
COMMENT ON COLUMN BS_CAR_PREPARE.C1_COMPANY IS '旧车所属公司';
COMMENT ON COLUMN BS_CAR_PREPARE.C1_MOTORCADE IS '旧车所属车队';
COMMENT ON COLUMN BS_CAR_PREPARE.C1_BS_TYPE IS '旧车合同性质';
COMMENT ON COLUMN BS_CAR_PREPARE.C1_SCRAPTO IS '旧车残值归属';
COMMENT ON COLUMN BS_CAR_PREPARE.C1_REGISTER_DATE IS '旧车登记日期';
COMMENT ON COLUMN BS_CAR_PREPARE.C1_CONTRACT_END_DATE IS '旧车经济合同到期日';
COMMENT ON COLUMN BS_CAR_PREPARE.C1_COMMERIAL_END_DATE IS '旧车商业险到期日';
COMMENT ON COLUMN BS_CAR_PREPARE.C1_GREENSLIP_END_DATE IS '旧车强制险到期日';
COMMENT ON COLUMN BS_CAR_PREPARE.C2_INDICATOR IS '新车指标编号';
COMMENT ON COLUMN BS_CAR_PREPARE.C2_PLATE_TYPE IS '新车车牌归属';
COMMENT ON COLUMN BS_CAR_PREPARE.C2_PLATE_NO IS '新车车牌号';
COMMENT ON COLUMN BS_CAR_PREPARE.C2_ENGINE_No IS '新车发动机号码';
COMMENT ON COLUMN BS_CAR_PREPARE.C2_COMPANY IS '新车所属公司';
COMMENT ON COLUMN BS_CAR_PREPARE.C2_BRANCH IS '新车所属分公司';
COMMENT ON COLUMN BS_CAR_PREPARE.C2_MOTORCADE IS '新车所属车队';
COMMENT ON COLUMN BS_CAR_PREPARE.AUTHOR_ID IS '创建人ID';
COMMENT ON COLUMN BS_CAR_PREPARE.FILE_DATE IS '创建时间';
COMMENT ON COLUMN BS_CAR_PREPARE.MODIFIER_ID IS '最后修改人ID';
COMMENT ON COLUMN BS_CAR_PREPARE.MODIFIED_DATE IS '最后修改时间';
ALTER TABLE BS_CAR_PREPARE
	ADD CONSTRAINT BSFK_CAR_PREPARE_MOTORCADE1 FOREIGN KEY (C1_MOTORCADE)
	REFERENCES BS_MOTORCADE (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE BS_CAR_PREPARE
	ADD CONSTRAINT BSFK_CAR_PREPARE_MOTORCADE2 FOREIGN KEY (C2_MOTORCADE)
	REFERENCES BS_MOTORCADE (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE BS_CAR_PREPARE
	ADD CONSTRAINT BSFK_CAR_PREPARE_BRANCH2 FOREIGN KEY (C2_BRANCH)
	REFERENCES BC_IDENTITY_ACTOR (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE BS_CAR_PREPARE
	ADD CONSTRAINT BSFK_CAR_PREPARE_AUTHOR FOREIGN KEY (AUTHOR_ID)
	REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE BS_CAR_PREPARE
	ADD CONSTRAINT BSFK_CAR_PREPARE_MODIFIER FOREIGN KEY (MODIFIER_ID)
	REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- 车辆更新项目
CREATE TABLE BS_CAR_PREPARE_ITEM (
	ID INT NOT NULL,
	PID INT NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	ORDER_ INT NOT NULL,
	DATE_ DATE,
	STATUS_ INT NOT NULL,
	DESC_ VARCHAR(1000),
	CONSTRAINT BSPK_CAR_PREPARE_ITEM PRIMARY KEY (ID),
	CONSTRAINT BSUK_CAR_PREPARE_ITEM_PIDNAME UNIQUE (PID, NAME)
);
COMMENT ON TABLE BS_CAR_PREPARE_ITEM IS '车辆更新项目';
COMMENT ON COLUMN BS_CAR_PREPARE_ITEM.ID IS 'ID';
COMMENT ON COLUMN BS_CAR_PREPARE_ITEM.PID IS 'PID';
COMMENT ON COLUMN BS_CAR_PREPARE_ITEM.NAME IS '名称';
COMMENT ON COLUMN BS_CAR_PREPARE_ITEM.ORDER_ IS '排序号';
COMMENT ON COLUMN BS_CAR_PREPARE_ITEM.DATE_ IS '更新日期';
COMMENT ON COLUMN BS_CAR_PREPARE_ITEM.STATUS_ IS '状态 : 0-未完成,1-已完成';
COMMENT ON COLUMN BS_CAR_PREPARE_ITEM.DESC_ IS '备注';
ALTER TABLE BS_CAR_PREPARE_ITEM
	ADD CONSTRAINT BSFK_CAR_PREPARE_ITEM_PID FOREIGN KEY (PID)
	REFERENCES BS_CAR_PREPARE (ID) ON UPDATE RESTRICT ON DELETE CASCADE;