-- 删表语句
DROP TABLE IF EXISTS BS_IR_ORIGIN;
DROP TABLE IF EXISTS BS_IR_CAR_QUANTITY;
DROP TABLE IF EXISTS BS_IR_CONVERT_ITEM;
DROP TABLE IF EXISTS BS_IR_CONVERT;

-- 行业排名原始数据
CREATE TABLE BS_IR_ORIGIN (
	ID INT NOT NULL,
	YEAR_ INT NOT NULL,
	MONTH_ INT NOT NULL,
	COMPANY VARCHAR(255) NOT NULL,
	S1 NUMERIC(5,2) NOT NULL,
	S2 NUMERIC(5,2) NOT NULL,
	S3 NUMERIC(5,2) NOT NULL,
	S4 NUMERIC(5,2) NOT NULL,
	TOTAL NUMERIC(5,2) NOT NULL,
	INNER_ BOOLEAN DEFAULT 'false' NOT NULL,
	RANK INT NOT NULL,
	AUTHOR_ID INT NOT NULL,
	FILE_DATE TIMESTAMP NOT NULL,
	MODIFIER_ID INT,
	MODIFIED_DATE TIMESTAMP,
	CONSTRAINT BSPK_IR_ORIGIN PRIMARY KEY (ID),
	CONSTRAINT BSUK_IR_ORIGIN_YEARMONTH UNIQUE (YEAR_, MONTH_)
);
COMMENT ON TABLE BS_IR_ORIGIN IS '行业排名原始数据';
COMMENT ON COLUMN BS_IR_ORIGIN.ID IS 'ID';
COMMENT ON COLUMN BS_IR_ORIGIN.YEAR_ IS '年度';
COMMENT ON COLUMN BS_IR_ORIGIN.MONTH_ IS '月份';
COMMENT ON COLUMN BS_IR_ORIGIN.COMPANY IS '企业名称';
COMMENT ON COLUMN BS_IR_ORIGIN.S1 IS '服务投诉';
COMMENT ON COLUMN BS_IR_ORIGIN.S2 IS '交通违法';
COMMENT ON COLUMN BS_IR_ORIGIN.S3 IS '营运违章';
COMMENT ON COLUMN BS_IR_ORIGIN.S4 IS '服务违章';
COMMENT ON COLUMN BS_IR_ORIGIN.TOTAL IS '总分';
COMMENT ON COLUMN BS_IR_ORIGIN.INNER_ IS '是否为我司记录 : 当企业名称为宝城、广发时值为true';
COMMENT ON COLUMN BS_IR_ORIGIN.RANK IS '排名';
COMMENT ON COLUMN BS_IR_ORIGIN.AUTHOR_ID IS '创建人ID';
COMMENT ON COLUMN BS_IR_ORIGIN.FILE_DATE IS '创建时间';
COMMENT ON COLUMN BS_IR_ORIGIN.MODIFIER_ID IS '最后修改人ID';
COMMENT ON COLUMN BS_IR_ORIGIN.MODIFIED_DATE IS '最后修改时间';
ALTER TABLE BS_IR_ORIGIN
	ADD CONSTRAINT BSFK_IR_ORIGIN_AUTHOR FOREIGN KEY (AUTHOR_ID)
	REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE BS_IR_ORIGIN
	ADD CONSTRAINT BSFK_IR_ORIGIN_MODIFIER FOREIGN KEY (MODIFIER_ID)
	REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- 行业排名
CREATE TABLE BS_IR_CONVERT (
	ID INT NOT NULL,
	YEAR_ INT NOT NULL,
	MONTH_ INT NOT NULL,
	B1 NUMERIC(5,2) DEFAULT 0 NOT NULL,
	B2 NUMERIC(5,2) DEFAULT 0 NOT NULL,
	B3 NUMERIC(5,2) DEFAULT 0 NOT NULL,
	B4 NUMERIC(5,2) DEFAULT 0 NOT NULL,
	AUTHOR_ID INT NOT NULL,
	FILE_DATE TIMESTAMP NOT NULL,
	MODIFIER_ID INT,
	MODIFIED_DATE TIMESTAMP,
	FORMULA VARCHAR(1000) NOT NULL,
	CONSTRAINT BSPK_IR_CONVERT PRIMARY KEY (ID),
	CONSTRAINT BSUK_IR_CONVERT_YEARMONTH UNIQUE (YEAR_, MONTH_)
);
COMMENT ON TABLE BS_IR_CONVERT IS '行业排名';
COMMENT ON COLUMN BS_IR_CONVERT.ID IS 'ID';
COMMENT ON COLUMN BS_IR_CONVERT.YEAR_ IS '年度';
COMMENT ON COLUMN BS_IR_CONVERT.MONTH_ IS '月份';
COMMENT ON COLUMN BS_IR_CONVERT.B1 IS '服务投诉基准分 : 默认25分';
COMMENT ON COLUMN BS_IR_CONVERT.B2 IS '交通违法基准分 : 默认20分';
COMMENT ON COLUMN BS_IR_CONVERT.B3 IS '营运违章基准分 : 默认20分';
COMMENT ON COLUMN BS_IR_CONVERT.B4 IS '服务违章基准分 : 默认25分';
COMMENT ON COLUMN BS_IR_CONVERT.AUTHOR_ID IS '创建人ID';
COMMENT ON COLUMN BS_IR_CONVERT.FILE_DATE IS '创建时间';
COMMENT ON COLUMN BS_IR_CONVERT.MODIFIER_ID IS '最后修改人ID';
COMMENT ON COLUMN BS_IR_CONVERT.MODIFIED_DATE IS '最后修改时间';
COMMENT ON COLUMN BS_IR_CONVERT.FORMULA IS '折算公式';
ALTER TABLE BS_IR_CONVERT
	ADD CONSTRAINT BSFK_IR_CONVERT_MODIFIER FOREIGN KEY (MODIFIER_ID)
	REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE BS_IR_CONVERT
	ADD CONSTRAINT BSFK_IR_CONVERT_AUTHOR FOREIGN KEY (AUTHOR_ID)
	REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- 分公司车辆数
CREATE TABLE BS_IR_CAR_QUANTITY (
	ID INT NOT NULL,
	PID INT NOT NULL,
	COMPANY VARCHAR(255) NOT NULL,
	QUANTITY NUMERIC(5,2) DEFAULT 0 NOT NULL,
	CONSTRAINT BSPK_IR_CAR_QUANTITY PRIMARY KEY (ID)
);
COMMENT ON TABLE BS_IR_CAR_QUANTITY IS '分公司车辆数';
COMMENT ON COLUMN BS_IR_CAR_QUANTITY.ID IS 'ID';
COMMENT ON COLUMN BS_IR_CAR_QUANTITY.PID IS 'PID';
COMMENT ON COLUMN BS_IR_CAR_QUANTITY.COMPANY IS '分公司';
COMMENT ON COLUMN BS_IR_CAR_QUANTITY.QUANTITY IS '车辆数';
ALTER TABLE BS_IR_CAR_QUANTITY
	ADD CONSTRAINT BSFK_IR_CAR_QUANTITY_PID FOREIGN KEY (PID)
	REFERENCES BS_IR_CONVERT (ID) ON UPDATE RESTRICT ON DELETE CASCADE;

-- 行业排名项
CREATE TABLE BS_IR_CONVERT_ITEM (
	ID INT NOT NULL,
	PID INT NOT NULL,
	COMPANY VARCHAR(255) NOT NULL,
	S1 NUMERIC(5,2) NOT NULL,
	S2 NUMERIC(5,2) NOT NULL,
	S3 NUMERIC(5,2) NOT NULL,
	S4 NUMERIC(5,2) NOT NULL,
	TOTAL NUMERIC(5,2),
	RANK INT NOT NULL,
	CONSTRAINT BSPK_IR_CONVERT_ITEM PRIMARY KEY (ID),
	CONSTRAINT BSUK_IR_CONVERT_ITEM_PIDCOMPANY UNIQUE (PID, COMPANY)
);
COMMENT ON TABLE BS_IR_CONVERT_ITEM IS '行业排名项';
COMMENT ON COLUMN BS_IR_CONVERT_ITEM.ID IS 'ID';
COMMENT ON COLUMN BS_IR_CONVERT_ITEM.PID IS 'PID';
COMMENT ON COLUMN BS_IR_CONVERT_ITEM.COMPANY IS '分公司';
COMMENT ON COLUMN BS_IR_CONVERT_ITEM.S1 IS '服务投诉得分';
COMMENT ON COLUMN BS_IR_CONVERT_ITEM.S2 IS '交通违法得分';
COMMENT ON COLUMN BS_IR_CONVERT_ITEM.S3 IS '营运违章得分';
COMMENT ON COLUMN BS_IR_CONVERT_ITEM.S4 IS '服务违章得分';
COMMENT ON COLUMN BS_IR_CONVERT_ITEM.TOTAL IS '总分';
COMMENT ON COLUMN BS_IR_CONVERT_ITEM.RANK IS '排名';
ALTER TABLE BS_IR_CONVERT_ITEM
	ADD CONSTRAINT BSFK_IR_CONVERT_ITEM_PID FOREIGN KEY (PID)
	REFERENCES BS_IR_CONVERT (ID) ON UPDATE RESTRICT ON DELETE CASCADE;
