-- 创建数据转换用的序列，开始于100000
CREATE sequence DC_SEQUENCE
    minvalue 1
    start with 100000
    increment by 1
    cache 20;

-- 数据转换记录
CREATE TABLE DC_RECORD(
  TYPE_         VARCHAR2(255) NOT NULL,
  FROM_ID       NUMBER(19) NOT NULL,
  TO_ID         NUMBER(19) NOT NULL,
  FROM_TABLE    VARCHAR2(255),
  TO_TABLE      VARCHAR2(255),
  CREATE_DATE   DATE NOT NULL,
  REMARK        VARCHAR2(4000),
  MODIFIED_DATE DATE
);
COMMENT ON TABLE DC_RECORD IS '数据转换记录';
COMMENT ON COLUMN DC_RECORD.TYPE_ IS '类型';
COMMENT ON COLUMN DC_RECORD.FROM_ID IS '旧表数据ID';
COMMENT ON COLUMN DC_RECORD.TO_ID IS '新表数据的ID';
COMMENT ON COLUMN DC_RECORD.FROM_TABLE IS '旧数据表名';
COMMENT ON COLUMN DC_RECORD.TO_TABLE IS '新数据表名';
COMMENT ON COLUMN DC_RECORD.CREATE_DATE IS '创建时间';
COMMENT ON COLUMN DC_RECORD.REMARK IS '备注说明';
COMMENT ON COLUMN DC_RECORD.MODIFIED_DATE IS '最后修改时间';
ALTER TABLE DC_RECORD ADD CONSTRAINT BSUK_RECORD UNIQUE (TYPE_, FROM_ID);

-- bc营运管理子系统的建表脚本,所有表名须附带前缀"BS_"
-- 运行此脚本之前需先运行平台的建表脚本framework.db.mysql.CREATE.sql

-- 车队信息
CREATE TABLE BS_MOTORCADE (
   ID                   NUMBER(19)           NOT NULL,
   UID_                 VARCHAR2(36),
   CODE                 VARCHAR2(255)        NOT NULL,
   NAME                 VARCHAR2(255)        NOT NULL,
   STATUS_              NUMBER(1)            NOT NULL,
   UNIT_ID              NUMBER(19)           NOT NULL,
   PRINCIPAL_ID         NUMBER(19),
   PRINCIPAL_NAME       VARCHAR2(255),
   TYPE_                NUMBER(1)            NOT NULL,
   PID                  NUMBER(19),
   DESC_                VARCHAR2(4000),
   PAYMENT_DATE         VARCHAR2(255),
   COLOR                VARCHAR2(255), ADDRESS              VARCHAR2(255),
   PHONE                VARCHAR2(255),
   FAX                  VARCHAR2(255),
   FILE_DATE            DATE                 NOT NULL,
   AUTHOR_ID            NUMBER(19)           NOT NULL,
   MODIFIER_ID          NUMBER(19),
   MODIFIED_DATE        DATE,
   CONSTRAINT BSPK_MOTORCADE PRIMARY KEY (ID)
);
COMMENT ON TABLE BS_MOTORCADE IS '车队';
COMMENT ON COLUMN BS_MOTORCADE.CODE IS '编码';
COMMENT ON COLUMN BS_MOTORCADE.NAME IS '名称';
COMMENT ON COLUMN BS_MOTORCADE.STATUS_ IS '状态：0-在案,1-已禁用,2-已删除';
COMMENT ON COLUMN BS_MOTORCADE.UNIT_ID IS '所属单位ID';
COMMENT ON COLUMN BS_MOTORCADE.PRINCIPAL_ID IS '负责人ID';
COMMENT ON COLUMN BS_MOTORCADE.PRINCIPAL_NAME IS '负责人姓名';
COMMENT ON COLUMN BS_MOTORCADE.TYPE_ IS '类别：0-分队,1-分组';
COMMENT ON COLUMN BS_MOTORCADE.PID IS '所属父类ID';
COMMENT ON COLUMN BS_MOTORCADE.DESC_ IS '备注';
COMMENT ON COLUMN BS_MOTORCADE.PAYMENT_DATE IS '缴费日';
COMMENT ON COLUMN BS_MOTORCADE.COLOR IS '颜色';
COMMENT ON COLUMN BS_MOTORCADE.ADDRESS IS '地址';
COMMENT ON COLUMN BS_MOTORCADE.PHONE IS '电话';
COMMENT ON COLUMN BS_MOTORCADE.FAX IS '传真';
COMMENT ON COLUMN BS_MOTORCADE.FILE_DATE IS '创建时间';
COMMENT ON COLUMN BS_MOTORCADE.AUTHOR_ID IS '创建人ID';
COMMENT ON COLUMN BS_MOTORCADE.MODIFIER_ID IS '最后修改人ID';
COMMENT ON COLUMN BS_MOTORCADE.MODIFIED_DATE IS '最后修改时间';
ALTER TABLE BS_MOTORCADE ADD CONSTRAINT BSFK_MOTORCADE_AUTHORID FOREIGN KEY (AUTHOR_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
ALTER TABLE BS_MOTORCADE ADD CONSTRAINT BSFK_MOTORCADE_MODIFIER FOREIGN KEY (MODIFIER_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
ALTER TABLE BS_MOTORCADE ADD CONSTRAINT BSFK_MOTORCADE_PID FOREIGN KEY (PID)
      REFERENCES BS_MOTORCADE (ID);
ALTER TABLE BS_MOTORCADE ADD CONSTRAINT BSFK_MOTORCADE_PRINCIPAL FOREIGN KEY (PRINCIPAL_ID)
      REFERENCES BC_IDENTITY_ACTOR (ID);
ALTER TABLE BS_MOTORCADE ADD CONSTRAINT BSFK_MOTORCADE_UNIT FOREIGN KEY (UNIT_ID)
      REFERENCES BC_IDENTITY_ACTOR (ID);
CREATE INDEX BSIDX_MOTORCADE_STATUS ON BS_MOTORCADE (STATUS_);

-- 车队历史车辆数
CREATE TABLE BS_MOTORCADE_CARQUANTITY (
   ID                   NUMBER(19)           NOT NULL,
   MOTORCADE_ID         NUMBER(19)           NOT NULL,
   YEAR_                NUMBER(4)            NOT NULL,
   MONTH_               NUMBER(2)            NOT NULL,
   QUANTITY             NUMBER(19)           NOT NULL,
   FILE_DATE            DATE                 NOT NULL,
   AUTHOR_ID            NUMBER(19)           NOT NULL,
   MODIFIER_ID          NUMBER(19),
   MODIFIED_DATE        DATE,
   CONSTRAINT BSPK_CARQUANTITY PRIMARY KEY (ID)
);
COMMENT ON TABLE BS_MOTORCADE_CARQUANTITY IS '车队历史车辆数';
COMMENT ON COLUMN BS_MOTORCADE_CARQUANTITY.MOTORCADE_ID IS '所属车队ID';
COMMENT ON COLUMN BS_MOTORCADE_CARQUANTITY.YEAR_ IS '年份';
COMMENT ON COLUMN BS_MOTORCADE_CARQUANTITY.MONTH_ IS '月份';
COMMENT ON COLUMN BS_MOTORCADE_CARQUANTITY.QUANTITY IS '车辆数';
COMMENT ON COLUMN BS_MOTORCADE_CARQUANTITY.FILE_DATE IS '创建时间';
COMMENT ON COLUMN BS_MOTORCADE_CARQUANTITY.AUTHOR_ID IS '创建人ID';
COMMENT ON COLUMN BS_MOTORCADE_CARQUANTITY.MODIFIER_ID IS '最后修改人ID';
COMMENT ON COLUMN BS_MOTORCADE_CARQUANTITY.MODIFIED_DATE IS '最后修改时间';
ALTER TABLE BS_MOTORCADE_CARQUANTITY ADD CONSTRAINT BSFK_CARQUANTITY_AUTHOR FOREIGN KEY (AUTHOR_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
ALTER TABLE BS_MOTORCADE_CARQUANTITY ADD CONSTRAINT BSFK_CARQUANTITY_MODIFIER FOREIGN KEY (MODIFIER_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
ALTER TABLE BS_MOTORCADE_CARQUANTITY ADD CONSTRAINT BSFK_CARQUANTITY_MOTORCADE FOREIGN KEY (MOTORCADE_ID)
      REFERENCES BS_MOTORCADE (ID);


-- 证件
create table BS_CERT (
    ID number(19) NOT NULL,
    STATUS_ number(1) NOT NULL,
    UID_ varchar2(36) NOT NULL,
    TYPE_ number(1) NOT NULL,
    CERT_CODE varchar2(255) NOT NULL,
    CERT_NAME varchar2(255) NOT NULL,
    CERT_FULL_NAME varchar2(255),
    LICENCER varchar2(255),
    ISSUE_DATE date,
    START_DATE date,
    END_DATE date,
    EXT_STR1 varchar2(255),
    EXT_STR2 varchar2(255),
    EXT_STR3 varchar2(255),
    EXT_NUM1 number(19),
    EXT_NUM2 number(19),
    EXT_NUM3 number(19),
    FILE_DATE date NOT NULL,
    AUTHOR_ID number(19) NOT NULL,
    MODIFIER_ID number(19) ,
    MODIFIED_DATE date,
    CONSTRAINT BSPK_CERT primary key (ID)
);
COMMENT ON TABLE BS_CERT IS '证件';
COMMENT ON COLUMN BS_CERT.STATUS_ IS '状态：0-启用中,1-已禁用,2-已删除';
COMMENT ON COLUMN BS_CERT.CERT_CODE IS '证件号';
COMMENT ON COLUMN BS_CERT.TYPE_ IS '证件类型：居民身份证、机动车驾驶证、从业资格证、服务资格证、驾驶培训证、机动车行驶证、道路运输证';
COMMENT ON COLUMN BS_CERT.CERT_NAME IS '证件简称';
COMMENT ON COLUMN BS_CERT.CERT_FULL_NAME IS '证件全称';
COMMENT ON COLUMN BS_CERT.LICENCER IS '发证机关';
COMMENT ON COLUMN BS_CERT.START_DATE IS '生效日期';
COMMENT ON COLUMN BS_CERT.ISSUE_DATE IS '发证日期';
COMMENT ON COLUMN BS_CERT.END_DATE IS '到期日期';
COMMENT ON COLUMN BS_CERT.FILE_DATE IS '创建时间';
COMMENT ON COLUMN BS_CERT.AUTHOR_ID IS '创建人ID';
COMMENT ON COLUMN BS_CERT.MODIFIER_ID IS '最后修改人ID';
COMMENT ON COLUMN BS_CERT.MODIFIED_DATE IS '最后修改时间';
ALTER TABLE BS_CERT ADD CONSTRAINT BSFK_CERT_AUTHORID FOREIGN KEY (AUTHOR_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
ALTER TABLE BS_CERT ADD CONSTRAINT BSFK_CERT_MODIFIER FOREIGN KEY (MODIFIER_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
CREATE INDEX BSIDX_CERT_CODE ON BS_CERT (CERT_CODE ASC);
CREATE INDEX BSIDX_CERT_NAME ON BS_CERT (CERT_NAME ASC);

-- 证件:居民身份证
create table BS_CERT_IDENTITY (
    ID number(19) NOT NULL,
    NAME varchar2(255),
    SEX number(1),
    BIRTHDATE date,
    NATION varchar2(255),
    ADDRESS varchar2(500),
    CONSTRAINT BSPK_CERT_IDENTITY primary key (ID)
);
COMMENT ON TABLE BS_CERT_IDENTITY IS '证件:居民身份证';
COMMENT ON COLUMN BS_CERT_IDENTITY.NAME IS '姓名';
COMMENT ON COLUMN BS_CERT_IDENTITY.SEX IS '性别(0-未设置,1-男,2-女)';
COMMENT ON COLUMN BS_CERT_IDENTITY.BIRTHDATE IS '出生日期';
COMMENT ON COLUMN BS_CERT_IDENTITY.NATION IS '民族';
COMMENT ON COLUMN BS_CERT_IDENTITY.ADDRESS IS '住址';
ALTER TABLE BS_CERT_IDENTITY ADD CONSTRAINT BSFK_CERT4IDENTITY_CERT FOREIGN KEY (ID) 
	REFERENCES BS_CERT (ID);

-- 证件:机动车驾驶证
create table BS_CERT_DRIVING (
    ID number(19) NOT NULL,
    NAME varchar2(255),
    SEX number(1),
    BIRTHDATE date,
    NATION varchar2(255),
    ADDRESS varchar2(500),
    MODEL varchar2(255),
    RECEIVEDATE date,
    VALIDFOR varchar2(255),
    ARCHIVENO varchar2(255),
    RECORD varchar2(255),
    CONSTRAINT BSPK_CERT_DRIVING primary key (ID)
);
COMMENT ON TABLE BS_CERT_DRIVING IS '证件:机动车驾驶证';
COMMENT ON COLUMN BS_CERT_DRIVING.NAME IS '姓名';
COMMENT ON COLUMN BS_CERT_DRIVING.SEX IS '性别(0-未设置,1-男,2-女)';
COMMENT ON COLUMN BS_CERT_DRIVING.BIRTHDATE IS '出生日期';
COMMENT ON COLUMN BS_CERT_DRIVING.NATION IS '国籍';
COMMENT ON COLUMN BS_CERT_DRIVING.ADDRESS IS '地址';
COMMENT ON COLUMN BS_CERT_DRIVING.MODEL IS '准驾车型';
COMMENT ON COLUMN BS_CERT_DRIVING.RECEIVEDATE IS '初次领证日期';
COMMENT ON COLUMN BS_CERT_DRIVING.VALIDFOR IS '有效期限';
COMMENT ON COLUMN BS_CERT_DRIVING.ARCHIVENO IS '档案编号';
COMMENT ON COLUMN BS_CERT_DRIVING.RECORD IS '记录';
ALTER TABLE BS_CERT_DRIVING ADD CONSTRAINT BSFK_CERT4DRIVING_CERT FOREIGN KEY (ID) 
	REFERENCES BS_CERT (ID);

-- 证件:从业资格证
create table BS_CERT_CYZG (
    ID number(19) NOT NULL,
    NAME varchar2(255),
    SEX number(1),
    BIRTHDATE date,
    NATION varchar2(255),
    ADDRESS varchar2(500),
    SCOPE_ varchar2(255),
    IDENTITY_NO varchar2(255),
    SERVICE_UNIT varchar2(500),
    CONSTRAINT BSPK_CERT_CYZG primary key (ID)
);
COMMENT ON TABLE BS_CERT_CYZG IS '证件:从业资格证';
COMMENT ON COLUMN BS_CERT_CYZG.NAME IS '姓名';
COMMENT ON COLUMN BS_CERT_CYZG.SEX IS '性别(0-未设置,1-男,2-女)';
COMMENT ON COLUMN BS_CERT_CYZG.BIRTHDATE IS '出生日期';
COMMENT ON COLUMN BS_CERT_CYZG.NATION IS '国籍';
COMMENT ON COLUMN BS_CERT_CYZG.ADDRESS IS '地址';
COMMENT ON COLUMN BS_CERT_CYZG.SCOPE_ IS '从业资格';
COMMENT ON COLUMN BS_CERT_CYZG.IDENTITY_NO IS '身份证件号';
COMMENT ON COLUMN BS_CERT_CYZG.SERVICE_UNIT IS '服务单位';
ALTER TABLE BS_CERT_CYZG ADD CONSTRAINT BSFK_CERT4CYZG_CERT FOREIGN KEY (ID) 
	REFERENCES BS_CERT (ID);

-- 证件:服务资格证
create table BS_CERT_FWZG (
    ID number(19) NOT NULL,
    NAME varchar2(255),
    SEX number(1),
    BIRTHDATE date,
    NATION varchar2(255),
    ADDRESS varchar2(500),
    LEVEL_ varchar2(255),
    SERVICE_UNIT varchar2(500),
    CONSTRAINT BSPK_CERT_FWZG primary key (ID)
);
COMMENT ON TABLE BS_CERT_FWZG IS '证件:服务资格证';
COMMENT ON COLUMN BS_CERT_FWZG.NAME IS '姓名';
COMMENT ON COLUMN BS_CERT_FWZG.SEX IS '性别(0-未设置,1-男,2-女)';
COMMENT ON COLUMN BS_CERT_FWZG.BIRTHDATE IS '出生日期';
COMMENT ON COLUMN BS_CERT_FWZG.NATION IS '国籍';
COMMENT ON COLUMN BS_CERT_FWZG.ADDRESS IS '地址';
COMMENT ON COLUMN BS_CERT_FWZG.LEVEL_ IS '等级';
COMMENT ON COLUMN BS_CERT_FWZG.SERVICE_UNIT IS '服务单位';
ALTER TABLE BS_CERT_FWZG ADD CONSTRAINT BSFK_CERT4FWZG_CERT FOREIGN KEY (ID) 
	REFERENCES BS_CERT (ID);

-- 证件:驾驶培训证
create table BS_CERT_JSPX (
    ID number(19) NOT NULL,
    NAME varchar2(255),
    SEX number(1),
    BIRTHDATE date,
    NATION varchar2(255),
    ADDRESS varchar2(500),
    DOMAIN varchar2(255),
    TRAIN_DATE date,
    TRAIN_HOUR number(3),
    GRADE1 number(3),
    GRADE2 varchar2(10),
    GRADE3 varchar2(10),
    IDENTITY_NO varchar2(255),
    CONSTRAINT BSPK_CERT_JSPX primary key (ID)
);
COMMENT ON TABLE BS_CERT_JSPX IS '证件:驾驶培训证';
COMMENT ON COLUMN BS_CERT_JSPX.NAME IS '姓名';
COMMENT ON COLUMN BS_CERT_JSPX.SEX IS '性别(0-未设置,1-男,2-女)';
COMMENT ON COLUMN BS_CERT_JSPX.BIRTHDATE IS '出生日期';
COMMENT ON COLUMN BS_CERT_JSPX.NATION IS '国籍';
COMMENT ON COLUMN BS_CERT_JSPX.ADDRESS IS '地址';
COMMENT ON COLUMN BS_CERT_JSPX.DOMAIN IS '培训专业';
COMMENT ON COLUMN BS_CERT_JSPX.TRAIN_DATE IS '培训时间';
COMMENT ON COLUMN BS_CERT_JSPX.TRAIN_HOUR IS '培训学时';
COMMENT ON COLUMN BS_CERT_JSPX.GRADE1 IS '理论知识考核成绩';
COMMENT ON COLUMN BS_CERT_JSPX.GRADE2 IS '操作技能考核成绩';
COMMENT ON COLUMN BS_CERT_JSPX.GRADE3 IS '评定成绩';
COMMENT ON COLUMN BS_CERT_JSPX.IDENTITY_NO IS '身份证件号';
ALTER TABLE BS_CERT_JSPX ADD CONSTRAINT BSFK_CERT4JSPX_CERT FOREIGN KEY (ID) 
	REFERENCES BS_CERT (ID);

-- 证件:道路运输证
CREATE TABLE BS_CERT_ROADTRANSPORT(
	ID                   NUMBER(19) NOT NULL,
	FACTORY              VARCHAR2(255),
	PLATE                VARCHAR2(255),
	OWNER                VARCHAR2(255),
	ADDRESS              VARCHAR2(255),
	BS_CERT_NO           VARCHAR2(255),
	SEAT                 VARCHAR2(255),
	DIM_LEN              NUMBER(19),
	DIM_WIDTH            NUMBER(19),
	DIM_HEIGHT           NUMBER(19),
	SCOPE_               VARCHAR2(255),
	LEVEL_               VARCHAR2(255),
	DESC_                VARCHAR2(255),
  	CONSTRAINT BSPK_CERT_ROADTRANSPORT PRIMARY KEY (ID)
);
COMMENT ON TABLE BS_CERT_ROADTRANSPORT IS '证件：道路运输证';
COMMENT ON COLUMN BS_CERT_ROADTRANSPORT.FACTORY IS '品牌型号，如“桑塔纳SVW7182QQD”';
COMMENT ON COLUMN BS_CERT_ROADTRANSPORT.PLATE IS '车牌及号码，如“粤AC4X74”';
COMMENT ON COLUMN BS_CERT_ROADTRANSPORT.OWNER IS '业户名称';
COMMENT ON COLUMN BS_CERT_ROADTRANSPORT.ADDRESS IS '地址';
COMMENT ON COLUMN BS_CERT_ROADTRANSPORT.BS_CERT_NO IS '经营许可证号';
COMMENT ON COLUMN BS_CERT_ROADTRANSPORT.SEAT IS '吨（座）位';
COMMENT ON COLUMN BS_CERT_ROADTRANSPORT.DIM_LEN IS '外廓尺寸：长，单位MM';
COMMENT ON COLUMN BS_CERT_ROADTRANSPORT.DIM_WIDTH IS '外廓尺寸：宽，单位MM';
COMMENT ON COLUMN BS_CERT_ROADTRANSPORT.DIM_HEIGHT IS '外廓尺寸：高，单位MM';
COMMENT ON COLUMN BS_CERT_ROADTRANSPORT.SCOPE_ IS '经营范围';
COMMENT ON COLUMN BS_CERT_ROADTRANSPORT.LEVEL_ IS '技术等级';
COMMENT ON COLUMN BS_CERT_ROADTRANSPORT.DESC_ IS '备注';
ALTER TABLE BS_CERT_ROADTRANSPORT ADD CONSTRAINT BSFK_CERT4ROADTRANSPORT_CERT FOREIGN KEY (ID) 
	REFERENCES BS_CERT (ID);
  
-- 证件:机动车行驶证
CREATE TABLE BS_CERT_VEHICELICENSE(
	ID                   NUMBER(19) NOT NULL,
	FACTORY              VARCHAR2(255),
	PLATE                VARCHAR2(255),
	OWNER                VARCHAR2(255),
	ADDRESS              VARCHAR2(255),
	USE_CHARACTER        VARCHAR2(255),
	VEHICE_TYPE          VARCHAR2(255),
	VIN                  VARCHAR2(255),
	ENGINE_NO            VARCHAR2(255),
	REGISTER_DATE        DATE,
	ARCHIVE_NO           VARCHAR2(255),
	DIM_LEN              number(19),
	DIM_WIDTH            number(19),
	DIM_HEIGHT           number(19),
	TOTAL_WEIGHT         number(19),
	CURB_WEIGHT          number(19),
	ACCESS_WEIGHT        number(19),
	PULL_WEIGHT          number(19),
	ACCESS_COUNT         number(19),
	SCRAP_DATE           DATE,
	DESC_                VARCHAR2(500),
	RECORD_              VARCHAR2(500),
	CONSTRAINT BSPK_CERT_VEHICELICENSE PRIMARY KEY (ID)
);
COMMENT ON TABLE BS_CERT_VEHICELICENSE IS '证件：机动车行驶证';
COMMENT ON COLUMN BS_CERT_VEHICELICENSE.FACTORY IS '品牌型号，如“桑塔纳SVW7182QQD”';
COMMENT ON COLUMN BS_CERT_VEHICELICENSE.PLATE IS '车牌及号码，如“粤AC4X74”';
COMMENT ON COLUMN BS_CERT_VEHICELICENSE.OWNER IS '业户名称';
COMMENT ON COLUMN BS_CERT_VEHICELICENSE.ADDRESS IS '地址';
COMMENT ON COLUMN BS_CERT_VEHICELICENSE.USE_CHARACTER IS '使用性质';
COMMENT ON COLUMN BS_CERT_VEHICELICENSE.VEHICE_TYPE IS '车辆类型';
COMMENT ON COLUMN BS_CERT_VEHICELICENSE.VIN IS '车辆识别代号';
COMMENT ON COLUMN BS_CERT_VEHICELICENSE.ENGINE_NO IS '发动机号码';
COMMENT ON COLUMN BS_CERT_VEHICELICENSE.REGISTER_DATE IS '注册日期';
COMMENT ON COLUMN BS_CERT_VEHICELICENSE.ARCHIVE_NO IS '档案编号';
COMMENT ON COLUMN BS_CERT_VEHICELICENSE.DIM_LEN IS '外廓尺寸：长，单位MM';
COMMENT ON COLUMN BS_CERT_VEHICELICENSE.DIM_WIDTH IS '外廓尺寸：宽，单位MM';
COMMENT ON COLUMN BS_CERT_VEHICELICENSE.DIM_HEIGHT IS '外廓尺寸：高，单位MM';
COMMENT ON COLUMN BS_CERT_VEHICELICENSE.TOTAL_WEIGHT IS '总质量，单位KG';
COMMENT ON COLUMN BS_CERT_VEHICELICENSE.CURB_WEIGHT IS '整备质量，单位KG';
COMMENT ON COLUMN BS_CERT_VEHICELICENSE.ACCESS_WEIGHT IS '核定载质量，单位KG';
COMMENT ON COLUMN BS_CERT_VEHICELICENSE.PULL_WEIGHT IS '准牵引总质量，单位KG';
COMMENT ON COLUMN BS_CERT_VEHICELICENSE.ACCESS_COUNT IS '核定载人数';
COMMENT ON COLUMN BS_CERT_VEHICELICENSE.SCRAP_DATE IS '强制报废日期';
COMMENT ON COLUMN BS_CERT_VEHICELICENSE.DESC_ IS '备注';
COMMENT ON COLUMN BS_CERT_VEHICELICENSE.RECORD_ IS '检验记录';
ALTER TABLE BS_CERT_VEHICELICENSE ADD CONSTRAINT BSFK_CERT4VEHICELICENSE_CERT FOREIGN KEY (ID) 
	REFERENCES BS_CERT (ID);


-- 司机责任人
create table BS_CARMAN (
    ID number(19) NOT NULL,
    UID_ varchar2(36) NOT NULL,
    STATUS_ number(1) NOT NULL,
    TYPE_ number(1) default 0 NOT NULL,
    NAME varchar2(255) NOT NULL,
    ORDER_ varchar2(100),
    SEX number(1) default 0 NOT NULL,
    WORK_DATE date,
    ORIGIN varchar2(255),
    REGION_  number(1),
    HOUSE_TYPE varchar2(255),
    BIRTHDATE date,
    FORMER_UNIT varchar2(500),
    ADDRESS varchar2(500),
    ADDRESS1 varchar2(500),
    PHONE varchar2(500),
    PHONE1 varchar2(500),
    MODEL_                VARCHAR2(255),
	LEVEL_ varchar2(255),
    CERT_IDENTITY        VARCHAR2(255),
    CERT_DRIVING         VARCHAR2(255),
    CERT_DRIVING_ARCHIVE VARCHAR2(255),
    CERT_DRIVING_FIRST_DATE DATE,
    CERT_DRIVING_START_DATE DATE,
    CERT_DRIVING_END_DATE DATE,
    CERT_FWZG            VARCHAR2(255),
	CERT_FWZG_ID            VARCHAR2(255),
    CERT_CYZG            VARCHAR2(255),
    DRIVING_STATUS        number(1),
    OLD_UNIT_NAME        VARCHAR2(255),
    EXT_ZRR              VARCHAR2(255),
    GZ                   number(1) default 0,
    ACCESS_CERTS         VARCHAR2(255),
    DESC_                VARCHAR2(4000),
    FILE_DATE date NOT NULL,
    AUTHOR_ID number(19) NOT NULL,
    MODIFIER_ID number(19),
    MODIFIED_DATE date,
    CHARGER		VARCHAR2(255),
    CONSTRAINT BSPK_CARMAN primary key (ID)
);
COMMENT ON TABLE BS_CARMAN IS '司机责任人';
COMMENT ON COLUMN BS_CARMAN.UID_ IS 'UID';
COMMENT ON COLUMN BS_CARMAN.STATUS_ IS '状态：0-启用中,1-已禁用,2-已删除';
COMMENT ON COLUMN BS_CARMAN.TYPE_ IS '类别:0-司机,1-责任人,2-司机和责任人';
COMMENT ON COLUMN BS_CARMAN.NAME IS '姓名';
COMMENT ON COLUMN BS_CARMAN.ORDER_ IS '排序号';
COMMENT ON COLUMN BS_CARMAN.SEX IS '性别：0-未设置,1-男,2-女';
COMMENT ON COLUMN BS_CARMAN.WORK_DATE IS '入职日期';
COMMENT ON COLUMN BS_CARMAN.ORIGIN IS '籍贯';
COMMENT ON COLUMN BS_CARMAN.REGION_ IS '区域：0-未定义，1-本市，2-本省，3-外省';
COMMENT ON COLUMN BS_CARMAN.HOUSE_TYPE IS '户口类型';
COMMENT ON COLUMN BS_CARMAN.BIRTHDATE IS '出生日期';
COMMENT ON COLUMN BS_CARMAN.FORMER_UNIT IS '入职原单位';
COMMENT ON COLUMN BS_CARMAN.ADDRESS IS '身份证住址';
COMMENT ON COLUMN BS_CARMAN.ADDRESS1 IS '暂住地址';
COMMENT ON COLUMN BS_CARMAN.PHONE IS '电话';
COMMENT ON COLUMN BS_CARMAN.PHONE1 IS '电话1';
COMMENT ON COLUMN BS_CARMAN.FILE_DATE IS '创建时间';
COMMENT ON COLUMN BS_CARMAN.AUTHOR_ID IS '创建人ID';
COMMENT ON COLUMN BS_CARMAN.MODIFIER_ID IS '最后修改人ID';
COMMENT ON COLUMN BS_CARMAN.MODIFIED_DATE IS '最后修改时间';
COMMENT ON COLUMN BS_CARMAN.MODEL_ IS '准驾车型';
COMMENT ON COLUMN BS_CARMAN.LEVEL_ IS '司机等级';
COMMENT ON COLUMN BS_CARMAN.CERT_IDENTITY IS '身份证号';
COMMENT ON COLUMN BS_CARMAN.CERT_DRIVING IS '驾驶证号';
COMMENT ON COLUMN BS_CARMAN.CERT_DRIVING_ARCHIVE IS '驾驶证档案号';
COMMENT ON COLUMN BS_CARMAN.CERT_DRIVING_FIRST_DATE IS '初次领证日期';
COMMENT ON COLUMN BS_CARMAN.CERT_DRIVING_START_DATE IS '驾驶证起效日期';
COMMENT ON COLUMN BS_CARMAN.CERT_DRIVING_END_DATE IS '驾驶证过期日期';
COMMENT ON COLUMN BS_CARMAN.CERT_FWZG IS '服务资格证号';
COMMENT ON COLUMN BS_CARMAN.CERT_FWZG_ID IS '服务资格证号';
COMMENT ON COLUMN BS_CARMAN.CERT_CYZG IS '从业资格证号';
COMMENT ON COLUMN BS_CARMAN.DRIVING_STATUS IS '驾驶状态：0-未定义，1-正班，2-副班，3-顶班';
COMMENT ON COLUMN BS_CARMAN.OLD_UNIT_NAME IS '分支机构：用于历史数据的保存';
COMMENT ON COLUMN BS_CARMAN.EXT_ZRR IS '责任人：用于历史数据的保存';
COMMENT ON COLUMN BS_CARMAN.GZ IS '驾驶证是否广州:0-否,1-是';
COMMENT ON COLUMN BS_CARMAN.ACCESS_CERTS IS '已考取证件：历史数据保存';
COMMENT ON COLUMN BS_CARMAN.DESC_ IS '备注';
COMMENT ON COLUMN BS_CARMAN.CHARGER IS '责任人信息';
ALTER TABLE BS_CARMAN ADD CONSTRAINT BSFK_CARMAN_AUTHOR FOREIGN KEY (AUTHOR_ID) 
	REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
ALTER TABLE BS_CARMAN ADD CONSTRAINT BSFK_CARMAN_MODIFIER FOREIGN KEY (MODIFIER_ID) 
	REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
CREATE INDEX BSIDX_CARMAN_STATUS ON BS_CARMAN (STATUS_);

-- 司机责任人与证件的关联
CREATE TABLE BS_CARMAN_CERT (
    MAN_ID number(19) NOT NULL,
    CERT_ID number(19) NOT NULL,
    CONSTRAINT BSPK_CARMAN_CERT PRIMARY KEY (MAN_ID,CERT_ID)
);
COMMENT ON TABLE BS_CARMAN_CERT IS '司机责任人与证件的关联';
COMMENT ON COLUMN BS_CARMAN_CERT.MAN_ID IS '司机责任人ID';
COMMENT ON COLUMN BS_CARMAN_CERT.CERT_ID IS '证件ID';
ALTER TABLE BS_CARMAN_CERT ADD CONSTRAINT BSFK_CARMANCERT_MAN FOREIGN KEY (MAN_ID) 
	REFERENCES BS_CARMAN (ID);
ALTER TABLE BS_CARMAN_CERT ADD CONSTRAINT BSFK_CARMANCERT_CERT FOREIGN KEY (CERT_ID) 
	REFERENCES BS_CERT (ID);


-- 车辆 
CREATE TABLE BS_CAR (
   ID                   NUMBER(19)           NOT NULL,
   UID_                 VARCHAR2(36)         NOT NULL,
   STATUS_              NUMBER(1)            NOT NULL,
   OLD_UNIT_NAME        VARCHAR2(255),
   MOTORCADE_ID         NUMBER(19),
   DRIVER		VARCHAR2(255),
   CHARGER		VARCHAR2(255),
   BS_TYPE              VARCHAR2(255),
   CODE                 VARCHAR2(255),
   ORIGIN_NO            VARCHAR2(255),
   PLATE_TYPE           VARCHAR2(255),
   PLATE_NO             VARCHAR2(255),
   VIN                  VARCHAR2(255),
   FACTORY_TYPE         VARCHAR2(255),
   FACTORY_MODEL        VARCHAR2(255),
   REGISTER_DATE        DATE,
   OPERATE_DATE         DATE,
   SCRAP_DATE           DATE,
   FACTORY_DATE         DATE,
   REGISTER_NO          VARCHAR2(255),
   LEVEL_               VARCHAR2(255),
   COLOR                VARCHAR2(255),
   ENGINE_NO            VARCHAR2(255),
   ENGINE_TYPE          VARCHAR2(255),
   FUEL_TYPE            VARCHAR2(255),
   DISPLACEMENT         NUMBER(19),
   POWER                NUMBER(19,2),
   TURN_TYPE            VARCHAR2(255),
   TIRE_COUNT           NUMBER(19),
   TIRE_STANDARD        VARCHAR2(255),
   AXIS_DISTANCE        NUMBER(19),
   AXIS_COUNT           NUMBER(19),
   PIECE_COUNT          NUMBER(19),
   DIM_LEN              NUMBER(19),
   DIM_WIDTH            NUMBER(19),
   DIM_HEIGHT           NUMBER(19),
   TOTAL_WEIGHT         NUMBER(19),
   ACCESS_WEIGHT        NUMBER(19),
   ACCESS_COUNT         NUMBER(19),
   ORIGINAL_VALUE       NUMBER(19,2),
   INVOICE_NO1          VARCHAR2(255),
   INVOICE_NO2          VARCHAR2(255),
   PAYMENT_TYPE         VARCHAR2(255),
   CERT_NO1             VARCHAR2(255),
   CERT_NO2             VARCHAR2(255),
   CERT_NO3             VARCHAR2(255),
   TAXIMETER_FACTORY    VARCHAR2(255),
   TAXIMETER_TYPE       VARCHAR2(255),
   TAXIMETER_NO         VARCHAR2(255),
   DESC1                VARCHAR2(4000),
   DESC2                VARCHAR2(4000),
   DESC3                VARCHAR2(4000),
   FILE_DATE            DATE NOT NULL,
   AUTHOR_ID            NUMBER(19) NOT NULL,
   MODIFIER_ID          NUMBER(19),
   MODIFIED_DATE        DATE,
   CONSTRAINT BSPK_CAR PRIMARY KEY (ID)
);
COMMENT ON TABLE BS_CAR IS '车辆';
COMMENT ON COLUMN BS_CAR.STATUS_ IS '状态：0-启用中,1-已禁用,2-已删除';
COMMENT ON COLUMN BS_CAR.OLD_UNIT_NAME IS '所属单位';
COMMENT ON COLUMN BS_CAR.MOTORCADE_ID IS '所属车队ID';
COMMENT ON COLUMN BS_CAR.DRIVER IS '司机信息';
COMMENT ON COLUMN BS_CAR.CHARGER IS '责任人信息';
COMMENT ON COLUMN BS_CAR.BS_TYPE IS '营运性质';
COMMENT ON COLUMN BS_CAR.CODE IS '自编号';
COMMENT ON COLUMN BS_CAR.ORIGIN_NO IS '原车号';
COMMENT ON COLUMN BS_CAR.PLATE_TYPE IS '车牌归属，如“粤A”';
COMMENT ON COLUMN BS_CAR.PLATE_NO IS '车牌号码，如“C4X74”';
COMMENT ON COLUMN BS_CAR.VIN IS '车辆识别代号';
COMMENT ON COLUMN BS_CAR.FACTORY_TYPE IS '厂牌类型，如“桑塔纳”';
COMMENT ON COLUMN BS_CAR.FACTORY_MODEL IS '厂牌型号，如“SVW7182QQD”';
COMMENT ON COLUMN BS_CAR.REGISTER_DATE IS '登记日期';
COMMENT ON COLUMN BS_CAR.OPERATE_DATE IS '投产日期';
COMMENT ON COLUMN BS_CAR.SCRAP_DATE IS '报废日期';
COMMENT ON COLUMN BS_CAR.FACTORY_DATE IS '出厂日期';
COMMENT ON COLUMN BS_CAR.REGISTER_NO IS '机动车登记编号';
COMMENT ON COLUMN BS_CAR.LEVEL_ IS '车辆定级';
COMMENT ON COLUMN BS_CAR.COLOR IS '颜色';
COMMENT ON COLUMN BS_CAR.ENGINE_NO IS '发动机号码';
COMMENT ON COLUMN BS_CAR.ENGINE_TYPE IS '发动机类型';
COMMENT ON COLUMN BS_CAR.FUEL_TYPE IS '燃料类型，如“汽油”';
COMMENT ON COLUMN BS_CAR.DISPLACEMENT IS '排量，单位ML';
COMMENT ON COLUMN BS_CAR.POWER IS '功率，单位KW';
COMMENT ON COLUMN BS_CAR.TURN_TYPE IS '转向方式，如“方向盘”';
COMMENT ON COLUMN BS_CAR.TIRE_COUNT IS '轮胎数';
COMMENT ON COLUMN BS_CAR.TIRE_STANDARD IS '轮胎规格';
COMMENT ON COLUMN BS_CAR.AXIS_DISTANCE IS '轴距';
COMMENT ON COLUMN BS_CAR.AXIS_COUNT IS '轴数';
COMMENT ON COLUMN BS_CAR.PIECE_COUNT IS '后轴钢板弹簧片数';
COMMENT ON COLUMN BS_CAR.DIM_LEN IS '外廓尺寸：长，单位MM';
COMMENT ON COLUMN BS_CAR.DIM_WIDTH IS '外廓尺寸：宽，单位MM';
COMMENT ON COLUMN BS_CAR.DIM_HEIGHT IS '外廓尺寸：高，单位MM';
COMMENT ON COLUMN BS_CAR.TOTAL_WEIGHT IS '总质量，单位KG';
COMMENT ON COLUMN BS_CAR.ACCESS_WEIGHT IS '核定载质量，单位KG';
COMMENT ON COLUMN BS_CAR.ACCESS_COUNT IS '核定载人数';
COMMENT ON COLUMN BS_CAR.ORIGINAL_VALUE IS '固定资产原值，单位元';
COMMENT ON COLUMN BS_CAR.INVOICE_NO1 IS '购车发票号';
COMMENT ON COLUMN BS_CAR.INVOICE_NO2 IS '购置税发票号';
COMMENT ON COLUMN BS_CAR.PAYMENT_TYPE IS '缴费日';
COMMENT ON COLUMN BS_CAR.CERT_NO1 IS '购置税证号';
COMMENT ON COLUMN BS_CAR.CERT_NO2 IS '经营权使用证号';
COMMENT ON COLUMN BS_CAR.CERT_NO3 IS '强检证号';
COMMENT ON COLUMN BS_CAR.TAXIMETER_FACTORY IS '计价器制造厂';
COMMENT ON COLUMN BS_CAR.TAXIMETER_TYPE IS '计价器型号';
COMMENT ON COLUMN BS_CAR.TAXIMETER_NO IS '计价器出厂编号';
COMMENT ON COLUMN BS_CAR.DESC1 IS '备注1';
COMMENT ON COLUMN BS_CAR.DESC2 IS '备注2';
COMMENT ON COLUMN BS_CAR.DESC3 IS '备注3';
COMMENT ON COLUMN BS_CAR.FILE_DATE IS '创建时间';
COMMENT ON COLUMN BS_CAR.AUTHOR_ID IS '创建人ID';
COMMENT ON COLUMN BS_CAR.MODIFIER_ID IS '最后修改人ID';
COMMENT ON COLUMN BS_CAR.MODIFIED_DATE IS '最后修改时间';
ALTER TABLE BS_CAR ADD CONSTRAINT BSFK_CAR_AUTHOR FOREIGN KEY (AUTHOR_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
ALTER TABLE BS_CAR ADD CONSTRAINT BSFK_CAR_MODIFIER FOREIGN KEY (MODIFIER_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
ALTER TABLE BS_CAR ADD CONSTRAINT BSFK_CAR_MOTORCADEID FOREIGN KEY (MOTORCADE_ID)
      REFERENCES BS_MOTORCADE (ID);
CREATE INDEX BSIDX_CAR_STATUS ON BS_CAR (STATUS_);
CREATE INDEX BSIDX_CAR_MOTORCADE ON BS_CAR (MOTORCADE_ID);


-- 车辆与证件的关联
CREATE TABLE BS_CAR_CERT (
    CAR_ID number(19) NOT NULL,
    CERT_ID number(19) NOT NULL,
    CONSTRAINT BSPK_CAR_CERT PRIMARY KEY (CAR_ID,CERT_ID)
);
COMMENT ON TABLE BS_CAR_CERT IS '车辆与证件的关联';
COMMENT ON COLUMN BS_CAR_CERT.CAR_ID IS '车辆ID';
COMMENT ON COLUMN BS_CAR_CERT.CERT_ID IS '证件ID';
ALTER TABLE BS_CAR_CERT ADD CONSTRAINT BSFK_CARCERT_CAR FOREIGN KEY (CAR_ID) 
	REFERENCES BS_CAR (ID);
ALTER TABLE BS_CAR_CERT ADD CONSTRAINT BSFK_CARCERT_CERT FOREIGN KEY (CERT_ID) 
	REFERENCES BS_CERT (ID);


-- 合同
CREATE TABLE BS_CONTRACT 
(
   ID                   NUMBER(19)           NOT NULL,
   UID_                 VARCHAR2(36)         NOT NULL,
   PID                  NUMBER(19),
   STATUS_              NUMBER(1)            NOT NULL,
   VER_MAJOR            NUMBER(2),
   VER_MINOR            NUMBER(3),
   PATCH_NO             VARCHAR2(255)        NOT NULL,
   MAIN                 NUMBER(1)            NOT NULL,
   WORD_NO              VARCHAR2(255),
   CODE                 VARCHAR2(255)        NOT NULL,
   TYPE_                NUMBER(1)            NOT NULL,
   OP_TYPE              NUMBER(1)            NOT NULL,
   TRANSACTOR_ID        NUMBER(19),
   TRANSACTOR_NAME      VARCHAR2(255),
   SIGN_DATE            DATE,
   START_DATE           DATE                 NOT NULL,
   END_DATE             DATE                 NOT NULL,
   CONTENT              VARCHAR2(4000),
   EXT_STR1             VARCHAR2(255),
   EXT_STR2             VARCHAR2(255),
   EXT_STR3             VARCHAR2(255),
   EXT_NUM1             NUMBER(19),
   EXT_NUM2             NUMBER(19),
   EXT_NUM3             NUMBER(19),
   FILE_DATE            DATE                 NOT NULL,
   AUTHOR_ID            NUMBER(19)           NOT NULL,
   MODIFIER_ID          NUMBER(19),
   MODIFIED_DATE        DATE,
   CONSTRAINT PK_BS_CONTRACT PRIMARY KEY (ID)
);

COMMENT ON TABLE BS_CONTRACT IS'合同';
COMMENT ON COLUMN BS_CONTRACT.STATUS_ IS'状态：0-正常,1-失效,2-离职';
COMMENT ON COLUMN BS_CONTRACT.VER_MAJOR IS '主版本号';
COMMENT ON COLUMN BS_CONTRACT.VER_MINOR IS '次版本号';
COMMENT ON COLUMN BS_CONTRACT.PATCH_NO IS '批号';
COMMENT ON COLUMN BS_CONTRACT.MAIN IS '主体: 0-当前版本,1-历史版本';
COMMENT ON COLUMN BS_CONTRACT.WORD_NO IS '文书号';
COMMENT ON COLUMN BS_CONTRACT.CODE IS '合同号';
COMMENT ON COLUMN BS_CONTRACT.TYPE_ IS '合同类型：1-司机劳动合同、2-责任人合同';
COMMENT ON COLUMN BS_CONTRACT.OP_TYPE IS '操作类型: 1-新建,2-维护,3-转车,4-续约,5-离职';
COMMENT ON COLUMN BS_CONTRACT.TRANSACTOR_ID IS '经办人ID';
COMMENT ON COLUMN BS_CONTRACT.TRANSACTOR_NAME IS '经办人姓名';
COMMENT ON COLUMN BS_CONTRACT.SIGN_DATE IS '签订日期';
COMMENT ON COLUMN BS_CONTRACT.START_DATE IS '生效日期';
COMMENT ON COLUMN BS_CONTRACT.END_DATE IS '到期日期';
COMMENT ON COLUMN BS_CONTRACT.CONTENT IS '合同内容';
COMMENT ON COLUMN BS_CONTRACT.EXT_STR1 IS '车牌';
COMMENT ON COLUMN BS_CONTRACT.EXT_STR2 IS '司机责任人姓名';
COMMENT ON COLUMN BS_CONTRACT.EXT_STR3 IS '字符扩展域3';
COMMENT ON COLUMN BS_CONTRACT.EXT_NUM1 IS '数字扩展域1';
COMMENT ON COLUMN BS_CONTRACT.EXT_NUM2 IS '数字扩展域2';
COMMENT ON COLUMN BS_CONTRACT.EXT_NUM3 IS '数字扩展域3';
COMMENT ON COLUMN BS_CONTRACT.FILE_DATE IS '创建时间';
COMMENT ON COLUMN BS_CONTRACT.AUTHOR_ID IS '创建人ID';
COMMENT ON COLUMN BS_CONTRACT.MODIFIER_ID IS '最后修改人ID';
COMMENT ON COLUMN BS_CONTRACT.MODIFIED_DATE IS '最后修改时间';
ALTER TABLE BS_CONTRACT ADD CONSTRAINT BSFK_CONTRACT_AUTHOR FOREIGN KEY (AUTHOR_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
ALTER TABLE BS_CONTRACT ADD CONSTRAINT BSFK_CONTRACT_MODIFIER FOREIGN KEY (MODIFIER_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
ALTER TABLE BS_CONTRACT ADD CONSTRAINT BSFK_CONTR_REFERENCE_BS_CONTR FOREIGN KEY (PID)
      REFERENCES BS_CONTRACT (ID);
CREATE INDEX BSIDX_CONTRACT_STATUS ON BS_CONTRACT (STATUS_);
CREATE INDEX BSIDX_CONTRACT_PATCH_NO ON BS_CONTRACT (PATCH_NO);

-- 司机劳动合同
CREATE TABLE BS_CONTRACT_LABOUR 
(
   ID                   NUMBER(19)           NOT NULL,
   CERT_NO              VARCHAR2(255)        NOT NULL,
   CERT_IDENTITY        VARCHAR2(255),
   SEX                  NUMBER(1),
   BIRTHDATE            DATE,
   AGE                  NUMBER(3),
   ORIGIN               VARCHAR2(255),
   HOUSE_TYPE           VARCHAR2(255),
   DOLE                 NUMBER(1)            DEFAULT 0,
   FUNDING              NUMBER(1)            DEFAULT 0,
   INSURCODE            VARCHAR2(255),
   JOINDATE             DATE,
   REGISTER_DATE        DATE,
   INSURE_DATE          DATE,
   BS_TYPE              VARCHAR2(255),
   BUY_UNIT             VARCHAR2(255),
   INSURANCE_TYPE       VARCHAR(255),
   IS_IQAMA             NUMBER(1)            DEFAULT 0,
   IS_ACCOUNT_BOOK      NUMBER(1)            DEFAULT 0,
   IS_IDENTITY_CARDS    NUMBER(1)            DEFAULT 0,
   IS_FPC               NUMBER(1)            DEFAULT 0,
   IS_UNEMPLOYED        NUMBER(1)            DEFAULT 0,
   IS_HEALTHFORM        NUMBER(1)            DEFAULT 0,
   IS_PHOTO             NUMBER(1)            DEFAULT 0,
   BREEDING_DATE        DATE,
   GET_STARTDATE        DATE,
   GET_ENDDATE          DATE,
   REMARK               VARCHAR2(255),
   STOPDATE		DATE,
   LEAVEDATE		DATE,
   CONSTRAINT PK_BS_CONTRACT_LABOUR PRIMARY KEY (ID)
);

COMMENT ON TABLE BS_CONTRACT_LABOUR IS '司机劳动合同';
COMMENT ON COLUMN BS_CONTRACT_LABOUR.CERT_NO IS '资格证号';
COMMENT ON COLUMN BS_CONTRACT_LABOUR.CERT_IDENTITY IS '身份证号';
COMMENT ON COLUMN BS_CONTRACT_LABOUR.SEX IS '性别(0-未设置,1-男,2-女)';
COMMENT ON COLUMN BS_CONTRACT_LABOUR.BIRTHDATE IS '出生日期';
COMMENT ON COLUMN BS_CONTRACT_LABOUR.AGE IS '年龄: 通过出生年月算出';
COMMENT ON COLUMN BS_CONTRACT_LABOUR.ORIGIN IS '籍贯';
COMMENT ON COLUMN BS_CONTRACT_LABOUR.HOUSE_TYPE IS '户口类型';
COMMENT ON COLUMN BS_CONTRACT_LABOUR.DOLE IS '个人岗位补贴:0-无,1-有';
COMMENT ON COLUMN BS_CONTRACT_LABOUR.FUNDING IS '对公社保资助';
COMMENT ON COLUMN BS_CONTRACT_LABOUR.INSURCODE IS '社保号';
COMMENT ON COLUMN BS_CONTRACT_LABOUR.JOINDATE IS '参保日期';
COMMENT ON COLUMN BS_CONTRACT_LABOUR.REGISTER_DATE IS '车辆登记日期';
COMMENT ON COLUMN BS_CONTRACT_LABOUR.INSURE_DATE IS '申领日期';
COMMENT ON COLUMN BS_CONTRACT_LABOUR.BS_TYPE IS '营运性质';
COMMENT ON COLUMN BS_CONTRACT_LABOUR.BUY_UNIT IS '购买单位';
COMMENT ON COLUMN BS_CONTRACT_LABOUR.INSURANCE_TYPE IS '社保险种';
COMMENT ON COLUMN BS_CONTRACT_LABOUR.IS_IQAMA IS '是否缴交暂住证';
COMMENT ON COLUMN BS_CONTRACT_LABOUR.IS_ACCOUNT_BOOK IS '是否缴交户口薄';
COMMENT ON COLUMN BS_CONTRACT_LABOUR.IS_IDENTITY_CARDS IS '是否缴交身份证';
COMMENT ON COLUMN BS_CONTRACT_LABOUR.IS_FPC IS '是否缴交计生证';
COMMENT ON COLUMN BS_CONTRACT_LABOUR.IS_UNEMPLOYED IS '是否缴交失业就业手册';
COMMENT ON COLUMN BS_CONTRACT_LABOUR.IS_HEALTHFORM IS '是否缴交体检表';
COMMENT ON COLUMN BS_CONTRACT_LABOUR.IS_PHOTO IS '是否缴交照片';
COMMENT ON COLUMN BS_CONTRACT_LABOUR.BREEDING_DATE IS '生育日期';
COMMENT ON COLUMN BS_CONTRACT_LABOUR.GET_STARTDATE IS '申领开始日期';
COMMENT ON COLUMN BS_CONTRACT_LABOUR.GET_ENDDATE IS '申领结束日期';
COMMENT ON COLUMN BS_CONTRACT_LABOUR.REMARK IS '备注';
COMMENT ON COLUMN BS_CONTRACT_LABOUR.STOPDATE IS '停保日期';
COMMENT ON COLUMN BS_CONTRACT_LABOUR.LEAVEDATE IS '离职日期';
ALTER TABLE BS_CONTRACT_LABOUR ADD CONSTRAINT BSFK_CONTRACT4LABOUR_CONTRACT FOREIGN KEY (ID)
      REFERENCES BS_CONTRACT (ID);

-- 责任人合同
CREATE TABLE BS_CONTRACT_CHARGER (
   ID                   NUMBER(19)           NOT NULL,
   SIGN_TYPE            VARCHAR2(255)        NOT NULL,
   LOGOUT               NUMBER(1)            DEFAULT 0,
   TAKEBACK_ORIGIN      NUMBER(1)            DEFAULT 0,
   INCLUDE_COST         NUMBER(1)            DEFAULT 0,
   BS_TYPE		VARCHAR2(255),
   OLD_CONTENT          VARCHAR2(4000),
   CONSTRAINT BSPK_CONTRACT_CHARGER PRIMARY KEY (ID)
);
COMMENT ON TABLE BS_CONTRACT_CHARGER IS '责任人合同:如承包合同';
COMMENT ON COLUMN BS_CONTRACT_CHARGER.SIGN_TYPE IS '签约类型:如新户';
COMMENT ON COLUMN BS_CONTRACT_CHARGER.LOGOUT IS '注销:0-未,1-已';
COMMENT ON COLUMN BS_CONTRACT_CHARGER.TAKEBACK_ORIGIN IS '已经收回原件:0-未1-已';
COMMENT ON COLUMN BS_CONTRACT_CHARGER.INCLUDE_COST IS '包含检审费用:0-不包含,1-包含';
COMMENT ON COLUMN BS_CONTRACT_CHARGER.BS_TYPE IS '合同性质';
COMMENT ON COLUMN BS_CONTRACT_CHARGER.OLD_CONTENT IS '旧合同内容';
ALTER TABLE BS_CONTRACT_CHARGER ADD CONSTRAINT BSFK_CONTRACT4CHARGER_CONTRACT FOREIGN KEY (ID)
      REFERENCES BS_CONTRACT (ID);
      
-- 司机责任人与合同的关联
CREATE TABLE BS_CARMAN_CONTRACT (
   MAN_ID               NUMBER(19)           NOT NULL,
   CONTRACT_ID          NUMBER(19)           NOT NULL,
   CONSTRAINT BSPK_CARMAN_CONTRACT PRIMARY KEY (MAN_ID, CONTRACT_ID)
);
COMMENT ON TABLE BS_CARMAN_CONTRACT IS '司机责任人与合同的关联';
COMMENT ON COLUMN BS_CARMAN_CONTRACT.MAN_ID IS '司机责任人ID';
COMMENT ON COLUMN BS_CARMAN_CONTRACT.CONTRACT_ID IS '合同ID';
ALTER TABLE BS_CARMAN_CONTRACT ADD CONSTRAINT BSFK_CARMANCONTRACT_CONTRACT FOREIGN KEY (CONTRACT_ID)
      REFERENCES BS_CONTRACT (ID);
ALTER TABLE BS_CARMAN_CONTRACT ADD CONSTRAINT BSFK_CARMANCONTRACT_MAN FOREIGN KEY (MAN_ID)
      REFERENCES BS_CARMAN (ID);

-- 车辆与合同的关联
CREATE TABLE BS_CAR_CONTRACT (
   CAR_ID               NUMBER(19)           NOT NULL,
   CONTRACT_ID          NUMBER(19)           NOT NULL,
   CONSTRAINT BSPK_CAR_CONTRACT PRIMARY KEY (CAR_ID, CONTRACT_ID)
);
COMMENT ON TABLE BS_CAR_CONTRACT IS '车辆与合同的关联';
COMMENT ON COLUMN BS_CAR_CONTRACT.CAR_ID IS '车辆ID';
COMMENT ON COLUMN BS_CAR_CONTRACT.CONTRACT_ID IS '合同ID';
ALTER TABLE BS_CAR_CONTRACT ADD CONSTRAINT BSFK_CARCONTRACT_CAR FOREIGN KEY (CAR_ID)
      REFERENCES BS_CAR (ID);
ALTER TABLE BS_CAR_CONTRACT ADD CONSTRAINT BSFK_CARCONTRACT_CONTRACT FOREIGN KEY (CONTRACT_ID)
      REFERENCES BS_CONTRACT (ID);
            
-- 司机营运车辆
CREATE TABLE BS_CAR_DRIVER (
   ID                   NUMBER(19)           NOT NULL,
   STATUS_              NUMBER(1)            NOT NULL,
   DRIVER_ID            NUMBER(19)           NOT NULL,
   CAR_ID               NUMBER(19)           NOT NULL,
   CLASSES              NUMBER(1)         NOT NULL,
   FILE_DATE            DATE                 NOT NULL,
   AUTHOR_ID            NUMBER(19)           NOT NULL,
   MODIFIED_DATE        DATE,
   MODIFIER_ID          NUMBER(19),
   DESC_                VARCHAR2(4000),
  CONSTRAINT BSPK_CAR_DRIVER PRIMARY KEY (ID)
);
COMMENT ON TABLE BS_CAR_DRIVER IS '司机营运车辆';
COMMENT ON COLUMN BS_CAR_DRIVER.STATUS_ IS '状态：0-启用中,1-已禁用,2-已删除';
COMMENT ON COLUMN BS_CAR_DRIVER.DRIVER_ID IS '司机ID';
COMMENT ON COLUMN BS_CAR_DRIVER.CAR_ID IS '车辆ID';
COMMENT ON COLUMN BS_CAR_DRIVER.CLASSES IS '营运班次:如1-正班、2-副班、3-顶班';
COMMENT ON COLUMN BS_CAR_DRIVER.FILE_DATE IS '创建时间';
COMMENT ON COLUMN BS_CAR_DRIVER.AUTHOR_ID IS '创建人ID';
COMMENT ON COLUMN BS_CAR_DRIVER.MODIFIED_DATE IS '最后修改时间';
COMMENT ON COLUMN BS_CAR_DRIVER.MODIFIER_ID IS '最后修改人ID';
COMMENT ON COLUMN BS_CAR_DRIVER.DESC_ IS '备注';
ALTER TABLE BS_CAR_DRIVER ADD CONSTRAINT BSFK_CARDRIVER_AUTHOR FOREIGN KEY (AUTHOR_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
ALTER TABLE BS_CAR_DRIVER ADD CONSTRAINT BSFK_CARDRIVER_MODIFIER FOREIGN KEY (MODIFIER_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
ALTER TABLE BS_CAR_DRIVER ADD CONSTRAINT BSFK_CARDRIVER_CAR FOREIGN KEY (CAR_ID)
      REFERENCES BS_CAR (ID);
ALTER TABLE BS_CAR_DRIVER ADD CONSTRAINT BSFK_CARDRIVER_CARMAN FOREIGN KEY (DRIVER_ID)
      REFERENCES BS_CARMAN (ID);
      CREATE INDEX BSIDX_CARDRIVER_CAR ON BS_CAR_DRIVER (CAR_ID);
      CREATE INDEX BSIDX_CARDRIVER_DRIVER ON BS_CAR_DRIVER (DRIVER_ID);
      
 -- 迁移记录
CREATE TABLE BS_CAR_DRIVER_HISTORY (
   ID                   NUMBER(19)           NOT NULL,
   DRIVER_ID            NUMBER(19)  ,
   FROM_CAR_ID             NUMBER(19),
   FROM_MOTORCADE_ID       NUMBER(19),
   FROM_CLASSES       NUMBER(1),
   TO_CAR_ID             NUMBER(19),
   TO_MOTORCADE_ID       NUMBER(19),
   TO_CLASSES      NUMBER(1),
   MOVE_DATE              DATE,
   MOVE_TYPE            NUMBER(1)         NOT NULL,  
   FROM_UNIT              VARCHAR2(255),
   TO_UNIT                VARCHAR2(255),
   HAND_PAPERS_DATE      DATE,
   CANCEL_ID            VARCHAR2(255),
   FILE_DATE            DATE                 NOT NULL,
   AUTHOR_ID            NUMBER(19)           NOT NULL,
   MODIFIED_DATE        DATE,
   MODIFIER_ID          NUMBER(19),
   DESC_                VARCHAR2(4000),
  CONSTRAINT BSPK_CAR_DRIVER_HISTORY PRIMARY KEY (ID)
);
COMMENT ON TABLE BS_CAR_DRIVER_HISTORY IS '迁移记录';
COMMENT ON COLUMN BS_CAR_DRIVER_HISTORY.DRIVER_ID IS '司机ID';
COMMENT ON COLUMN BS_CAR_DRIVER_HISTORY.FROM_CAR_ID IS '原车辆ID';
COMMENT ON COLUMN BS_CAR_DRIVER_HISTORY.FROM_MOTORCADE_ID IS '原车队ID';
COMMENT ON COLUMN BS_CAR_DRIVER_HISTORY.FROM_CLASSES IS '营运班次:如1-正班、2-副班、3-顶班';
COMMENT ON COLUMN BS_CAR_DRIVER_HISTORY.TO_CAR_ID IS '新车辆ID';
COMMENT ON COLUMN BS_CAR_DRIVER_HISTORY.TO_MOTORCADE_ID IS '新车队ID';
COMMENT ON COLUMN BS_CAR_DRIVER_HISTORY.TO_CLASSES IS '营运班次:如1-正班、2-副班、3-顶班';
COMMENT ON COLUMN BS_CAR_DRIVER_HISTORY.MOVE_DATE IS '迁移日期';
COMMENT ON COLUMN BS_CAR_DRIVER_HISTORY.MOVE_TYPE IS '迁移类型';
COMMENT ON COLUMN BS_CAR_DRIVER_HISTORY.FROM_UNIT IS '原单位';
COMMENT ON COLUMN BS_CAR_DRIVER_HISTORY.TO_UNIT IS '现单位';
COMMENT ON COLUMN BS_CAR_DRIVER_HISTORY.HAND_PAPERS_DATE IS '交证日期';
COMMENT ON COLUMN BS_CAR_DRIVER_HISTORY.CANCEL_ID IS '注销单号';

COMMENT ON COLUMN BS_CAR_DRIVER_HISTORY.FILE_DATE IS '创建时间';
COMMENT ON COLUMN BS_CAR_DRIVER_HISTORY.AUTHOR_ID IS '创建人ID';
COMMENT ON COLUMN BS_CAR_DRIVER_HISTORY.MODIFIED_DATE IS '最后修改时间';
COMMENT ON COLUMN BS_CAR_DRIVER_HISTORY.MODIFIER_ID IS '最后修改人ID';
COMMENT ON COLUMN BS_CAR_DRIVER_HISTORY.DESC_ IS '备注';
ALTER TABLE BS_CAR_DRIVER_HISTORY ADD CONSTRAINT BSFK_CARDRIVERHISTORY_AUTHOR FOREIGN KEY (AUTHOR_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
ALTER TABLE BS_CAR_DRIVER_HISTORY ADD CONSTRAINT BSFK_CARDRIVERHISTORY_MODIFIER FOREIGN KEY (MODIFIER_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
ALTER TABLE BS_CAR_DRIVER_HISTORY ADD CONSTRAINT BSFK_CARDRIVER_OLD_CAR FOREIGN KEY (FROM_CAR_ID)
      REFERENCES BS_CAR (ID);
ALTER TABLE BS_CAR_DRIVER_HISTORY ADD CONSTRAINT BSFK_CARDRIVER_NEW_CAR FOREIGN KEY (TO_CAR_ID)
      REFERENCES BS_CAR (ID);
ALTER TABLE BS_CAR_DRIVER_HISTORY ADD CONSTRAINT BSFK_CASEBASE_OLD_MOTORCADE FOREIGN KEY (FROM_MOTORCADE_ID)
      REFERENCES BS_MOTORCADE (ID);
ALTER TABLE BS_CAR_DRIVER_HISTORY ADD CONSTRAINT BSFK_CASEBASE_NEW_MOTORCADE FOREIGN KEY (TO_MOTORCADE_ID)
      REFERENCES BS_MOTORCADE (ID);
ALTER TABLE BS_CAR_DRIVER_HISTORY ADD CONSTRAINT BSFK_CARDRIVERHISTORY_CARMAN FOREIGN KEY (DRIVER_ID)
      REFERENCES BS_CARMAN (ID);
      CREATE INDEX BSIDX_CARDRIVERHISTORY_TO_CAR ON BS_CAR_DRIVER_HISTORY (TO_CAR_ID);
      CREATE INDEX BSIDX_CARDRIVERHISTORY_FR_CAR ON BS_CAR_DRIVER_HISTORY (FROM_CAR_ID);
      CREATE INDEX BSIDX_CARDRIVERHISTORY_DRIVER ON BS_CAR_DRIVER_HISTORY (DRIVER_ID);
           
-- 司机迁移历史
CREATE TABLE BS_CARMAN_HISTORY (
   ID                   NUMBER(19)           NOT NULL,
   TYPE_                VARCHAR2(255)        NOT NULL,
   DRIVER_ID            NUMBER(19)           NOT NULL,
   SUBJECT              VARCHAR2(1000),
   FROM_CARID           NUMBER(19),
   TO_CARID             NUMBER(19)           NOT NULL,
   FROM_CLASSES         VARCHAR2(255),
   TO_CLASSES           VARCHAR2(255)        NOT NULL,
   SHIFT_DATE           DATE                 NOT NULL,
   FROM_MOTORCADEID     NUMBER(19),
   TO_MOTORCADEID       NUMBER(19)           NOT NULL,
   FILE_DATE            DATE                 NOT NULL,
   AUTHOR_ID            NUMBER(19)           NOT NULL,
   MODIFIED_DATE        DATE,
   MODIFIER_ID          NUMBER(19),
   CONSTRAINT BSPK_CARMAN_HISTORY PRIMARY KEY (ID)
);
COMMENT ON TABLE BS_CARMAN_HISTORY IS '司机迁移历史';
COMMENT ON COLUMN BS_CARMAN_HISTORY.TYPE_ IS '迁移属性，如新入职';
COMMENT ON COLUMN BS_CARMAN_HISTORY.DRIVER_ID IS '司机ID';
COMMENT ON COLUMN BS_CARMAN_HISTORY.SUBJECT IS '其他';
COMMENT ON COLUMN BS_CARMAN_HISTORY.FROM_CARID IS '迁自车辆ID';
COMMENT ON COLUMN BS_CARMAN_HISTORY.TO_CARID IS '迁往车辆ID';
COMMENT ON COLUMN BS_CARMAN_HISTORY.FROM_CLASSES IS '原营运班次:如正班、副班、顶班';
COMMENT ON COLUMN BS_CARMAN_HISTORY.TO_CLASSES IS '新营运班次:如正班、副班、顶班';
COMMENT ON COLUMN BS_CARMAN_HISTORY.SHIFT_DATE IS '迁移日期';
COMMENT ON COLUMN BS_CARMAN_HISTORY.FROM_MOTORCADEID IS '原车队ID';
COMMENT ON COLUMN BS_CARMAN_HISTORY.TO_MOTORCADEID IS '迁往车队ID';
COMMENT ON COLUMN BS_CARMAN_HISTORY.FILE_DATE IS '创建时间';
COMMENT ON COLUMN BS_CARMAN_HISTORY.AUTHOR_ID IS '创建人ID';
COMMENT ON COLUMN BS_CARMAN_HISTORY.MODIFIED_DATE IS '最后修改时间';
COMMENT ON COLUMN BS_CARMAN_HISTORY.MODIFIER_ID IS '最后修改人ID';
ALTER TABLE BS_CARMAN_HISTORY ADD CONSTRAINT BSFK_CARMANH_DRIVER FOREIGN KEY (DRIVER_ID)
      REFERENCES BS_CARMAN (ID);
ALTER TABLE BS_CARMAN_HISTORY ADD CONSTRAINT BSFK_CARMANH_FROMCAR FOREIGN KEY (FROM_CARID)
      REFERENCES BS_CAR (ID);
ALTER TABLE BS_CARMAN_HISTORY ADD CONSTRAINT BSFK_CARMANH_TOCAR FOREIGN KEY (TO_CARID)
      REFERENCES BS_CAR (ID);
ALTER TABLE BS_CARMAN_HISTORY ADD CONSTRAINT BSFK_CARMANH_FROMMC FOREIGN KEY (FROM_MOTORCADEID)
      REFERENCES BS_MOTORCADE (ID);
ALTER TABLE BS_CARMAN_HISTORY ADD CONSTRAINT BSFK_CARMANH_TOMC FOREIGN KEY (TO_MOTORCADEID)
      REFERENCES BS_MOTORCADE (ID);
ALTER TABLE BS_CARMAN_HISTORY ADD CONSTRAINT BSFK_CARMANH_AUTHOR FOREIGN KEY (AUTHOR_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID); 
ALTER TABLE BS_CARMAN_HISTORY ADD CONSTRAINT BSFK_CARMANH_MODIFIER FOREIGN KEY (MODIFIER_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);

-- 黑名单
CREATE TABLE BS_BLACKLIST (
   ID                   NUMBER(19)           NOT NULL,
   STATUS_              NUMBER(1),
   TYPE_                VARCHAR2(255)        NOT NULL,
   OLD_UNIT_NAME        VARCHAR2(255),
   DRIVER_ID            NUMBER(19),
   CAR_ID               NUMBER(19),
   MOTORCADE_ID         NUMBER(19),
   SUBJECT              VARCHAR2(1000),
   LOCK_DATE            DATE                 NOT NULL,
   UNLOCK_DATE          DATE,
   LOCKER_ID            NUMBER(19)           NOT NULL,
   UNLOCKER_ID          NUMBER(19),
   LOCK_REASON          VARCHAR2(4000),
   UNLOCK_REASON        VARCHAR2(4000),
   LEVEL_               VARCHAR2(255),
   CODE                 VARCHAR2(255),
   FILE_DATE            DATE                 NOT NULL,
   AUTHOR_ID            NUMBER(19)           NOT NULL,
   MODIFIED_DATE        DATE,
   MODIFIER_ID          NUMBER(19),
   CONSTRAINT BSPK_BLACKLIST PRIMARY KEY (ID)
);
COMMENT ON TABLE BS_BLACKLIST IS '黑名单';
COMMENT ON COLUMN BS_BLACKLIST.STATUS_ IS '状态：0-锁定,1-解锁';
COMMENT ON COLUMN BS_BLACKLIST.TYPE_ IS '限制项目';
COMMENT ON COLUMN BS_BLACKLIST.OLD_UNIT_NAME IS '车属单位';
COMMENT ON COLUMN BS_BLACKLIST.DRIVER_ID IS '司机ID';
COMMENT ON COLUMN BS_BLACKLIST.CAR_ID IS '车辆ID';
COMMENT ON COLUMN BS_BLACKLIST.MOTORCADE_ID IS '车队ID';
COMMENT ON COLUMN BS_BLACKLIST.SUBJECT IS '主题';
COMMENT ON COLUMN BS_BLACKLIST.LOCK_DATE IS '锁定时间';
COMMENT ON COLUMN BS_BLACKLIST.UNLOCK_DATE IS '解锁时间';
COMMENT ON COLUMN BS_BLACKLIST.LOCKER_ID IS '锁定人ID';
COMMENT ON COLUMN BS_BLACKLIST.UNLOCKER_ID IS '解锁人ID';
COMMENT ON COLUMN BS_BLACKLIST.LOCK_REASON IS '锁定原因';
COMMENT ON COLUMN BS_BLACKLIST.UNLOCK_REASON IS '解锁原因';
COMMENT ON COLUMN BS_BLACKLIST.LEVEL_ IS '等级';
COMMENT ON COLUMN BS_BLACKLIST.CODE IS '编号';
COMMENT ON COLUMN BS_BLACKLIST.FILE_DATE IS '创建时间';
COMMENT ON COLUMN BS_BLACKLIST.AUTHOR_ID IS '创建人ID';
COMMENT ON COLUMN BS_BLACKLIST.MODIFIED_DATE IS '最后修改时间';
COMMENT ON COLUMN BS_BLACKLIST.MODIFIER_ID IS '最后修改人ID';
ALTER TABLE BS_BLACKLIST ADD CONSTRAINT BSFK_BLACKLIST_AUTHOR FOREIGN KEY (AUTHOR_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
ALTER TABLE BS_BLACKLIST ADD CONSTRAINT BSFK_BLACKLIST_MODIFIER FOREIGN KEY (MODIFIER_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
ALTER TABLE BS_BLACKLIST ADD CONSTRAINT BSFK_BLACKLIST_MOTORCADE FOREIGN KEY (MOTORCADE_ID)
      REFERENCES BS_MOTORCADE (ID);
ALTER TABLE BS_BLACKLIST ADD CONSTRAINT BSFK_BLACKLIST_CAR FOREIGN KEY (CAR_ID)
      REFERENCES BS_CAR (ID);
ALTER TABLE BS_BLACKLIST ADD CONSTRAINT BSFK_BLACKLIST_DIRVER FOREIGN KEY (DRIVER_ID)
      REFERENCES BS_CARMAN (ID);
ALTER TABLE BS_BLACKLIST ADD CONSTRAINT BSFK_BLACKLIST_LOCKER FOREIGN KEY (LOCKER_ID)
      REFERENCES BC_IDENTITY_ACTOR (ID);
ALTER TABLE BS_BLACKLIST ADD CONSTRAINT BSFK_BLACKLIST_UNLOCKER FOREIGN KEY (UNLOCKER_ID)
      REFERENCES BC_IDENTITY_ACTOR (ID);
      CREATE INDEX BSIDX_BLACKLIST_DRIVER ON BS_BLACKLIST (DRIVER_ID);
      CREATE INDEX BSIDX_BLACKLIST_CAR ON BS_BLACKLIST (CAR_ID);

-- 营运事件基表
CREATE TABLE BS_CASE_BASE (
   ID                   NUMBER(19)           NOT NULL,
   UID_                 VARCHAR2(36)         NOT NULL,
   CASE_NO              VARCHAR2(255),
   CODE                 VARCHAR2(255),
   TYPE_                NUMBER(1)            NOT NULL,
   STATUS_              NUMBER(1)            NOT NULL,
   SOURCE               NUMBER(1)            NOT NULL,
   SUBJECT              VARCHAR2(1000),
   ADDRESS              VARCHAR2(1000),
   FROM_                VARCHAR2(255),
   HAPPEN_DATE          DATE                 NOT NULL,
   MOTORCADE_ID         NUMBER(19),
   MOTORCADE_NAME       VARCHAR2(255),
   CAR_ID               NUMBER(19),
   CAR_PLATE            VARCHAR2(255),
   DRIVER_ID            NUMBER(19),
   DRIVER_NAME          VARCHAR2(255),
   DRIVER_CERT          VARCHAR2(255),
   CLOSE_DATE           DATE,
   CLOSER_ID            NUMBER(19),
   CLOSER_NAME          VARCHAR2(255),
   DESC_                VARCHAR2(4000),
   FILE_DATE            DATE                 NOT NULL,
   AUTHOR_ID            NUMBER(19)           NOT NULL,
   MODIFIER_ID          NUMBER(19),
   MODIFIED_DATE        DATE,
   SYNC_UID             VARCHAR2(36),
   SYNC_ID              NUMBER(19),
   CONSTRAINT BSPK_CASEBASE PRIMARY KEY (ID)
);
COMMENT ON TABLE BS_CASE_BASE IS '营运事件：表扬、投诉、营运违章、交通违法、事故等的基表';
COMMENT ON COLUMN BS_CASE_BASE.CASE_NO IS '案号：营运违章的案号，交通违章的违章顺序号等';
COMMENT ON COLUMN BS_CASE_BASE.CODE IS '自编号';
COMMENT ON COLUMN BS_CASE_BASE.TYPE_ IS '内部类型：1-表扬、2-投诉、3-营运违章、4-交通违章、5-事故';
COMMENT ON COLUMN BS_CASE_BASE.STATUS_ IS '状态：0-在案,1-已结案';
COMMENT ON COLUMN BS_CASE_BASE.SOURCE IS '来源：1-用户创建(手输)、2-接口导入、3-司机递交等';
COMMENT ON COLUMN BS_CASE_BASE.SUBJECT IS '标题';
COMMENT ON COLUMN BS_CASE_BASE.ADDRESS IS '事发地点';
COMMENT ON COLUMN BS_CASE_BASE.HAPPEN_DATE IS '事发时间';
COMMENT ON COLUMN BS_CASE_BASE.FROM_ IS '信息来源(用户填写)';
COMMENT ON COLUMN BS_CASE_BASE.MOTORCADE_ID IS '车队ID';
COMMENT ON COLUMN BS_CASE_BASE.MOTORCADE_NAME IS '车队名称';
COMMENT ON COLUMN BS_CASE_BASE.CAR_ID IS '车辆ID';
COMMENT ON COLUMN BS_CASE_BASE.CAR_PLATE IS '车辆号码';
COMMENT ON COLUMN BS_CASE_BASE.DRIVER_ID IS '司机ID';
COMMENT ON COLUMN BS_CASE_BASE.DRIVER_NAME IS '司机姓名';
COMMENT ON COLUMN BS_CASE_BASE.DRIVER_CERT IS '服务资格证';
COMMENT ON COLUMN BS_CASE_BASE.CLOSE_DATE IS '结案日期';
COMMENT ON COLUMN BS_CASE_BASE.CLOSER_ID IS '结案人ID';
COMMENT ON COLUMN BS_CASE_BASE.CLOSER_NAME IS '结案人姓名';
COMMENT ON COLUMN BS_CASE_BASE.DESC_ IS '备注';
COMMENT ON COLUMN BS_CASE_BASE.FILE_DATE IS '创建时间';
COMMENT ON COLUMN BS_CASE_BASE.AUTHOR_ID IS '创建人ID';
COMMENT ON COLUMN BS_CASE_BASE.MODIFIER_ID IS '最后修改人ID';
COMMENT ON COLUMN BS_CASE_BASE.MODIFIED_DATE IS '最后修改时间';
COMMENT ON COLUMN BS_CASE_BASE.SYNC_UID IS '旧数据同步的UID';
COMMENT ON COLUMN BS_CASE_BASE.SYNC_ID IS '数据同步ID';
ALTER TABLE BS_CASE_BASE ADD CONSTRAINT BSFK_CASEBASE_AUTHOR FOREIGN KEY (AUTHOR_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
ALTER TABLE BS_CASE_BASE ADD CONSTRAINT BSFK_CASEBASE_MODIFIER FOREIGN KEY (MODIFIER_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
ALTER TABLE BS_CASE_BASE ADD CONSTRAINT BSFK_CASEBASE_MOTORCADE FOREIGN KEY (MOTORCADE_ID)
      REFERENCES BS_MOTORCADE (ID);
ALTER TABLE BS_CASE_BASE ADD CONSTRAINT BSFK_CASEBASE_CAR FOREIGN KEY (CAR_ID)
      REFERENCES BS_CAR (ID);
ALTER TABLE BS_CASE_BASE ADD CONSTRAINT BSFK_CASEBASE_DRIVER FOREIGN KEY (DRIVER_ID)
      REFERENCES BS_CARMAN (ID);
ALTER TABLE BS_CASE_BASE ADD CONSTRAINT BSFK_CASEBASE_CLOSER FOREIGN KEY (CLOSER_ID)
      REFERENCES BC_IDENTITY_ACTOR (ID);
ALTER TABLE BS_CASE_BASE ADD CONSTRAINT BSFK_CASEBASE_SYNC FOREIGN KEY (SYNC_ID)
      REFERENCES BC_SYNC_BASE (ID);
CREATE INDEX BSIDX_CASE_BASE_DRIVER ON BS_CASE_BASE (DRIVER_ID);
CREATE INDEX BSIDX_CASE_BASE_CAR ON BS_CASE_BASE (CAR_ID);
            
-- 营运违章
CREATE TABLE BS_CASE_INFRACT_BUSINESS (
   ID                   NUMBER(19)           NOT NULL,
   RECEIVE_DATE         DATE,
   RECEIVER_ID          NUMBER(19),
   RECEIVER_NAME        VARCHAR2(255),
   CHARGER1_ID          NUMBER(19),
   CHARGER1_NAME        VARCHAR2(255),
   CHARGER2_ID          NUMBER(19),
   CHARGER2_NAME        VARCHAR2(255),
   DUTY                 VARCHAR2(255),
   SORT                 VARCHAR2(255),
   EXTENT               VARCHAR2(255),
   CERT_KJ_TYPE         VARCHAR2(255),
   CERT_KJ              VARCHAR2(255),
   CERT_YY              VARCHAR2(255),
   DETAIN               VARCHAR2(255),
   JEOM                 NUMBER(3,1)	    DEFAULT 0,
   PENALTY              NUMBER(10,2)	    DEFAULT 0,
   PENALTY2             NUMBER(10,2)	    DEFAULT 0,
   AREA                 VARCHAR2(255),
   PULL_UNIT            VARCHAR2(255),
   OPERATOR             VARCHAR2(255),
   OPERATE_UNIT         VARCHAR2(255),
   RECEIPT              VARCHAR2(255),
   COMMENT_             VARCHAR2(4000),
   IS_INVALID           NUMBER(1)            NOT NULL,
   IS_SEAL              NUMBER(1)            NOT NULL,
   SEAL_DATE            DATE,
   IS_DELIVER           NUMBER(1)            NOT NULL,
   IS_CLOSE             NUMBER(1)            NOT NULL,
   IS_OVERDUE           NUMBER(1)            NOT NULL,
   IS_STOP              NUMBER(1),
   CONSTRAINT BSPK_CASE_INFRACT_BUSINESS PRIMARY KEY (ID)
);
COMMENT ON TABLE BS_CASE_INFRACT_BUSINESS IS '营运违章';
COMMENT ON COLUMN BS_CASE_INFRACT_BUSINESS.RECEIVE_DATE IS '接案日期';
COMMENT ON COLUMN BS_CASE_INFRACT_BUSINESS.RECEIVER_ID IS '接案人ID';
COMMENT ON COLUMN BS_CASE_INFRACT_BUSINESS.RECEIVER_NAME IS '接案人姓名';
COMMENT ON COLUMN BS_CASE_INFRACT_BUSINESS.CHARGER1_ID IS '责任人1ID';
COMMENT ON COLUMN BS_CASE_INFRACT_BUSINESS.CHARGER1_NAME IS '责任人1姓名';
COMMENT ON COLUMN BS_CASE_INFRACT_BUSINESS.CHARGER2_ID IS '责任人2ID';
COMMENT ON COLUMN BS_CASE_INFRACT_BUSINESS.CHARGER2_NAME IS '责任人2姓名';
COMMENT ON COLUMN BS_CASE_INFRACT_BUSINESS.DUTY IS '责任';
COMMENT ON COLUMN BS_CASE_INFRACT_BUSINESS.SORT IS '性质';
COMMENT ON COLUMN BS_CASE_INFRACT_BUSINESS.EXTENT IS '程度';
COMMENT ON COLUMN BS_CASE_INFRACT_BUSINESS.CERT_KJ_TYPE IS '没收证件类型';
COMMENT ON COLUMN BS_CASE_INFRACT_BUSINESS.CERT_KJ IS '扣件证号';
COMMENT ON COLUMN BS_CASE_INFRACT_BUSINESS.CERT_YY IS '营运证号';
COMMENT ON COLUMN BS_CASE_INFRACT_BUSINESS.DETAIN IS '扣留物品';
COMMENT ON COLUMN BS_CASE_INFRACT_BUSINESS.JEOM IS '扣分';
COMMENT ON COLUMN BS_CASE_INFRACT_BUSINESS.PENALTY IS '罚款';
COMMENT ON COLUMN BS_CASE_INFRACT_BUSINESS.PENALTY2 IS '违约金';
COMMENT ON COLUMN BS_CASE_INFRACT_BUSINESS.AREA IS '所属区县';
COMMENT ON COLUMN BS_CASE_INFRACT_BUSINESS.PULL_UNIT IS '拖车单位';
COMMENT ON COLUMN BS_CASE_INFRACT_BUSINESS.OPERATOR IS '执法人';
COMMENT ON COLUMN BS_CASE_INFRACT_BUSINESS.OPERATE_UNIT IS '执法机关';
COMMENT ON COLUMN BS_CASE_INFRACT_BUSINESS.RECEIPT IS '罚没收据编号';
COMMENT ON COLUMN BS_CASE_INFRACT_BUSINESS.COMMENT_ IS '处理意见';
COMMENT ON COLUMN BS_CASE_INFRACT_BUSINESS.IS_INVALID IS '是否无效：1-无效';
COMMENT ON COLUMN BS_CASE_INFRACT_BUSINESS.IS_SEAL IS '是否盖章：1-盖';
COMMENT ON COLUMN BS_CASE_INFRACT_BUSINESS.SEAL_DATE IS '盖章日期';
COMMENT ON COLUMN BS_CASE_INFRACT_BUSINESS.IS_DELIVER IS '是否交结案单：1-已交';
COMMENT ON COLUMN BS_CASE_INFRACT_BUSINESS.IS_CLOSE IS '是否结案：1-结案';
COMMENT ON COLUMN BS_CASE_INFRACT_BUSINESS.IS_OVERDUE IS '是否过期：1-过期';
COMMENT ON COLUMN BS_CASE_INFRACT_BUSINESS.IS_STOP IS '是否停场：1-停';
ALTER TABLE BS_CASE_INFRACT_BUSINESS ADD CONSTRAINT BSFK_INFRACTB_CASEBASE FOREIGN KEY (ID)
      REFERENCES BS_CASE_BASE (ID);
ALTER TABLE BS_CASE_INFRACT_BUSINESS ADD CONSTRAINT BSFK_INFRACTB_RECEIVER FOREIGN KEY (RECEIVER_ID)
      REFERENCES BC_IDENTITY_ACTOR (ID);
ALTER TABLE BS_CASE_INFRACT_BUSINESS ADD CONSTRAINT BSFK_INFRACTB_CHARGER1 FOREIGN KEY (CHARGER1_ID)
      REFERENCES BS_CARMAN (ID);
ALTER TABLE BS_CASE_INFRACT_BUSINESS ADD CONSTRAINT BSFK_INFRACTB_CHARGER2 FOREIGN KEY (CHARGER2_ID)
      REFERENCES BS_CARMAN (ID);

-- 交通违章
CREATE TABLE BS_CASE_INFRACT_TRAFFIC (
   ID                   NUMBER(19)           NOT NULL,
   CHARGER1_ID          NUMBER(19),
   CHARGER1_NAME        VARCHAR2(255),
   CHARGER2_ID          NUMBER(19),
   CHARGER2_NAME        VARCHAR2(255),
   DUTY                 VARCHAR2(255),
   SORT                 VARCHAR2(255),
   JEOM                 NUMBER(3,1)	     DEFAULT 0,
   COMMENT_             VARCHAR2(4000),
   IS_DELIVER           NUMBER(1)            NOT NULL,
   DELIVER_DATE         DATE,
   IS_SIGN              number(1)            not null,
   SIGN_DATE            DATE,
   CONSTRAINT BSPK_CASE_INFRACT_TRAFFIC PRIMARY KEY (ID)
);
COMMENT ON TABLE BS_CASE_INFRACT_TRAFFIC IS '交通违章';
COMMENT ON COLUMN BS_CASE_INFRACT_TRAFFIC.CHARGER1_ID IS '责任人1ID';
COMMENT ON COLUMN BS_CASE_INFRACT_TRAFFIC.CHARGER1_NAME IS '责任人1姓名';
COMMENT ON COLUMN BS_CASE_INFRACT_TRAFFIC.CHARGER2_ID IS '责任人2ID';
COMMENT ON COLUMN BS_CASE_INFRACT_TRAFFIC.CHARGER2_NAME IS '责任人2姓名';
COMMENT ON COLUMN BS_CASE_INFRACT_TRAFFIC.DUTY IS '责任';
COMMENT ON COLUMN BS_CASE_INFRACT_TRAFFIC.SORT IS '性质';
COMMENT ON COLUMN BS_CASE_INFRACT_TRAFFIC.JEOM IS '扣分';
COMMENT ON COLUMN BS_CASE_INFRACT_TRAFFIC.COMMENT_ IS '处理意见';
COMMENT ON COLUMN BS_CASE_INFRACT_TRAFFIC.IS_DELIVER IS '是否邮递：1-是';
COMMENT ON COLUMN BS_CASE_INFRACT_TRAFFIC.DELIVER_DATE IS '邮递时间';
COMMENT ON COLUMN BS_CASE_INFRACT_TRAFFIC.IS_SIGN IS '是否签领：1-是';
COMMENT ON COLUMN BS_CASE_INFRACT_TRAFFIC.SIGN_DATE IS '签领时间';
ALTER TABLE BS_CASE_INFRACT_TRAFFIC ADD CONSTRAINT BSFK_INFRACTT_CASEBASE FOREIGN KEY (ID)
      REFERENCES BS_CASE_BASE (ID);
ALTER TABLE BS_CASE_INFRACT_TRAFFIC ADD CONSTRAINT BSFK_INFRACTT_CHARGER1 FOREIGN KEY (CHARGER1_ID)
      REFERENCES BS_CARMAN (ID);
ALTER TABLE BS_CASE_INFRACT_TRAFFIC ADD CONSTRAINT BSFK_INFRACTT_CHARGER2 FOREIGN KEY (CHARGER2_ID)
      REFERENCES BS_CARMAN (ID);
      
-- 事故理赔
CREATE TABLE BS_CASE_ACCIDENT (
   ID                   NUMBER(19)           NOT NULL,
   RECEIVE_DATE         DATE,
   RECEIVER_ID          NUMBER(19),
   RECEIVER_NAME        VARCHAR2(255),
   RECEIVE_CODE         VARCHAR2(255),
   DEPARTMENT           VARCHAR2(255),
   CHARGER_ID           NUMBER(19),
   CHARGER_NAME         VARCHAR2(255),
   DUTY                 VARCHAR2(255),
   SORT                 VARCHAR2(255),
   WEATHER              VARCHAR2(255),
   DRIVER_AREA          NUMBER(1),
   DRIVER_TYPE          NUMBER(1),
   DRIVER_CLASSES       NUMBER(1),
   INSURANCE_COMPANY    VARCHAR2(255),
   INSURANCE_INFO       VARCHAR2(4000),
   IS_DELIVER           NUMBER(1)            NOT NULL,
   DELIVER_DATE         DATE,
   DELIVER_MONEY        NUMBER(10,2),
   IS_PAY               NUMBER(1)            NOT NULL,
   PAY_DATE             DATE,
   PAY_MONEY            NUMBER(10,2),
   PAY_CODE             VARCHAR2(255),
   IS_CLAIM             NUMBER(1)            NOT NULL,
   CLAIM_DATE           DATE,
   CLAIM_MONEY          NUMBER(10,2),
   CLAIM_CODE           VARCHAR2(255),
   CLAIM_NO1           VARCHAR2(255),
   CLAIM_NO2           VARCHAR2(255),
   CASUALTIES           VARCHAR2(255),
   CAR_HURT             VARCHAR2(255),
   THIRD_PARTY          VARCHAR2(255),
   IS_ROB               NUMBER(1),
   HURT_COUNT           NUMBER(10),
   DEAD_COUNT           NUMBER(10),
   ACTUAL_LOSS          NUMBER(10,2),
   IS_INNER_FIX         NUMBER(1),
   FIX_COST             NUMBER(10,2),
   COST_DETAIL          VARCHAR2(4000),
   CONSTRAINT BSPK_CASE_ACCIDENT PRIMARY KEY (ID)
);
COMMENT ON TABLE BS_CASE_ACCIDENT IS '事故理赔';
COMMENT ON COLUMN BS_CASE_ACCIDENT.RECEIVE_DATE IS '受理时间';
COMMENT ON COLUMN BS_CASE_ACCIDENT.RECEIVER_ID IS '经办人ID';
COMMENT ON COLUMN BS_CASE_ACCIDENT.RECEIVER_NAME IS '经办人姓名';
COMMENT ON COLUMN BS_CASE_ACCIDENT.RECEIVE_CODE IS '受理编号';
COMMENT ON COLUMN BS_CASE_ACCIDENT.DEPARTMENT IS '处理部门';
COMMENT ON COLUMN BS_CASE_ACCIDENT.CHARGER_ID IS '负责人ID';
COMMENT ON COLUMN BS_CASE_ACCIDENT.CHARGER_NAME IS '负责人姓名';
COMMENT ON COLUMN BS_CASE_ACCIDENT.DUTY IS '责任';
COMMENT ON COLUMN BS_CASE_ACCIDENT.SORT IS '性质';
COMMENT ON COLUMN BS_CASE_ACCIDENT.WEATHER IS '天气';
COMMENT ON COLUMN BS_CASE_ACCIDENT.DRIVER_AREA IS '司机区域:0-未定义，1-本市，2-本省，3-外省';
COMMENT ON COLUMN BS_CASE_ACCIDENT.DRIVER_TYPE IS '司机类型：0:未定义,1:车主 ,2:司机,3:非编';
COMMENT ON COLUMN BS_CASE_ACCIDENT.DRIVER_CLASSES IS '驾驶状态：如正班等';
COMMENT ON COLUMN BS_CASE_ACCIDENT.INSURANCE_COMPANY IS '保险公司';
COMMENT ON COLUMN BS_CASE_ACCIDENT.INSURANCE_INFO IS '相关保单';
COMMENT ON COLUMN BS_CASE_ACCIDENT.IS_DELIVER IS '是否送保：1-是';
COMMENT ON COLUMN BS_CASE_ACCIDENT.DELIVER_DATE IS '送保日期';
COMMENT ON COLUMN BS_CASE_ACCIDENT.DELIVER_MONEY IS '送保金额';
COMMENT ON COLUMN BS_CASE_ACCIDENT.IS_PAY IS '是否司机受款：1-是';
COMMENT ON COLUMN BS_CASE_ACCIDENT.PAY_DATE IS '司机受款日期';
COMMENT ON COLUMN BS_CASE_ACCIDENT.PAY_MONEY IS '司机受款金额';
COMMENT ON COLUMN BS_CASE_ACCIDENT.PAY_CODE IS '司机受款收据号';
COMMENT ON COLUMN BS_CASE_ACCIDENT.IS_CLAIM IS '是否保险公司赔付：1-是';
COMMENT ON COLUMN BS_CASE_ACCIDENT.CLAIM_DATE IS '保险公司赔付日期';
COMMENT ON COLUMN BS_CASE_ACCIDENT.CLAIM_MONEY IS '保险公司赔付金额';
COMMENT ON COLUMN BS_CASE_ACCIDENT.CLAIM_CODE IS '保险公司赔付收据号';
COMMENT ON COLUMN BS_CASE_ACCIDENT.CLAIM_NO1 IS '商业险赔付号';
COMMENT ON COLUMN BS_CASE_ACCIDENT.CLAIM_NO2 IS '交强险赔付号';
COMMENT ON COLUMN BS_CASE_ACCIDENT.CASUALTIES IS '伤亡情况';
COMMENT ON COLUMN BS_CASE_ACCIDENT.CAR_HURT IS '车损情况';
COMMENT ON COLUMN BS_CASE_ACCIDENT.THIRD_PARTY IS '第三者情况';
COMMENT ON COLUMN BS_CASE_ACCIDENT.IS_ROB IS '是否抢劫：1-是';
COMMENT ON COLUMN BS_CASE_ACCIDENT.HURT_COUNT IS '受伤人数';
COMMENT ON COLUMN BS_CASE_ACCIDENT.DEAD_COUNT IS '死亡人数';
COMMENT ON COLUMN BS_CASE_ACCIDENT.ACTUAL_LOSS IS '实际损失';
COMMENT ON COLUMN BS_CASE_ACCIDENT.IS_INNER_FIX IS '是否修理厂内修：1-是';
COMMENT ON COLUMN BS_CASE_ACCIDENT.FIX_COST IS '修理厂内修金额';
COMMENT ON COLUMN BS_CASE_ACCIDENT.COST_DETAIL IS '损失明细';
ALTER TABLE BS_CASE_ACCIDENT ADD CONSTRAINT BSFK_ACCIDENT_CASEBASE FOREIGN KEY (ID)
      REFERENCES BS_CASE_BASE (ID);
ALTER TABLE BS_CASE_ACCIDENT ADD CONSTRAINT BSFK_ACCIDENT_CHARGER FOREIGN KEY (CHARGER_ID)
      REFERENCES BC_IDENTITY_ACTOR (ID);
ALTER TABLE BS_CASE_ACCIDENT ADD CONSTRAINT BSFK_ACCIDENT_RECEIVER FOREIGN KEY (RECEIVER_ID)
      REFERENCES BC_IDENTITY_ACTOR (ID);
      

-- 投诉与建议
CREATE TABLE BS_CASE_ADVICE (
   ID                   NUMBER(19)           NOT NULL,
   ADVICE_TYPE          NUMBER(1)            NOT NULL,
   RECEIVE_DATE         DATE                 NOT NULL,
   RECEIVE_CODE         VARCHAR2(255),
   RECEIVER_ID          NUMBER(19),
   RECEIVER_NAME        VARCHAR2(255),
   SUBJECT2             VARCHAR2(255),
   DETAIL               VARCHAR2(4000),
   CAR_COLOR            VARCHAR2(255),
   DRIVER_SEX           NUMBER(1),
   DRIVER_FEATURE       VARCHAR2(255),
   ADVISOR_NAME         VARCHAR2(255),
   ADVISOR_SEX          NUMBER(1)            NOT NULL,
   ADVISOR_AGE          NUMBER(3),
   ADVISOR_PHONE        VARCHAR2(255),
   ADVISOR_CERT         VARCHAR2(255),
   DUTY                 VARCHAR2(255),
   EXTENT               VARCHAR2(255),
   NOTICE_DATE          DATE,
   RESULT_              VARCHAR2(4000),
   TICKET               VARCHAR2(255),
   MACHINE_PRICE        NUMBER(10)	    DEFAULT 0,
   CHARGE               NUMBER(10)	    DEFAULT 0,
   RIDING_TIME_START    DATE,
   RIDING_TIME_END      DATE,
   PATH_FROM            VARCHAR2(255),
   PATH_TO              VARCHAR2(255),
   PATH                 VARCHAR2(255),
   PASSENGER_COUNT_MAN  NUMBER(1),
   PASSENGER_COUNT_WOMAN NUMBER(1),
   PASSENGER_COUNT_CHILD NUMBER(1),
   PASSENGER_COUNT      NUMBER(1),
   DELIVER_DATE         DATE,
   IS_INVALID           NUMBER(1)            NOT NULL,
   CONSTRAINT BSPK_CASE_ADVICE PRIMARY KEY (ID)
);
COMMENT ON TABLE BS_CASE_ADVICE IS '投诉与建议';
COMMENT ON COLUMN BS_CASE_ADVICE.ADVICE_TYPE IS '标识是投诉还是建议:0-投诉,1-建议';
COMMENT ON COLUMN BS_CASE_ADVICE.RECEIVE_DATE IS '接诉时间';
COMMENT ON COLUMN BS_CASE_ADVICE.RECEIVE_CODE IS '受理号';
COMMENT ON COLUMN BS_CASE_ADVICE.RECEIVER_ID IS '经办人ID';
COMMENT ON COLUMN BS_CASE_ADVICE.RECEIVER_NAME IS '经办人姓名';
COMMENT ON COLUMN BS_CASE_ADVICE.SUBJECT2 IS '投诉项目小类';
COMMENT ON COLUMN BS_CASE_ADVICE.DETAIL IS '投诉内容';
COMMENT ON COLUMN BS_CASE_ADVICE.CAR_COLOR IS '车色';
COMMENT ON COLUMN BS_CASE_ADVICE.DRIVER_SEX IS '司机性别:0-未设,1-男,2-女';
COMMENT ON COLUMN BS_CASE_ADVICE.DRIVER_FEATURE IS '司机特征';
COMMENT ON COLUMN BS_CASE_ADVICE.ADVISOR_NAME IS '投诉人姓名';
COMMENT ON COLUMN BS_CASE_ADVICE.ADVISOR_SEX IS '投诉人性别';
COMMENT ON COLUMN BS_CASE_ADVICE.ADVISOR_AGE IS '投诉人年龄';
COMMENT ON COLUMN BS_CASE_ADVICE.ADVISOR_PHONE IS '投诉人电话';
COMMENT ON COLUMN BS_CASE_ADVICE.ADVISOR_CERT IS '投诉人证件号';
COMMENT ON COLUMN BS_CASE_ADVICE.DUTY IS '责任';
COMMENT ON COLUMN BS_CASE_ADVICE.EXTENT IS '程度';
COMMENT ON COLUMN BS_CASE_ADVICE.NOTICE_DATE IS '通知时间';
COMMENT ON COLUMN BS_CASE_ADVICE.RESULT_ IS '处理结果';
COMMENT ON COLUMN BS_CASE_ADVICE.TICKET IS '车票号码';
COMMENT ON COLUMN BS_CASE_ADVICE.MACHINE_PRICE IS '计费器显示价格';
COMMENT ON COLUMN BS_CASE_ADVICE.CHARGE IS '实际收费';
COMMENT ON COLUMN BS_CASE_ADVICE.RIDING_TIME_START IS '乘车起始时间';
COMMENT ON COLUMN BS_CASE_ADVICE.RIDING_TIME_END IS '乘车结束时间';
COMMENT ON COLUMN BS_CASE_ADVICE.PATH_FROM IS '乘车路线(从)';
COMMENT ON COLUMN BS_CASE_ADVICE.PATH_TO IS '乘车路线(到)';
COMMENT ON COLUMN BS_CASE_ADVICE.PATH IS '乘车路线';
COMMENT ON COLUMN BS_CASE_ADVICE.PASSENGER_COUNT_MAN IS '乘车人数(男)';
COMMENT ON COLUMN BS_CASE_ADVICE.PASSENGER_COUNT_WOMAN IS '乘车人数(女)';
COMMENT ON COLUMN BS_CASE_ADVICE.PASSENGER_COUNT_CHILD IS '乘车人数(童)';
COMMENT ON COLUMN BS_CASE_ADVICE.PASSENGER_COUNT IS '乘车人数';
COMMENT ON COLUMN BS_CASE_ADVICE.DELIVER_DATE IS '结案书交回日期';
COMMENT ON COLUMN BS_CASE_ADVICE.IS_INVALID IS '是否无效：1-无效';
ALTER TABLE BS_CASE_ADVICE ADD CONSTRAINT BSFK_ADVICE_CASEBASE FOREIGN KEY (ID)
      REFERENCES BS_CASE_BASE (ID);
ALTER TABLE BS_CASE_ADVICE ADD CONSTRAINT BSFK_ADVICE_RECEIVER FOREIGN KEY (RECEIVER_ID)
      REFERENCES BC_IDENTITY_ACTOR (ID);
      
-- 表扬
CREATE TABLE BS_CASE_PRAISE (
   ID                   NUMBER(19)           NOT NULL,
   PRAISE_TYPE          VARCHAR2(255),
   RECEIVE_DATE         DATE                 NOT NULL,
   RECEIVER_ID          NUMBER(19),
   RECEIVER_NAME        VARCHAR2(255),
   SUBJECT2             VARCHAR2(255),
   DETAIL               VARCHAR2(4000),
   CAR_COLOR            VARCHAR2(255),
   DRIVER_SEX           NUMBER(1)            NOT NULL,
   DRIVER_FEATURE       VARCHAR2(255),
   ADVISOR_NAME         VARCHAR2(255)        NOT NULL,
   ADVISOR_SEX          NUMBER(1)            NOT NULL,
   ADVISOR_AGE          NUMBER(3),
   ADVISOR_PHONE        VARCHAR2(255),
   ADVISOR_CERT         VARCHAR2(255),
   NOTICE_DATE          DATE,
   RESULT_              VARCHAR2(4000),
   TICKET               VARCHAR2(255),
   MACHINE_PRICE        NUMBER(10),
   CHARGE               NUMBER(10),
   RIDING_TIME_START    DATE,
   RIDING_TIME_END      DATE,
   PATH_FROM            VARCHAR2(255),
   PATH_TO              VARCHAR2(255),
   PATH                 VARCHAR2(255),
   PASSENGER_COUNT_MAN  NUMBER(1),
   PASSENGER_COUNT_WOMAN NUMBER(1),
   PASSENGER_COUNT_CHILD NUMBER(1),
   PASSENGER_COUNT      NUMBER(1),
   REWARD_MONEY         NUMBER(10,2),
   CONSTRAINT BSPK_CASE_PRAISE PRIMARY KEY (ID)
);
COMMENT ON TABLE BS_CASE_PRAISE IS '表扬';
COMMENT ON COLUMN BS_CASE_PRAISE.PRAISE_TYPE IS '表扬类型';
COMMENT ON COLUMN BS_CASE_PRAISE.RECEIVE_DATE IS '接诉时间';
COMMENT ON COLUMN BS_CASE_PRAISE.RECEIVER_ID IS '经办人ID';
COMMENT ON COLUMN BS_CASE_PRAISE.RECEIVER_NAME IS '经办人姓名';
COMMENT ON COLUMN BS_CASE_PRAISE.SUBJECT2 IS '表扬项目小类';
COMMENT ON COLUMN BS_CASE_PRAISE.DETAIL IS '表扬内容';
COMMENT ON COLUMN BS_CASE_PRAISE.CAR_COLOR IS '车色';
COMMENT ON COLUMN BS_CASE_PRAISE.DRIVER_SEX IS '司机性别:0-未设,1-男,2-女';
COMMENT ON COLUMN BS_CASE_PRAISE.DRIVER_FEATURE IS '司机特征';
COMMENT ON COLUMN BS_CASE_PRAISE.ADVISOR_NAME IS '投诉人姓名';
COMMENT ON COLUMN BS_CASE_PRAISE.ADVISOR_SEX IS '投诉人性别';
COMMENT ON COLUMN BS_CASE_PRAISE.ADVISOR_AGE IS '投诉人年龄';
COMMENT ON COLUMN BS_CASE_PRAISE.ADVISOR_PHONE IS '投诉人电话';
COMMENT ON COLUMN BS_CASE_PRAISE.ADVISOR_CERT IS '投诉人证件号';
COMMENT ON COLUMN BS_CASE_PRAISE.NOTICE_DATE IS '通知时间';
COMMENT ON COLUMN BS_CASE_PRAISE.RESULT_ IS '处理结果';
COMMENT ON COLUMN BS_CASE_PRAISE.TICKET IS '车票号码';
COMMENT ON COLUMN BS_CASE_PRAISE.MACHINE_PRICE IS '计费器显示价格';
COMMENT ON COLUMN BS_CASE_PRAISE.CHARGE IS '实际收费';
COMMENT ON COLUMN BS_CASE_PRAISE.RIDING_TIME_START IS '乘车起始时间';
COMMENT ON COLUMN BS_CASE_PRAISE.RIDING_TIME_END IS '乘车结束时间';
COMMENT ON COLUMN BS_CASE_PRAISE.PATH_FROM IS '乘车路线(从)';
COMMENT ON COLUMN BS_CASE_PRAISE.PATH_TO IS '乘车路线(到)';
COMMENT ON COLUMN BS_CASE_PRAISE.PATH IS '乘车路线';
COMMENT ON COLUMN BS_CASE_PRAISE.PASSENGER_COUNT_MAN IS '乘车人数(男)';
COMMENT ON COLUMN BS_CASE_PRAISE.PASSENGER_COUNT_WOMAN IS '乘车人数(女)';
COMMENT ON COLUMN BS_CASE_PRAISE.PASSENGER_COUNT_CHILD IS '乘车人数(童)';
COMMENT ON COLUMN BS_CASE_PRAISE.PASSENGER_COUNT IS '乘车人数';
COMMENT ON COLUMN BS_CASE_PRAISE.REWARD_MONEY IS '获奖金额';
ALTER TABLE BS_CASE_PRAISE ADD CONSTRAINT BSFK_PRAISE_CASEBASE FOREIGN KEY (ID)
      REFERENCES BS_CASE_BASE (ID);
ALTER TABLE BS_CASE_PRAISE ADD CONSTRAINT BSFK_PRAISE_RECEIVER FOREIGN KEY (RECEIVER_ID)
      REFERENCES BC_IDENTITY_ACTOR (ID);

-- 工伤
CREATE TABLE BS_INDUSTRIAL_INJURY 
(
   ID                   NUMBER(19)           NOT NULL,
   UID_                 VARCHAR2(36)         NOT NULL,
   CONTRACT_ID          NUMBER(19)           NOT NULL,
   STATUS_		NUMBER(19)	     NOT NULL,
   CODE                 VARCHAR2(255)        NOT NULL,
   HAPPEN_DATE          DATE,
   CONFIRM_DATE         DATE,
   START_DATE           DATE,
   END_DATE             DATE,
   COMPENSATION         VARCHAR2(255),
   MONEY                NUMBER(10,2),
   IS_OAS               NUMBER(1)            DEFAULT 0,
   IS_IN_HOSPITAL       NUMBER(1)            DEFAULT 0,
   IS_LI                NUMBER(1)            DEFAULT 0,
   DESCRIPTION          VARCHAR2(4000),
   FILE_DATE            DATE                 NOT NULL,
   AUTHOR_ID            NUMBER(19)           NOT NULL,
   MODIFIER_ID          NUMBER(19),
   MODIFIED_DATE        DATE,
   CONSTRAINT PK_BS_INDUSTRIAL_INJURY PRIMARY KEY (ID)
);
COMMENT ON TABLE BS_INDUSTRIAL_INJURY IS '工伤';
COMMENT ON COLUMN BS_INDUSTRIAL_INJURY.CONTRACT_ID IS '合同ID';
COMMENT ON COLUMN BS_INDUSTRIAL_INJURY.STATUS_ IS '状态：0-正常,1-已禁用';
COMMENT ON COLUMN BS_INDUSTRIAL_INJURY.CODE IS '工伤号';
COMMENT ON COLUMN BS_INDUSTRIAL_INJURY.HAPPEN_DATE IS '工伤时间';
COMMENT ON COLUMN BS_INDUSTRIAL_INJURY.CONFIRM_DATE IS '认定日期';
COMMENT ON COLUMN BS_INDUSTRIAL_INJURY.START_DATE IS '医疗开始日期';
COMMENT ON COLUMN BS_INDUSTRIAL_INJURY.END_DATE IS '医疗结束日期';
COMMENT ON COLUMN BS_INDUSTRIAL_INJURY.COMPENSATION IS '赔偿项目';
COMMENT ON COLUMN BS_INDUSTRIAL_INJURY.MONEY IS '金额';
COMMENT ON COLUMN BS_INDUSTRIAL_INJURY.IS_OAS IS '是否门诊';
COMMENT ON COLUMN BS_INDUSTRIAL_INJURY.IS_IN_HOSPITAL IS '是否住院';
COMMENT ON COLUMN BS_INDUSTRIAL_INJURY.IS_LI IS '是否劳动鉴别';
COMMENT ON COLUMN BS_INDUSTRIAL_INJURY.DESCRIPTION IS '概况描述';
COMMENT ON COLUMN BS_INDUSTRIAL_INJURY.FILE_DATE IS '创建时间';
COMMENT ON COLUMN BS_INDUSTRIAL_INJURY.AUTHOR_ID IS '创建人ID';
COMMENT ON COLUMN BS_INDUSTRIAL_INJURY.MODIFIER_ID IS '最后修改人ID';
COMMENT ON COLUMN BS_INDUSTRIAL_INJURY.MODIFIED_DATE IS '最后修改时间';
ALTER TABLE BS_INDUSTRIAL_INJURY ADD CONSTRAINT BSFK_INDUS_REFERENCE_BS_CONTR FOREIGN KEY (CONTRACT_ID)
      REFERENCES BS_CONTRACT_LABOUR (ID);
ALTER TABLE BS_INDUSTRIAL_INJURY ADD CONSTRAINT BSFK_INDUS_REFERENCE_BC_AUTHOR FOREIGN KEY (AUTHOR_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
ALTER TABLE BS_INDUSTRIAL_INJURY ADD CONSTRAINT BSFK_INDUS_INJURY_BC_MODIFIER FOREIGN KEY (MODIFIER_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
	  
-- 车辆保单
CREATE TABLE BS_CAR_POLICY (
   ID                   NUMBER(19)           NOT NULL,
   UID_                 VARCHAR2(36)         NOT NULL,
   VER_MAJOR            NUMBER(2),
   VER_MINOR            NUMBER(3),
   PATCH_NO             VARCHAR2(255)        NOT NULL,
   MAIN                 NUMBER(1)            NOT NULL,
   PID                  NUMBER(19),
   OP_TYPE              NUMBER(1)            NOT NULL,
   STATUS_              NUMBER(1)            NOT NULL,
   CAR_ID               NUMBER(19)           NOT NULL,
   REGISTER_DATE        DATE,
   ASSURED              VARCHAR2(255),
   COMMERIAL_NO         VARCHAR2(255),
   COMMERIAL_COMPANY    VARCHAR2(255),
   COMMERIAL_START_DATE DATE,
   COMMERIAL_END_DATE   DATE,
   OWNRISK              NUMBER(1),
   GREENSLIP            NUMBER(1),
   GREENSLIP_SAME_DATE  NUMBER(1),
   GREENSLIP_NO         VARCHAR2(255),
   GREENSLIP_COMPANY    VARCHAR2(255),
   GREENSLIP_START_DATE               DATE,
   GREENSLIP_END_DATE                 DATE,
   GREENSLIP_SOURCE     VARCHAR2(255),
   LIABILITY_NO         VARCHAR2(255),
   AMOUNT               NUMBER(10,2),
   STOPDATE             DATE,
   FILE_DATE            DATE                 NOT NULL,
   AUTHOR_ID            NUMBER(19)           NOT NULL,
   MODIFIED_DATE        DATE,
   MODIFIER_ID          NUMBER(19),
   CONSTRAINT BSPK_CARPOLICY PRIMARY KEY (ID)
);
COMMENT ON TABLE BS_CAR_POLICY IS '车辆保单';
COMMENT ON COLUMN BS_CAR_POLICY.STATUS_ IS '状态：0-正常,1-注销';
COMMENT ON COLUMN BS_CAR_POLICY.VER_MAJOR IS '主版本号';
COMMENT ON COLUMN BS_CAR_POLICY.VER_MINOR IS '次版本号';
COMMENT ON COLUMN BS_CAR_POLICY.PATCH_NO IS '批号';
COMMENT ON COLUMN BS_CAR_POLICY.MAIN IS '主体: 0-当前版本,1-历史版本';
COMMENT ON COLUMN BS_CAR_POLICY.PID IS '父级ID';
COMMENT ON COLUMN BS_CONTRACT.OP_TYPE IS '操作类型: 1-新建,2-维护,3-续保,4-停保';
COMMENT ON COLUMN BS_CAR_POLICY.CAR_ID IS '投保车号';
COMMENT ON COLUMN BS_CAR_POLICY.REGISTER_DATE IS '初登日期';
COMMENT ON COLUMN BS_CAR_POLICY.ASSURED IS '投保人';
COMMENT ON COLUMN BS_CAR_POLICY.COMMERIAL_NO IS '商业险号';
COMMENT ON COLUMN BS_CAR_POLICY.COMMERIAL_COMPANY IS '商业险保险公司';
COMMENT ON COLUMN BS_CAR_POLICY.COMMERIAL_START_DATE IS '商业险开始日期';
COMMENT ON COLUMN BS_CAR_POLICY.COMMERIAL_END_DATE IS '商业险结束日期';
COMMENT ON COLUMN BS_CAR_POLICY.OWNRISK IS '是否自保';
COMMENT ON COLUMN BS_CAR_POLICY.GREENSLIP IS '是否购买了强制险';
COMMENT ON COLUMN BS_CAR_POLICY.GREENSLIP_SAME_DATE IS '强制险是否与商业险同期';
COMMENT ON COLUMN BS_CAR_POLICY.GREENSLIP_NO IS '强险单号';
COMMENT ON COLUMN BS_CAR_POLICY.GREENSLIP_COMPANY IS '强险保险公司';
COMMENT ON COLUMN BS_CAR_POLICY.GREENSLIP_START_DATE IS '强制险开始日期';
COMMENT ON COLUMN BS_CAR_POLICY.GREENSLIP_END_DATE IS '强制险结束日期';
COMMENT ON COLUMN BS_CAR_POLICY.GREENSLIP_SOURCE IS '强保人来源';
COMMENT ON COLUMN BS_CAR_POLICY.LIABILITY_NO IS '责任险单号';
COMMENT ON COLUMN BS_CAR_POLICY.STOPDATE IS '停保日期';
COMMENT ON COLUMN BS_CAR_POLICY.AMOUNT IS '合计';
COMMENT ON COLUMN BS_CAR_POLICY.FILE_DATE IS '创建时间';
COMMENT ON COLUMN BS_CAR_POLICY.AUTHOR_ID IS '创建人ID';
COMMENT ON COLUMN BS_CAR_POLICY.MODIFIED_DATE IS '最后修改时间';
COMMENT ON COLUMN BS_CAR_POLICY.MODIFIER_ID IS '最后修改人ID';
ALTER TABLE BS_CAR_POLICY ADD CONSTRAINT BSFK_CARPOLICY_AUTHOR FOREIGN KEY (AUTHOR_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
ALTER TABLE BS_CAR_POLICY ADD CONSTRAINT BSFK_CARPOLICY_MODIFIER FOREIGN KEY (MODIFIER_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
ALTER TABLE BS_CAR_POLICY ADD CONSTRAINT BSFK_POLICY_REFERENCE_BS_POLICY FOREIGN KEY (PID)
      REFERENCES BS_CAR_POLICY (ID);
ALTER TABLE BS_CAR_POLICY ADD CONSTRAINT BSFK_CARPOLICY_CAR FOREIGN KEY (CAR_ID )
      REFERENCES BS_CAR (ID);
CREATE INDEX BSIDX_CAR_POLICY ON BS_CAR_POLICY (CAR_ID);
-- 购买车保险种
CREATE TABLE BS_BUY_PLANT 
(
   ID                   NUMBER(19)          NOT NULL,
   PID                  NUMBER(19)          NOT NULL,
   NAME                 VARCHAR(255)       NOT NULL,
   COVERAGE		        NUMERIC(10,2),
   PREMIUM              NUMERIC(10,2),
   DESC_                VARCHAR(4000),
   CONSTRAINT BSPK_BUY_PLANT PRIMARY KEY (ID)
);
COMMENT ON TABLE BS_BUY_PLANT IS '购买车保险种';
COMMENT ON COLUMN BS_BUY_PLANT.PID IS '所属保单ID';
COMMENT ON COLUMN BS_BUY_PLANT.NAME IS '险种名称';
COMMENT ON COLUMN BS_BUY_PLANT.COVERAGE IS '保额';
COMMENT ON COLUMN BS_BUY_PLANT.PREMIUM IS '保费';
COMMENT ON COLUMN BS_BUY_PLANT.DESC_ IS '备注';
ALTER TABLE BS_BUY_PLANT ADD CONSTRAINT BSFK_BUYPLANT_CARPOLICY FOREIGN KEY (PID)
      REFERENCES BS_CAR_POLICY (ID);


-- 车辆保单险种
CREATE TABLE BS_INSURANCE_TYPE 
(
   ID                   NUMBER(19)          NOT NULL,
   STATUS_              NUMBER(1)           NOT NULL,
   NAME                 VARCHAR2(255)       NOT NULL,
   COVERAGE		        NUMBER(10,2),
   PREMIUM              NUMBER(10,2),
   DESC_                VARCHAR(4000),
   FILE_DATE            DATE                 NOT NULL,
   AUTHOR_ID            NUMBER(19)           NOT NULL,
   MODIFIER_ID          NUMBER(19),
   MODIFIED_DATE        DATE,
   CONSTRAINT BSPK_INSURANCE_TYPE PRIMARY KEY (ID)
);
COMMENT ON TABLE BS_INSURANCE_TYPE IS '车辆保单险种';
COMMENT ON COLUMN BS_INSURANCE_TYPE.STATUS_ IS '状态：0-正常,1-禁用';
COMMENT ON COLUMN BS_INSURANCE_TYPE.NAME IS '险种名称';
COMMENT ON COLUMN BS_INSURANCE_TYPE.COVERAGE IS '保额';
COMMENT ON COLUMN BS_INSURANCE_TYPE.PREMIUM IS '保费';
COMMENT ON COLUMN BS_INSURANCE_TYPE.DESC_ IS '备注';
COMMENT ON COLUMN BS_INSURANCE_TYPE.FILE_DATE IS '创建时间';
COMMENT ON COLUMN BS_INSURANCE_TYPE.AUTHOR_ID IS '创建人ID';
COMMENT ON COLUMN BS_INSURANCE_TYPE.MODIFIER_ID IS '最后修改人ID';
COMMENT ON COLUMN BS_INSURANCE_TYPE.MODIFIED_DATE IS '最后修改时间';
ALTER TABLE BS_INSURANCE_TYPE ADD CONSTRAINT BSFK_INSURANCETYPE_AUTHOR FOREIGN KEY (AUTHOR_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
ALTER TABLE BS_INSURANCE_TYPE ADD CONSTRAINT BSFK_INSURANCETYPE_MODIFIER FOREIGN KEY (MODIFIER_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);

-- 从交委WebService接口同步的交通违章信息
CREATE TABLE BS_SYNC_JIAOWEI_JTWF (
    ID number(19) NOT NULL,
    HAPPEN_DATE DATE NOT NULL,
    CAR_PLATE_TYPE varchar2(100) NOT NULL,
    CAR_PLATE_NO varchar2(100) NOT NULL,
    DRIVER_CERT varchar2(255),
    DRIVER_NAME varchar2(255),
    JEOM number(10,1) NOT NULL,
    COMPANY_NAME varchar2(255),
    CONTENT varchar2(4000) NOT NULL,
    CONSTRAINT BSPK_SYNC_JIAOWEI_JTWF PRIMARY KEY (ID)
);
COMMENT ON TABLE BS_SYNC_JIAOWEI_JTWF IS '交委WebService接口的交通违章信息';
COMMENT ON COLUMN BS_SYNC_JIAOWEI_JTWF.HAPPEN_DATE IS '违章时间';
COMMENT ON COLUMN BS_SYNC_JIAOWEI_JTWF.CONTENT IS '违章内容';
COMMENT ON COLUMN BS_SYNC_JIAOWEI_JTWF.CAR_PLATE_TYPE IS '车牌类型';
COMMENT ON COLUMN BS_SYNC_JIAOWEI_JTWF.CAR_PLATE_NO IS '车牌号';
COMMENT ON COLUMN BS_SYNC_JIAOWEI_JTWF.DRIVER_NAME IS '当事司机姓名';
COMMENT ON COLUMN BS_SYNC_JIAOWEI_JTWF.DRIVER_CERT IS '服务资格证';
COMMENT ON COLUMN BS_SYNC_JIAOWEI_JTWF.JEOM IS '本次扣分';
COMMENT ON COLUMN BS_SYNC_JIAOWEI_JTWF.COMPANY_NAME IS '单位名称';
ALTER TABLE BS_SYNC_JIAOWEI_JTWF ADD CONSTRAINT BSFK_JIAOWEIJTWF2BASE FOREIGN KEY (ID)
      REFERENCES BC_SYNC_BASE (ID);
CREATE INDEX BCIDX_JIAOWEIJTWF_DRIVER_CERT ON BS_SYNC_JIAOWEI_JTWF (DRIVER_CERT);
CREATE INDEX BCIDX_JIAOWEIJTWF_CAR_PLATE ON BS_SYNC_JIAOWEI_JTWF (CAR_PLATE_TYPE,CAR_PLATE_NO);

-- 从交委WebService接口同步的营运违章信息
CREATE TABLE BS_SYNC_JIAOWEI_YYWZ (
    ID			NUMBER(19) NOT NULL,
    C_ID		VARCHAR2(255) NOT NULL,
    STATUS		VARCHAR2(100),
    CERT_KJ		VARCHAR2(255),
    OPERATOR		VARCHAR2(255),
    OPERATE_UNIT        VARCHAR2(255),
    VIDEO_OPERATER      VARCHAR2(255),
    DRIVER_NAME		VARCHAR2(255),
    IDCARD_TYPE         VARCHAR2(255),
    IDCARD_CODE         VARCHAR2(255),
    CAR_PLATE		VARCHAR2(255),
    COMPANY		VARCHAR2(255),
    ADDRESS             VARCHAR2(1000),
    OWNER               VARCHAR2(255),
    OWNER_ID            VARCHAR2(100),
    BS_CERT_NO          VARCHAR2(255),
    CONTENT		VARCHAR2(4000) NOT NULL,
    HAPPEN_DATE         DATE NOT NULL,
    EVIDENCE_UNIT       VARCHAR2(255),
    WZ_TYPE		VARCHAR2(255),
    BUSLINES		VARCHAR2(255),
    CARPLATE_COLOR	VARCHAR2(100),
    DRIVER_CERT		VARCHAR2(255),
    COMMIT_STATUS	VARCHAR2(255),
    RECEIPT             VARCHAR2(255),
    NOTICE		VARCHAR2(255),
    CERT_YY             VARCHAR2(255),
    SEATING		NUMBER(10,1),
    OWE_RECORD          VARCHAR2(255),
    OWE_SIGNATURE	VARCHAR2(255),
    LEAVE_TROOPS	VARCHAR2(255),
    AREA                VARCHAR2(255),
    CLOSE_DATE          DATE,
    DESC_               VARCHAR2(4000),
    CLONE               VARCHAR2(4000),
    SUBJECT             VARCHAR2(1000),
    DETAIN              VARCHAR2(255),
    PULL_UNIT           VARCHAR2(255),
    PENALTY             NUMBER(10,2),
    CONSTRAINT BSPK_SYNC_JIAOWEI_YYWZ PRIMARY KEY (ID)
);
COMMENT ON TABLE BS_SYNC_JIAOWEI_YYWZ IS '交委WebService接口的营运违章信息';
COMMENT ON COLUMN BS_SYNC_JIAOWEI_YYWZ.STATUS IS '状态';
COMMENT ON COLUMN BS_SYNC_JIAOWEI_YYWZ.CERT_KJ IS '扣件证号';
COMMENT ON COLUMN BS_SYNC_JIAOWEI_YYWZ.OPERATOR IS '执法人';
COMMENT ON COLUMN BS_SYNC_JIAOWEI_YYWZ.OPERATE_UNIT IS '执法分队';
COMMENT ON COLUMN BS_SYNC_JIAOWEI_YYWZ.VIDEO_OPERATER IS '摄录员';
COMMENT ON COLUMN BS_SYNC_JIAOWEI_YYWZ.DRIVER_NAME IS '当事人';
COMMENT ON COLUMN BS_SYNC_JIAOWEI_YYWZ.IDCARD_TYPE IS '身份证明类型';
COMMENT ON COLUMN BS_SYNC_JIAOWEI_YYWZ.IDCARD_CODE IS '身份证明编号';
COMMENT ON COLUMN BS_SYNC_JIAOWEI_YYWZ.CAR_PLATE IS '违章主体';
COMMENT ON COLUMN BS_SYNC_JIAOWEI_YYWZ.COMPANY IS '违章企业';
COMMENT ON COLUMN BS_SYNC_JIAOWEI_YYWZ.ADDRESS IS '违章地段';
COMMENT ON COLUMN BS_SYNC_JIAOWEI_YYWZ.OWNER IS '业户名称';
COMMENT ON COLUMN BS_SYNC_JIAOWEI_YYWZ.OWNER_ID IS '业户ID';
COMMENT ON COLUMN BS_SYNC_JIAOWEI_YYWZ.BS_CERT_NO IS '经营许可证号';
COMMENT ON COLUMN BS_SYNC_JIAOWEI_YYWZ.CONTENT IS '违章内容';
COMMENT ON COLUMN BS_SYNC_JIAOWEI_YYWZ.EVIDENCE_UNIT IS '证物保存单位';
COMMENT ON COLUMN BS_SYNC_JIAOWEI_YYWZ.WZ_TYPE IS '违章类型';
COMMENT ON COLUMN BS_SYNC_JIAOWEI_YYWZ.BUSLINES IS '公交线路';
COMMENT ON COLUMN BS_SYNC_JIAOWEI_YYWZ.CARPLATE_COLOR IS '车牌颜色';
COMMENT ON COLUMN BS_SYNC_JIAOWEI_YYWZ.DRIVER_CERT IS '资格证号';
COMMENT ON COLUMN BS_SYNC_JIAOWEI_YYWZ.COMMIT_STATUS IS '提交状态';
COMMENT ON COLUMN BS_SYNC_JIAOWEI_YYWZ.RECEIPT IS '罚没收据编号';
COMMENT ON COLUMN BS_SYNC_JIAOWEI_YYWZ.NOTICE IS '放行通知书编号';
COMMENT ON COLUMN BS_SYNC_JIAOWEI_YYWZ.CERT_YY IS '营运证号';
COMMENT ON COLUMN BS_SYNC_JIAOWEI_YYWZ.SEATING IS '座位数';
COMMENT ON COLUMN BS_SYNC_JIAOWEI_YYWZ.OWE_RECORD IS '欠笔录';
COMMENT ON COLUMN BS_SYNC_JIAOWEI_YYWZ.OWE_SIGNATURE IS '欠签名';
COMMENT ON COLUMN BS_SYNC_JIAOWEI_YYWZ.LEAVE_TROOPS IS '留队部';
COMMENT ON COLUMN BS_SYNC_JIAOWEI_YYWZ.AREA IS '所属区县';
COMMENT ON COLUMN BS_SYNC_JIAOWEI_YYWZ.CLOSE_DATE IS '结案日期';
COMMENT ON COLUMN BS_SYNC_JIAOWEI_YYWZ.DESC_ IS '备注';
COMMENT ON COLUMN BS_SYNC_JIAOWEI_YYWZ.CLONE IS '是否克隆车';
COMMENT ON COLUMN BS_SYNC_JIAOWEI_YYWZ.SUBJECT IS '违章项目';
COMMENT ON COLUMN BS_SYNC_JIAOWEI_YYWZ.DETAIN IS '扣留物品';
COMMENT ON COLUMN BS_SYNC_JIAOWEI_YYWZ.PULL_UNIT IS '拖车单位';
COMMENT ON COLUMN BS_SYNC_JIAOWEI_YYWZ.PENALTY IS '罚款';
ALTER TABLE BS_SYNC_JIAOWEI_YYWZ ADD CONSTRAINT BSFK_JIAOWEIYYWZBASE FOREIGN KEY (ID)
      REFERENCES BC_SYNC_BASE (ID);
CREATE INDEX BCIDX_JIAOWEIYYWZ_DRIVER_CERT ON BS_SYNC_JIAOWEI_YYWZ (DRIVER_CERT);


-- 从交委WebService接口同步的投诉与建议信息
CREATE TABLE BS_SYNC_JIAOWEI_ADVICE (
    ID			NUMBER(19) NOT NULL,
    C_ID		VARCHAR2(255) NOT NULL,
    RECEIVE_CODE        VARCHAR2(255),
    ADVISOR_NAME        VARCHAR2(255) NOT NULL,
    PATH_FROM           VARCHAR2(255),
    PATH_TO             VARCHAR2(255),
    RIDING_TIME_START   DATE,
    RIDING_TIME_END     DATE,
    ADVISOR_SEX         VARCHAR2(100),
    ADVISOR_AGE         NUMBER(3,0),
    ADVISOR_PHONE       VARCHAR2(255),
    ADVISOR_CERT        VARCHAR2(255),
    OLD_UNIT_NAME       VARCHAR2(255),
    CAR_PLATE		VARCHAR2(255),
    DRIVER_ID		VARCHAR2(255),
    DRIVER_CHAR         VARCHAR2(255),
    CONTENT		VARCHAR2(4000) NOT NULL,
    RECEIVE_DATE        DATE,
    RESULT_             VARCHAR2(4000),
    ADVICE_TYPE		VARCHAR2(255),
    ADVICE_BS		VARCHAR2(255),
    SUBJECT             VARCHAR2(255),
    SUBJECT2            VARCHAR2(255),
    MACHINE_PRICE       VARCHAR2(255),
    TICKET              VARCHAR2(255),
    CHARGE              VARCHAR2(255),
    DRIVER_SEX          VARCHAR2(10),
    SUGGEST_BS		VARCHAR2(255),
    BUSLINES            VARCHAR2(255),
    BUS_COLOR		VARCHAR2(255),
    REPLY		VARCHAR2(255),
    CONSTRAINT BSPK_SYNC_JIAOWEI_ADVICE PRIMARY KEY (ID)
);
COMMENT ON TABLE BS_SYNC_JIAOWEI_ADVICE IS '交委WebService接口的投诉与建议信息';
COMMENT ON COLUMN BS_SYNC_JIAOWEI_ADVICE.RECEIVE_CODE IS '电话受理号';
COMMENT ON COLUMN BS_SYNC_JIAOWEI_ADVICE.ADVISOR_NAME IS '投诉人姓名';
COMMENT ON COLUMN BS_SYNC_JIAOWEI_ADVICE.PATH_FROM IS '乘车路线(从)';
COMMENT ON COLUMN BS_SYNC_JIAOWEI_ADVICE.PATH_TO IS '乘车路线(到)';
COMMENT ON COLUMN BS_SYNC_JIAOWEI_ADVICE.RIDING_TIME_START IS '乘车起始时间';
COMMENT ON COLUMN BS_SYNC_JIAOWEI_ADVICE.RIDING_TIME_END IS '乘车结束时间';
COMMENT ON COLUMN BS_SYNC_JIAOWEI_ADVICE.ADVISOR_SEX IS '投诉人性别';
COMMENT ON COLUMN BS_SYNC_JIAOWEI_ADVICE.ADVISOR_AGE IS '投诉人年龄';
COMMENT ON COLUMN BS_SYNC_JIAOWEI_ADVICE.ADVISOR_PHONE IS '投诉人电话';
COMMENT ON COLUMN BS_SYNC_JIAOWEI_ADVICE.ADVISOR_CERT IS '投诉人证件号';
COMMENT ON COLUMN BS_SYNC_JIAOWEI_ADVICE.OLD_UNIT_NAME IS '车属单位';
COMMENT ON COLUMN BS_SYNC_JIAOWEI_ADVICE.CAR_PLATE IS '车牌号码';
COMMENT ON COLUMN BS_SYNC_JIAOWEI_ADVICE.DRIVER_ID IS '资格证号';
COMMENT ON COLUMN BS_SYNC_JIAOWEI_ADVICE.DRIVER_CHAR IS '司机特征';
COMMENT ON COLUMN BS_SYNC_JIAOWEI_ADVICE.CONTENT IS '投诉内容';
COMMENT ON COLUMN BS_SYNC_JIAOWEI_ADVICE.RECEIVE_DATE IS '受理时间';
COMMENT ON COLUMN BS_SYNC_JIAOWEI_ADVICE.RESULT_ IS '处理结果';
COMMENT ON COLUMN BS_SYNC_JIAOWEI_ADVICE.ADVICE_TYPE IS '投诉或建议';
COMMENT ON COLUMN BS_SYNC_JIAOWEI_ADVICE.ADVICE_BS IS '投诉行业';
COMMENT ON COLUMN BS_SYNC_JIAOWEI_ADVICE.SUBJECT IS '投诉项目大类';
COMMENT ON COLUMN BS_SYNC_JIAOWEI_ADVICE.SUBJECT2 IS '投诉项目小类';
COMMENT ON COLUMN BS_SYNC_JIAOWEI_ADVICE.MACHINE_PRICE IS '计费器显示价格';
COMMENT ON COLUMN BS_SYNC_JIAOWEI_ADVICE.TICKET IS '车票号码';
COMMENT ON COLUMN BS_SYNC_JIAOWEI_ADVICE.CHARGE IS '实际收费';
COMMENT ON COLUMN BS_SYNC_JIAOWEI_ADVICE.DRIVER_SEX IS '司机性别';
COMMENT ON COLUMN BS_SYNC_JIAOWEI_ADVICE.SUGGEST_BS IS '建议行业';
COMMENT ON COLUMN BS_SYNC_JIAOWEI_ADVICE.BUSLINES IS '公交线路或站场';
COMMENT ON COLUMN BS_SYNC_JIAOWEI_ADVICE.BUS_COLOR IS '颜色';
COMMENT ON COLUMN BS_SYNC_JIAOWEI_ADVICE.REPLY IS '是否回复';
ALTER TABLE BS_SYNC_JIAOWEI_ADVICE ADD CONSTRAINT BSFK_JIAOWEIADVICEBASE FOREIGN KEY (ID)
      REFERENCES BC_SYNC_BASE (ID);
CREATE INDEX BCIDX_JIAOWEIADVICE_DRIVER_CERT ON BS_SYNC_JIAOWEI_ADVICE (DRIVER_CERT);

-- 从金盾网抓取的交通违法信息
CREATE TABLE BS_SYNC_JINDUN_JTWF (
    ID number(19) NOT NULL,
    CAR_TYPE varchar2(10) NOT NULL,
    CAR_TYPE_DESC varchar2(100) NOT NULL,
    CAR_PLATE_TYPE varchar2(100) NOT NULL,
    CAR_PLATE_NO varchar2(100) NOT NULL,
    ENGINE_NO varchar2(255),
    HAPPEN_DATE DATE NOT NULL,
    ADDRESS varchar2(1000),
    DRIVER_NAME varchar2(255),
    JEOM number(10,1) NOT NULL,
    PENALTY number(10,1) NOT NULL,
    OVERDUE_PAYMENT number(10,1) NOT NULL,
    DECISION_NO varchar2(255),
    DECISION_TYPE varchar2(255),
    SOURCE varchar2(255),
    TRAFFIC varchar2(255),
    BREAK_TYPE varchar2(255),
    CONSTRAINT BSPK_SYNC_JINDUN_JTWF PRIMARY KEY (ID)
);
COMMENT ON TABLE BS_SYNC_JINDUN_JTWF IS '从金盾网抓取的交通违法信息';
COMMENT ON COLUMN BS_SYNC_JINDUN_JTWF.HAPPEN_DATE IS '违法时间';
COMMENT ON COLUMN BS_SYNC_JINDUN_JTWF.CAR_TYPE IS '号牌种类';
COMMENT ON COLUMN BS_SYNC_JINDUN_JTWF.CAR_TYPE_DESC IS '号牌种类的中文描述';
COMMENT ON COLUMN BS_SYNC_JINDUN_JTWF.CAR_PLATE_TYPE IS '车牌类型';
COMMENT ON COLUMN BS_SYNC_JINDUN_JTWF.CAR_PLATE_NO IS '车牌号';
COMMENT ON COLUMN BS_SYNC_JINDUN_JTWF.ENGINE_NO IS '发动机号';
COMMENT ON COLUMN BS_SYNC_JINDUN_JTWF.DRIVER_NAME IS '当事人';
COMMENT ON COLUMN BS_SYNC_JINDUN_JTWF.JEOM IS '违法记分数';
COMMENT ON COLUMN BS_SYNC_JINDUN_JTWF.ADDRESS IS '违法地点';
COMMENT ON COLUMN BS_SYNC_JINDUN_JTWF.DECISION_NO IS '决定书编号';
COMMENT ON COLUMN BS_SYNC_JINDUN_JTWF.DECISION_TYPE IS '决定书类别';
COMMENT ON COLUMN BS_SYNC_JINDUN_JTWF.SOURCE IS '违法来源';
COMMENT ON COLUMN BS_SYNC_JINDUN_JTWF.PENALTY IS '罚款金额';
COMMENT ON COLUMN BS_SYNC_JINDUN_JTWF.OVERDUE_PAYMENT IS '滞纳金';
COMMENT ON COLUMN BS_SYNC_JINDUN_JTWF.TRAFFIC IS '交通方式';
COMMENT ON COLUMN BS_SYNC_JINDUN_JTWF.BREAK_TYPE IS '违法行为';
ALTER TABLE BS_SYNC_JINDUN_JTWF ADD CONSTRAINT BSFK_JINDUNJTWF2BASE FOREIGN KEY (ID)
      REFERENCES BC_SYNC_BASE (ID);
CREATE INDEX BCIDX_JINDUNJTWF_CAR ON BS_SYNC_JINDUN_JTWF (CAR_PLATE_TYPE,CAR_PLATE_NO);
