-- ????Identity??????У??????1
CREATE sequence CORE_SEQUENCE
    minvalue 1
    start with 1000
    increment by 1
    cache 20;

-- ????????????????У??????100000
CREATE sequence DC_SEQUENCE
    minvalue 1
    start with 100000
    increment by 1
    cache 20;

-- ?????????
CREATE TABLE DC_RECORD(
  TYPE_         VARCHAR2(255) NOT NULL,
  FROM_ID       NUMBER(19) NOT NULL,
  TO_ID         NUMBER(19) NOT NULL,
  FROM_TABLE    VARCHAR2(255),
  TO_TABLE      VARCHAR2(255),
  CREATE_DATE   DATE NOT NULL,
  REMARK        VARCHAR2(4000),
  MODIFIED_DATE DATE
);
COMMENT ON TABLE DC_RECORD IS '?????????';
COMMENT ON COLUMN DC_RECORD.TYPE_ IS '????';
COMMENT ON COLUMN DC_RECORD.FROM_ID IS '??????ID';
COMMENT ON COLUMN DC_RECORD.TO_ID IS '?±?????ID';
COMMENT ON COLUMN DC_RECORD.FROM_TABLE IS '????????';
COMMENT ON COLUMN DC_RECORD.TO_TABLE IS '????????';
COMMENT ON COLUMN DC_RECORD.CREATE_DATE IS '???????';
COMMENT ON COLUMN DC_RECORD.REMARK IS '??????';
COMMENT ON COLUMN DC_RECORD.MODIFIED_DATE IS '?????????';
ALTER TABLE DC_RECORD ADD CONSTRAINT UK_RECORD UNIQUE (TYPE_, FROM_ID);

-- bc?????????????????,???б?????????"BS_"
-- ???д??????????????????????framework.db.mysql.CREATE.sql

-- ???????
CREATE TABLE BS_MOTORCADE (
   ID                   NUMBER(19)           NOT NULL,
   UID_                 VARCHAR2(36),
   CODE                 VARCHAR2(255),
   NAME                 VARCHAR2(255)        NOT NULL,
   FULLNAME             VARCHAR2(255),
   PAYMENT_DATE         DATE,
   COMPANY              VARCHAR2(255),
   COLOR                VARCHAR2(255),
   ADDRESS              VARCHAR2(255),
   PRINCIPAL            VARCHAR2(500),
   PHONE                VARCHAR2(255),
   FAX                  VARCHAR2(255),
   DESC_                VARCHAR2(4000),
   STATUS_              NUMBER(1)            NOT NULL,
   FILE_DATE            DATE                 NOT NULL,
   AUTHOR_ID            NUMBER(19)           NOT NULL,
   MODIFIER_ID          NUMBER(19),
   MODIFIED_DATE        DATE,
   PRIMARY KEY (ID)
);
COMMENT ON TABLE BS_MOTORCADE IS '????';
COMMENT ON COLUMN BS_MOTORCADE.CODE IS '????';
COMMENT ON COLUMN BS_MOTORCADE.NAME IS '???';
COMMENT ON COLUMN BS_MOTORCADE.FULLNAME IS '???';
COMMENT ON COLUMN BS_MOTORCADE.PAYMENT_DATE IS '???????';
COMMENT ON COLUMN BS_MOTORCADE.COMPANY IS '???';
COMMENT ON COLUMN BS_MOTORCADE.COLOR IS '???';
COMMENT ON COLUMN BS_MOTORCADE.ADDRESS IS '???';
COMMENT ON COLUMN BS_MOTORCADE.PRINCIPAL IS '??????';
COMMENT ON COLUMN BS_MOTORCADE.PHONE IS '?绰';
COMMENT ON COLUMN BS_MOTORCADE.FAX IS '????';
COMMENT ON COLUMN BS_MOTORCADE.DESC_ IS '???';
COMMENT ON COLUMN BS_MOTORCADE.STATUS_ IS '????0-??????,1-?????,2-?????';
COMMENT ON COLUMN BS_MOTORCADE.FILE_DATE IS '???????';
COMMENT ON COLUMN BS_MOTORCADE.AUTHOR_ID IS '??????ID';
COMMENT ON COLUMN BS_MOTORCADE.MODIFIER_ID IS '????????ID';
COMMENT ON COLUMN BS_MOTORCADE.MODIFIED_DATE IS '?????????';
ALTER TABLE BS_MOTORCADE ADD CONSTRAINT BSFK_MOTORCADE_AUTHOR FOREIGN KEY (AUTHOR_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
ALTER TABLE BS_MOTORCADE ADD CONSTRAINT BSFK_MOTORCADE_MODIFIER FOREIGN KEY (MODIFIER_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);

-- ?????????????
CREATE TABLE BS_MOTORCADE_CARQUANTITY (
   ID                   NUMBER(19)           NOT NULL,
   MOTORCADE_ID         NUMBER(19)           NOT NULL,
   YEAR_                NUMBER(4)            NOT NULL,
   MONTH_               NUMBER(2)            NOT NULL,
   QUANTITY             NUMBER(19)           NOT NULL,
   FILE_DATE            DATE                 NOT NULL,
   AUTHOR_ID            NUMBER(19)           NOT NULL,
   MODIFIER_ID          NUMBER(19),
   MODIFIED_DATE        DATE,
   PRIMARY KEY (ID)
);
COMMENT ON TABLE BS_MOTORCADE_CARQUANTITY IS '?????????????';
COMMENT ON COLUMN BS_MOTORCADE_CARQUANTITY.MOTORCADE_ID IS '????????ID';
COMMENT ON COLUMN BS_MOTORCADE_CARQUANTITY.YEAR_ IS '???';
COMMENT ON COLUMN BS_MOTORCADE_CARQUANTITY.MONTH_ IS '?·?';
COMMENT ON COLUMN BS_MOTORCADE_CARQUANTITY.QUANTITY IS '??????';
COMMENT ON COLUMN BS_MOTORCADE_CARQUANTITY.FILE_DATE IS '???????';
COMMENT ON COLUMN BS_MOTORCADE_CARQUANTITY.AUTHOR_ID IS '??????ID';
COMMENT ON COLUMN BS_MOTORCADE_CARQUANTITY.MODIFIER_ID IS '????????ID';
COMMENT ON COLUMN BS_MOTORCADE_CARQUANTITY.MODIFIED_DATE IS '?????????';
ALTER TABLE BS_MOTORCADE_CARQUANTITY ADD CONSTRAINT BSFK_CARQUANTITY_AUTHOR FOREIGN KEY (AUTHOR_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
ALTER TABLE BS_MOTORCADE_CARQUANTITY ADD CONSTRAINT BSFK_CARQUANTITY_MODIFIER FOREIGN KEY (MODIFIER_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
ALTER TABLE BS_MOTORCADE_CARQUANTITY ADD CONSTRAINT BSFK_CARQUANTITY_MOTORCADE FOREIGN KEY (MOTORCADE_ID)
      REFERENCES BS_MOTORCADE (ID);


-- ???
create table BS_CERT (
    ID number(19) NOT NULL,
    STATUS_ number(1) NOT NULL,
    UID_ varchar2(36) NOT NULL,
    CERT_CODE varchar2(255) NOT NULL,
    CERT_NAME varchar2(255) NOT NULL,
    CERT_FULL_NAME varchar2(255),
    LICENCER varchar2(255),
    ISSUE_DATE date,
    START_DATE date,
    END_DATE date,
    EXT_STR1 varchar2(255),
    EXT_STR2 varchar2(255),
    EXT_STR3 varchar2(255),
    EXT_NUM1 number(19),
    EXT_NUM2 number(19),
    EXT_NUM3 number(19),
    FILE_DATE date NOT NULL,
    AUTHOR_ID number(19) NOT NULL,
    MODIFIER_ID number(19) ,
    MODIFIED_DATE date,
    primary key (ID)
);
COMMENT ON TABLE BS_CERT IS '???';
COMMENT ON COLUMN BS_CERT.STATUS_ IS '????0-??????,1-?????,2-?????';
COMMENT ON COLUMN BS_CERT.CERT_CODE IS '?????';
COMMENT ON COLUMN BS_CERT.CERT_NAME IS '??????';
COMMENT ON COLUMN BS_CERT.CERT_FULL_NAME IS '??????';
COMMENT ON COLUMN BS_CERT.LICENCER IS '??????';
COMMENT ON COLUMN BS_CERT.START_DATE IS '??Ч????';
COMMENT ON COLUMN BS_CERT.ISSUE_DATE IS '???????';
COMMENT ON COLUMN BS_CERT.END_DATE IS '????????';
COMMENT ON COLUMN BS_CERT.FILE_DATE IS '???????';
COMMENT ON COLUMN BS_CERT.AUTHOR_ID IS '??????ID';
COMMENT ON COLUMN BS_CERT.MODIFIER_ID IS '????????ID';
COMMENT ON COLUMN BS_CERT.MODIFIED_DATE IS '?????????';
ALTER TABLE BS_CERT ADD CONSTRAINT BSFK_CERT_AUTHORID FOREIGN KEY (AUTHOR_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
ALTER TABLE BS_CERT ADD CONSTRAINT BSFK_CERT_MODIFIER FOREIGN KEY (MODIFIER_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
CREATE INDEX BSIDX_CERT_CODE ON BS_CERT (CERT_CODE ASC);
CREATE INDEX BSIDX_CERT_NAME ON BS_CERT (CERT_NAME ASC);

-- ???:????????
create table BS_CERT_IDENTITY (
    ID number(19) NOT NULL,
    NAME varchar2(255),
    SEX number(1),
    BIRTHDATE date,
    NATION varchar2(255),
    ADDRESS varchar2(500),
    primary key (ID)
);
COMMENT ON TABLE BS_CERT_IDENTITY IS '???:????????';
COMMENT ON COLUMN BS_CERT_IDENTITY.NAME IS '????';
COMMENT ON COLUMN BS_CERT_IDENTITY.SEX IS '???(0-δ????,1-??,2-?)';
COMMENT ON COLUMN BS_CERT_IDENTITY.BIRTHDATE IS '????????';
COMMENT ON COLUMN BS_CERT_IDENTITY.NATION IS '????';
COMMENT ON COLUMN BS_CERT_IDENTITY.ADDRESS IS '??';
ALTER TABLE BS_CERT_IDENTITY ADD CONSTRAINT BSFK_CERT4IDENTITY_CERT FOREIGN KEY (ID) 
	REFERENCES BS_CERT (ID);

-- ???:??????
create table BS_CERT_DRIVING (
    ID number(19) NOT NULL,
    NAME varchar2(255),
    SEX number(1),
    BIRTHDATE date,
    NATION varchar2(255),
    ADDRESS varchar2(500),
    MODEL varchar2(255),
    RECEIVEDATE date,
    VALIDFOR varchar2(255),
    ARCHIVENO varchar2(255),
    RECORD varchar2(255),
    primary key (ID)
);
COMMENT ON TABLE BS_CERT_DRIVING IS '???:??????';
COMMENT ON COLUMN BS_CERT_DRIVING.NAME IS '????';
COMMENT ON COLUMN BS_CERT_DRIVING.SEX IS '???(0-δ????,1-??,2-?)';
COMMENT ON COLUMN BS_CERT_DRIVING.BIRTHDATE IS '????????';
COMMENT ON COLUMN BS_CERT_DRIVING.NATION IS '??';
COMMENT ON COLUMN BS_CERT_DRIVING.ADDRESS IS '???';
COMMENT ON COLUMN BS_CERT_DRIVING.MODEL IS '??????';
COMMENT ON COLUMN BS_CERT_DRIVING.RECEIVEDATE IS '???????????';
COMMENT ON COLUMN BS_CERT_DRIVING.VALIDFOR IS '??Ч????';
COMMENT ON COLUMN BS_CERT_DRIVING.ARCHIVENO IS '???????';
COMMENT ON COLUMN BS_CERT_DRIVING.RECORD IS '???';
ALTER TABLE BS_CERT_DRIVING ADD CONSTRAINT BSFK_CERT4DRIVING_CERT FOREIGN KEY (ID) 
	REFERENCES BS_CERT (ID);

-- ???:???????
create table BS_CERT_CYZG (
    ID number(19) NOT NULL,
    NAME varchar2(255),
    SEX number(1),
    BIRTHDATE date,
    NATION varchar2(255),
    ADDRESS varchar2(500),
    SCOPE_ varchar2(255),
    IDENTITY_NO varchar2(255),
    SERVICE_UNIT varchar2(500),
    primary key (ID)
);
COMMENT ON TABLE BS_CERT_CYZG IS '???:???????';
COMMENT ON COLUMN BS_CERT_CYZG.NAME IS '????';
COMMENT ON COLUMN BS_CERT_CYZG.SEX IS '???(0-δ????,1-??,2-?)';
COMMENT ON COLUMN BS_CERT_CYZG.BIRTHDATE IS '????????';
COMMENT ON COLUMN BS_CERT_CYZG.NATION IS '??';
COMMENT ON COLUMN BS_CERT_CYZG.ADDRESS IS '???';
COMMENT ON COLUMN BS_CERT_CYZG.SCOPE_ IS '??????';
COMMENT ON COLUMN BS_CERT_CYZG.IDENTITY_NO IS '????????';
COMMENT ON COLUMN BS_CERT_CYZG.SERVICE_UNIT IS '????λ';
ALTER TABLE BS_CERT_CYZG ADD CONSTRAINT BSFK_CERT4CYZG_CERT FOREIGN KEY (ID) 
	REFERENCES BS_CERT (ID);

-- ???:????????
create table BS_CERT_FWZG (
    ID number(19) NOT NULL,
    NAME varchar2(255),
    SEX number(1),
    BIRTHDATE date,
    NATION varchar2(255),
    ADDRESS varchar2(500),
    LEVEL_ varchar2(255),
    SERVICE_UNIT varchar2(500),
    primary key (ID)
);
COMMENT ON TABLE BS_CERT_FWZG IS '???:????????';
COMMENT ON COLUMN BS_CERT_FWZG.NAME IS '????';
COMMENT ON COLUMN BS_CERT_FWZG.SEX IS '???(0-δ????,1-??,2-?)';
COMMENT ON COLUMN BS_CERT_FWZG.BIRTHDATE IS '????????';
COMMENT ON COLUMN BS_CERT_FWZG.NATION IS '??';
COMMENT ON COLUMN BS_CERT_FWZG.ADDRESS IS '???';
COMMENT ON COLUMN BS_CERT_FWZG.LEVEL_ IS '???';
COMMENT ON COLUMN BS_CERT_FWZG.SERVICE_UNIT IS '????λ';
ALTER TABLE BS_CERT_FWZG ADD CONSTRAINT BSFK_CERT4FWZG_CERT FOREIGN KEY (ID) 
	REFERENCES BS_CERT (ID);

-- ???:???????
create table BS_CERT_JSPX (
    ID number(19) NOT NULL,
    NAME varchar2(255),
    SEX number(1),
    BIRTHDATE date,
    NATION varchar2(255),
    ADDRESS varchar2(500),
    DOMAIN varchar2(255),
    TRAIN_DATE date,
    TRAIN_HOUR number(3),
    GRADE1 number(3),
    GRADE2 varchar2(10),
    GRADE3 varchar2(10),
    IDENTITY_NO varchar2(255),
    primary key (ID)
);
COMMENT ON TABLE BS_CERT_JSPX IS '???:???????';
COMMENT ON COLUMN BS_CERT_JSPX.NAME IS '????';
COMMENT ON COLUMN BS_CERT_JSPX.SEX IS '???(0-δ????,1-??,2-?)';
COMMENT ON COLUMN BS_CERT_JSPX.BIRTHDATE IS '????????';
COMMENT ON COLUMN BS_CERT_JSPX.NATION IS '??';
COMMENT ON COLUMN BS_CERT_JSPX.ADDRESS IS '???';
COMMENT ON COLUMN BS_CERT_JSPX.DOMAIN IS '?????';
COMMENT ON COLUMN BS_CERT_JSPX.TRAIN_DATE IS '??????';
COMMENT ON COLUMN BS_CERT_JSPX.TRAIN_HOUR IS '?????';
COMMENT ON COLUMN BS_CERT_JSPX.GRADE1 IS '????????????';
COMMENT ON COLUMN BS_CERT_JSPX.GRADE2 IS '?????????????';
COMMENT ON COLUMN BS_CERT_JSPX.GRADE3 IS '???????';
COMMENT ON COLUMN BS_CERT_JSPX.IDENTITY_NO IS '????????';
ALTER TABLE BS_CERT_JSPX ADD CONSTRAINT BSFK_CERT4JSPX_CERT FOREIGN KEY (ID) 
	REFERENCES BS_CERT (ID);

-- ???:??·?????
CREATE TABLE BS_CERT_ROADTRANSPORT(
	ID                   NUMBER(19) NOT NULL,
	FACTORY              VARCHAR2(255),
	PLATE                VARCHAR2(255),
	OWNER                VARCHAR2(255),
	ADDRESS              VARCHAR2(255),
	BS_CERT_NO           VARCHAR2(255),
	SEAT                 VARCHAR2(255),
	DIM_LEN              NUMBER(19),
	DIM_WIDTH            NUMBER(19),
	DIM_HEIGHT           NUMBER(19),
	SCOPE_               VARCHAR2(255),
	LEVEL_               VARCHAR2(255),
  PRIMARY KEY (ID)
);
COMMENT ON TABLE BS_CERT_ROADTRANSPORT IS '???????·?????';
COMMENT ON COLUMN BS_CERT_ROADTRANSPORT.FACTORY IS '????????硰?????SVW7182QQD??';
COMMENT ON COLUMN BS_CERT_ROADTRANSPORT.PLATE IS '??????????硰??AC4X74??';
COMMENT ON COLUMN BS_CERT_ROADTRANSPORT.OWNER IS '??????';
COMMENT ON COLUMN BS_CERT_ROADTRANSPORT.ADDRESS IS '???';
COMMENT ON COLUMN BS_CERT_ROADTRANSPORT.BS_CERT_NO IS '?????????';
COMMENT ON COLUMN BS_CERT_ROADTRANSPORT.SEAT IS '?????λ';
COMMENT ON COLUMN BS_CERT_ROADTRANSPORT.DIM_LEN IS '??????磺??????λMM';
COMMENT ON COLUMN BS_CERT_ROADTRANSPORT.DIM_WIDTH IS '??????磺????λMM';
COMMENT ON COLUMN BS_CERT_ROADTRANSPORT.DIM_HEIGHT IS '??????磺?????λMM';
COMMENT ON COLUMN BS_CERT_ROADTRANSPORT.SCOPE_ IS '?????Χ';
COMMENT ON COLUMN BS_CERT_ROADTRANSPORT.LEVEL_ IS '???????';
ALTER TABLE BS_CERT_ROADTRANSPORT ADD CONSTRAINT BSFK_CERT4ROADTRANSPORT_CERT FOREIGN KEY (ID) 
	REFERENCES BS_CERT (ID);
  
-- ???:??????
CREATE TABLE BS_CERT_VEHICELICENSE(
	ID                   NUMBER(19) NOT NULL,
	FACTORY              VARCHAR2(255),
	PLATE                VARCHAR2(255),
	OWNER                VARCHAR2(255),
	ADDRESS              VARCHAR2(255),
	USE_CHARACTER        VARCHAR2(255),
	VEHICE_TYPE          VARCHAR2(255),
	VIN                  VARCHAR2(255),
	ENGINE_NO            VARCHAR2(255),
	REGISTER_DATE        DATE,
	ARCHIVE_NO           VARCHAR2(255),
	DIM_LEN              number(19),
	DIM_WIDTH            number(19),
	DIM_HEIGHT           number(19),
	TOTAL_WEIGHT         number(19),
	CURB_WEIGHT          number(19),
	ACCESS_WEIGHT        number(19),
	ACCESS_COUNT         number(19),
	SCRAP_DATE           DATE,
	DESC_                VARCHAR2(500),
	RECORD_              VARCHAR2(500),
	PRIMARY KEY (ID)
);
COMMENT ON TABLE BS_CERT_VEHICELICENSE IS '???????????';
COMMENT ON COLUMN BS_CERT_VEHICELICENSE.FACTORY IS '????????硰?????SVW7182QQD??';
COMMENT ON COLUMN BS_CERT_VEHICELICENSE.PLATE IS '??????????硰??AC4X74??';
COMMENT ON COLUMN BS_CERT_VEHICELICENSE.OWNER IS '??????';
COMMENT ON COLUMN BS_CERT_VEHICELICENSE.ADDRESS IS '???';
COMMENT ON COLUMN BS_CERT_VEHICELICENSE.USE_CHARACTER IS '???????';
COMMENT ON COLUMN BS_CERT_VEHICELICENSE.VEHICE_TYPE IS '????????';
COMMENT ON COLUMN BS_CERT_VEHICELICENSE.VIN IS '?????????';
COMMENT ON COLUMN BS_CERT_VEHICELICENSE.ENGINE_NO IS '?????????';
COMMENT ON COLUMN BS_CERT_VEHICELICENSE.REGISTER_DATE IS '???????';
COMMENT ON COLUMN BS_CERT_VEHICELICENSE.ARCHIVE_NO IS '???????';
COMMENT ON COLUMN BS_CERT_VEHICELICENSE.DIM_LEN IS '??????磺??????λMM';
COMMENT ON COLUMN BS_CERT_VEHICELICENSE.DIM_WIDTH IS '??????磺????λMM';
COMMENT ON COLUMN BS_CERT_VEHICELICENSE.DIM_HEIGHT IS '??????磺?????λMM';
COMMENT ON COLUMN BS_CERT_VEHICELICENSE.TOTAL_WEIGHT IS '??????????λKG';
COMMENT ON COLUMN BS_CERT_VEHICELICENSE.CURB_WEIGHT IS '??????????λKG';
COMMENT ON COLUMN BS_CERT_VEHICELICENSE.ACCESS_WEIGHT IS '?????????????λKG';
COMMENT ON COLUMN BS_CERT_VEHICELICENSE.ACCESS_COUNT IS '?????????';
COMMENT ON COLUMN BS_CERT_VEHICELICENSE.SCRAP_DATE IS '??????????';
COMMENT ON COLUMN BS_CERT_VEHICELICENSE.DESC_ IS '???';
COMMENT ON COLUMN BS_CERT_VEHICELICENSE.RECORD_ IS '??????';
ALTER TABLE BS_CERT_VEHICELICENSE ADD CONSTRAINT BSFK_CERT4VEHICELICENSE_CERT FOREIGN KEY (ID) 
	REFERENCES BS_CERT (ID);


-- ?????????
create table BS_CARMAN (
    ID number(19) NOT NULL,
    UID_ varchar2(36) NOT NULL,
    STATUS_ number(1) NOT NULL,
    TYPE_ number(1) default 0 NOT NULL,
    NAME varchar2(255) NOT NULL,
    ORDER_ varchar2(100),
    SEX number(1) default 0 NOT NULL,
    WORK_DATE date,
    ORIGIN varchar2(255),
    REGION_  number(1),
    HOUSE_TYPE varchar2(255),
    BIRTHDATE date,
    FORMER_UNIT varchar2(500),
    ADDRESS varchar2(500),
    ADDRESS1 varchar2(500),
    PHONE varchar2(500),
    PHONE1 varchar2(500),
    MODEL_                VARCHAR2(255),
	LEVEL_ varchar2(255),
    CERT_IDENTITY        VARCHAR2(255),
    CERT_DRIVING         VARCHAR2(255),
    CERT_DRIVING_ARCHIVE VARCHAR2(255),
    CERT_DRIVING_FIRST_DATE DATE,
    CERT_DRIVING_START_DATE DATE,
    CERT_DRIVING_END_DATE DATE,
    CERT_FWZG            VARCHAR2(255),
    CERT_CYZG            VARCHAR2(255),
    DRIVING_STATUS        number(1),
    EXT_FZJG             VARCHAR2(255),
    EXT_ZRR              VARCHAR2(255),
    GZ                   number(1),
    ACCESS_CERTS         VARCHAR2(255),
    DESC_                VARCHAR2(4000),
    FILE_DATE date NOT NULL,
    AUTHOR_ID number(19) NOT NULL,
    MODIFIER_ID number(19),
    MODIFIED_DATE date,
    primary key (ID)
);
COMMENT ON TABLE BS_CARMAN IS '?????????';
COMMENT ON COLUMN BS_CARMAN.UID_ IS 'UID';
COMMENT ON COLUMN BS_CARMAN.STATUS_ IS '????0-??????,1-?????,2-?????';
COMMENT ON COLUMN BS_CARMAN.TYPE_ IS '???:0-???,1-??????,2-??????????';
COMMENT ON COLUMN BS_CARMAN.NAME IS '????';
COMMENT ON COLUMN BS_CARMAN.ORDER_ IS '?????';
COMMENT ON COLUMN BS_CARMAN.SEX IS '???0-δ????,1-??,2-?';
COMMENT ON COLUMN BS_CARMAN.WORK_DATE IS '???????';
COMMENT ON COLUMN BS_CARMAN.ORIGIN IS '????';
COMMENT ON COLUMN BS_CARMAN.REGION_ IS '????0-δ???壬1-???У?2-?????3-???';
COMMENT ON COLUMN BS_CARMAN.HOUSE_TYPE IS '????????';
COMMENT ON COLUMN BS_CARMAN.BIRTHDATE IS '????????';
COMMENT ON COLUMN BS_CARMAN.FORMER_UNIT IS '??????λ';
COMMENT ON COLUMN BS_CARMAN.ADDRESS IS '??????';
COMMENT ON COLUMN BS_CARMAN.ADDRESS1 IS '??????';
COMMENT ON COLUMN BS_CARMAN.PHONE IS '?绰';
COMMENT ON COLUMN BS_CARMAN.PHONE1 IS '?绰1';
COMMENT ON COLUMN BS_CARMAN.FILE_DATE IS '???????';
COMMENT ON COLUMN BS_CARMAN.AUTHOR_ID IS '??????ID';
COMMENT ON COLUMN BS_CARMAN.MODIFIER_ID IS '????????ID';
COMMENT ON COLUMN BS_CARMAN.MODIFIED_DATE IS '?????????';
COMMENT ON COLUMN BS_CARMAN.MODEL_ IS '??????';
COMMENT ON COLUMN BS_CARMAN.LEVEL_ IS '?????';
COMMENT ON COLUMN BS_CARMAN.CERT_IDENTITY IS '??????';
COMMENT ON COLUMN BS_CARMAN.CERT_DRIVING IS '??????';
COMMENT ON COLUMN BS_CARMAN.CERT_DRIVING_ARCHIVE IS '??????????';
COMMENT ON COLUMN BS_CARMAN.CERT_DRIVING_FIRST_DATE IS '???????????';
COMMENT ON COLUMN BS_CARMAN.CERT_DRIVING_START_DATE IS '??????Ч????';
COMMENT ON COLUMN BS_CARMAN.CERT_DRIVING_END_DATE IS '????????????';
COMMENT ON COLUMN BS_CARMAN.CERT_FWZG IS '??????????';
COMMENT ON COLUMN BS_CARMAN.CERT_CYZG IS '?????????';
COMMENT ON COLUMN BS_CARMAN.DRIVING_STATUS IS '???????0-δ???壬1-???2-????3-????';
COMMENT ON COLUMN BS_CARMAN.EXT_FZJG IS '???????????????????';
COMMENT ON COLUMN BS_CARMAN.EXT_ZRR IS '?????????????????????';
COMMENT ON COLUMN BS_CARMAN.GZ IS '??????????:0-??,1-??';
COMMENT ON COLUMN BS_CARMAN.ACCESS_CERTS IS '??????????????????';
COMMENT ON COLUMN BS_CARMAN.DESC_ IS '???';
ALTER TABLE BS_CARMAN ADD CONSTRAINT BSFK_CARMAN_AUTHOR FOREIGN KEY (AUTHOR_ID) 
	REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
ALTER TABLE BS_CARMAN ADD CONSTRAINT BSFK_CARMAN_MODIFIER FOREIGN KEY (MODIFIER_ID) 
	REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);

-- ???????????????????
CREATE TABLE BS_CARMAN_CERT (
    MAN_ID number(19) NOT NULL,
    CERT_ID number(19) NOT NULL,
    PRIMARY KEY (MAN_ID,CERT_ID)
);
COMMENT ON TABLE BS_CARMAN_CERT IS '???????????????????';
COMMENT ON COLUMN BS_CARMAN_CERT.MAN_ID IS '?????????ID';
COMMENT ON COLUMN BS_CARMAN_CERT.CERT_ID IS '???ID';
ALTER TABLE BS_CARMAN_CERT ADD CONSTRAINT BSFK_CARMANCERT_MAN FOREIGN KEY (MAN_ID) 
	REFERENCES BS_CARMAN (ID);
ALTER TABLE BS_CARMAN_CERT ADD CONSTRAINT BSFK_CARMANCERT_CERT FOREIGN KEY (CERT_ID) 
	REFERENCES BS_CERT (ID);


-- ???? 
CREATE TABLE BS_CAR (
   ID                   NUMBER(19)           NOT NULL,
   UID_                 VARCHAR2(36)         NOT NULL,
   STATUS_              NUMBER(1)            NOT NULL,
   UNIT_ID              NUMBER(19)           NOT NULL,
   MOTORCADE_ID         NUMBER(19)           NOT NULL,
   BS_TYPE              VARCHAR2(255),
   CODE                 VARCHAR2(255),
   ORIGIN_NO            VARCHAR2(255),
   PLATE_TYPE           VARCHAR2(255),
   PLATE_NO             VARCHAR2(255),
   VIN                  VARCHAR2(255),
   FACTORY_TYPE         VARCHAR2(255),
   FACTORY_MODEL        VARCHAR2(255),
   REGISTER_DATE        DATE,
   OPERATE_DATE         DATE,
   SCRAP_DATE           DATE,
   FACTORY_DATE         DATE,
   REGISTER_NO          VARCHAR2(255),
   LEVEL_               VARCHAR2(255),
   COLOR                VARCHAR2(255),
   RNGINE_NO            VARCHAR2(255),
   RNGINE_TYPE          VARCHAR2(255),
   FUEL_TYPE            VARCHAR2(255),
   DISPLACEMENT         NUMBER(19),
   POWER                NUMBER(19,2),
   TURN_TYPE            VARCHAR2(255),
   TIRE_COUNT           NUMBER(19),
   TIRE_STANDARD        VARCHAR2(255),
   AXIS_DISTANCE        NUMBER(19),
   AXIS_COUNT           NUMBER(19),
   PIECE_COUNT          NUMBER(19),
   DIM_LEN              NUMBER(19),
   DIM_WIDTH            NUMBER(19),
   DIM_HEIGHT           NUMBER(19),
   TOTAL_WEIGHT         NUMBER(19),
   ACCESS_WEIGHT        NUMBER(19),
   ACCESS_COUNT         NUMBER(19),
   ORIGINAL_VALUE       NUMBER(19,2),
   INVOICE_NO1          VARCHAR2(255),
   INVOICE_NO2          VARCHAR2(255),
   PAYMENT_TYPE         VARCHAR2(255),
   CERT_NO1             VARCHAR2(255),
   CERT_NO2             VARCHAR2(255),
   CERT_NO3             VARCHAR2(255),
   TAXIMETER_FACTORY    VARCHAR2(255),
   TAXIMETER_TYPE       VARCHAR2(255),
   TAXIMETER_NO         VARCHAR2(255),
   DESC1                VARCHAR2(4000),
   DESC2                VARCHAR2(4000),
   DESC3                VARCHAR2(4000),
   FILE_DATE            DATE NOT NULL,
   AUTHOR_ID            NUMBER(19) NOT NULL,
   MODIFIER_ID          NUMBER(19),
   MODIFIED_DATE        DATE,
   PRIMARY KEY (ID)
);
COMMENT ON TABLE BS_CAR IS '????';
COMMENT ON COLUMN BS_CAR.STATUS_ IS '????0-??????,1-?????,2-?????';
COMMENT ON COLUMN BS_CAR.UNIT_ID IS '??????λID';
COMMENT ON COLUMN BS_CAR.MOTORCADE_ID IS '????????ID';
COMMENT ON COLUMN BS_CAR.BS_TYPE IS '???????';
COMMENT ON COLUMN BS_CAR.CODE IS '????';
COMMENT ON COLUMN BS_CAR.ORIGIN_NO IS '?????';
COMMENT ON COLUMN BS_CAR.PLATE_TYPE IS '??????????硰??A??';
COMMENT ON COLUMN BS_CAR.PLATE_NO IS '????????硰C4X74??';
COMMENT ON COLUMN BS_CAR.VIN IS '?????????';
COMMENT ON COLUMN BS_CAR.FACTORY_TYPE IS '??????????硰????ɡ?';
COMMENT ON COLUMN BS_CAR.FACTORY_MODEL IS '?????????硰SVW7182QQD??';
COMMENT ON COLUMN BS_CAR.REGISTER_DATE IS '???????';
COMMENT ON COLUMN BS_CAR.OPERATE_DATE IS '???????';
COMMENT ON COLUMN BS_CAR.SCRAP_DATE IS '????????';
COMMENT ON COLUMN BS_CAR.FACTORY_DATE IS '????????';
COMMENT ON COLUMN BS_CAR.REGISTER_NO IS '???????';
COMMENT ON COLUMN BS_CAR.LEVEL_ IS '????????';
COMMENT ON COLUMN BS_CAR.COLOR IS '???';
COMMENT ON COLUMN BS_CAR.RNGINE_NO IS '?????????';
COMMENT ON COLUMN BS_CAR.RNGINE_TYPE IS '??????????';
COMMENT ON COLUMN BS_CAR.FUEL_TYPE IS '?????????硰?????';
COMMENT ON COLUMN BS_CAR.DISPLACEMENT IS '????????λML';
COMMENT ON COLUMN BS_CAR.POWER IS '???????λKW';
COMMENT ON COLUMN BS_CAR.TURN_TYPE IS '???????硰???????';
COMMENT ON COLUMN BS_CAR.TIRE_COUNT IS '?????';
COMMENT ON COLUMN BS_CAR.TIRE_STANDARD IS '??????';
COMMENT ON COLUMN BS_CAR.AXIS_DISTANCE IS '???';
COMMENT ON COLUMN BS_CAR.AXIS_COUNT IS '????';
COMMENT ON COLUMN BS_CAR.PIECE_COUNT IS '?????嵯?????';
COMMENT ON COLUMN BS_CAR.DIM_LEN IS '??????磺??????λMM';
COMMENT ON COLUMN BS_CAR.DIM_WIDTH IS '??????磺????λMM';
COMMENT ON COLUMN BS_CAR.DIM_HEIGHT IS '??????磺?????λMM';
COMMENT ON COLUMN BS_CAR.TOTAL_WEIGHT IS '??????????λKG';
COMMENT ON COLUMN BS_CAR.ACCESS_WEIGHT IS '?????????????λKG';
COMMENT ON COLUMN BS_CAR.ACCESS_COUNT IS '?????????';
COMMENT ON COLUMN BS_CAR.ORIGINAL_VALUE IS '????????????λ?';
COMMENT ON COLUMN BS_CAR.INVOICE_NO1 IS '?????????';
COMMENT ON COLUMN BS_CAR.INVOICE_NO2 IS '??????????';
COMMENT ON COLUMN BS_CAR.PAYMENT_TYPE IS '?????';
COMMENT ON COLUMN BS_CAR.CERT_NO1 IS '????????';
COMMENT ON COLUMN BS_CAR.CERT_NO2 IS '??????????';
COMMENT ON COLUMN BS_CAR.CERT_NO3 IS '??????';
COMMENT ON COLUMN BS_CAR.TAXIMETER_FACTORY IS '?????????';
COMMENT ON COLUMN BS_CAR.TAXIMETER_TYPE IS '????????';
COMMENT ON COLUMN BS_CAR.TAXIMETER_NO IS '????????????';
COMMENT ON COLUMN BS_CAR.DESC1 IS '???1';
COMMENT ON COLUMN BS_CAR.DESC2 IS '???2';
COMMENT ON COLUMN BS_CAR.DESC3 IS '???3';
COMMENT ON COLUMN BS_CAR.FILE_DATE IS '???????';
COMMENT ON COLUMN BS_CAR.AUTHOR_ID IS '??????ID';
COMMENT ON COLUMN BS_CAR.MODIFIER_ID IS '????????ID';
COMMENT ON COLUMN BS_CAR.MODIFIED_DATE IS '?????????';
ALTER TABLE BS_CAR ADD CONSTRAINT BSFK_CAR_AUTHOR FOREIGN KEY (AUTHOR_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
ALTER TABLE BS_CAR ADD CONSTRAINT BSFK_CAR_MODIFIER FOREIGN KEY (MODIFIER_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
ALTER TABLE BS_CAR ADD CONSTRAINT BSFK_CAR_MOTORCADEID FOREIGN KEY (MOTORCADE_ID)
      REFERENCES BS_MOTORCADE (ID);
ALTER TABLE BS_CAR ADD CONSTRAINT BSFK_CAR_UNITID FOREIGN KEY (UNIT_ID)
      REFERENCES BC_IDENTITY_ACTOR (ID);

-- ??????????????
CREATE TABLE BS_CAR_CERT (
    CAR_ID number(19) NOT NULL,
    CERT_ID number(19) NOT NULL,
    PRIMARY KEY (CAR_ID,CERT_ID)
);
COMMENT ON TABLE BS_CAR_CERT IS '??????????????';
COMMENT ON COLUMN BS_CAR_CERT.CAR_ID IS '????ID';
COMMENT ON COLUMN BS_CAR_CERT.CERT_ID IS '???ID';
ALTER TABLE BS_CAR_CERT ADD CONSTRAINT BSFK_CARCERT_CAR FOREIGN KEY (CAR_ID) 
	REFERENCES BS_CAR (ID);
ALTER TABLE BS_CAR_CERT ADD CONSTRAINT BSFK_CARCERT_CERT FOREIGN KEY (CERT_ID) 
	REFERENCES BS_CERT (ID);


-- ???
CREATE TABLE BS_CONTRACT (
   ID                   NUMBER(19)           NOT NULL,
   UID_                 VARCHAR2(36)         NOT NULL,
   STATUS_              NUMBER(1)            NOT NULL,
   WORD_NO              VARCHAR2(255),
   CODE                 VARCHAR2(255)        NOT NULL,
   TYPE_                NUMBER(1)	     NOT NULL,
   TRANSACTOR_ID        NUMBER(19)           NOT NULL,
   SIGN_DATE            DATE                 NOT NULL,
   START_DATE           DATE                 NOT NULL,
   END_DATE             DATE                 NOT NULL,
   CONTENT              VARCHAR2(4000),
   EXT_STR1             VARCHAR2(255),
   EXT_STR2             VARCHAR2(255),
   EXT_STR3             VARCHAR2(255),
   EXT_NUM1             NUMBER(19),
   EXT_NUM2             NUMBER(19),
   EXT_NUM3             NUMBER(19),
   FILE_DATE            DATE                 NOT NULL,
   AUTHOR_ID            NUMBER(19)           NOT NULL,
   MODIFIER_ID          NUMBER(19),
   MODIFIED_DATE        DATE,
   PRIMARY KEY (ID)
);
COMMENT ON TABLE BS_CONTRACT IS '???';
COMMENT ON COLUMN BS_CONTRACT.STATUS_ IS '????0-??????,1-?????,2-?????';
COMMENT ON COLUMN BS_CONTRACT.WORD_NO IS '?????';
COMMENT ON COLUMN BS_CONTRACT.CODE IS '?????';
COMMENT ON COLUMN BS_CONTRACT.TYPE_ IS '???????????????????а?????';
COMMENT ON COLUMN BS_CONTRACT.TRANSACTOR_ID IS '??????ID';
COMMENT ON COLUMN BS_CONTRACT.SIGN_DATE IS '???????';
COMMENT ON COLUMN BS_CONTRACT.START_DATE IS '??Ч????';
COMMENT ON COLUMN BS_CONTRACT.END_DATE IS '????????';
COMMENT ON COLUMN BS_CONTRACT.CONTENT IS '???????';
COMMENT ON COLUMN BS_CONTRACT.EXT_STR1 IS '????????1';
COMMENT ON COLUMN BS_CONTRACT.EXT_STR2 IS '????????2';
COMMENT ON COLUMN BS_CONTRACT.EXT_STR3 IS '????????3';
COMMENT ON COLUMN BS_CONTRACT.EXT_NUM1 IS '?????????1';
COMMENT ON COLUMN BS_CONTRACT.EXT_NUM2 IS '?????????2';
COMMENT ON COLUMN BS_CONTRACT.EXT_NUM3 IS '?????????3';
COMMENT ON COLUMN BS_CONTRACT.FILE_DATE IS '???????';
COMMENT ON COLUMN BS_CONTRACT.AUTHOR_ID IS '??????ID';
COMMENT ON COLUMN BS_CONTRACT.MODIFIER_ID IS '????????ID';
COMMENT ON COLUMN BS_CONTRACT.MODIFIED_DATE IS '?????????';
ALTER TABLE BS_CONTRACT ADD CONSTRAINT BSFK_CONTRACT_AUTHOR FOREIGN KEY (AUTHOR_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
ALTER TABLE BS_CONTRACT ADD CONSTRAINT BSFK_CONTRACT_MODIFIER FOREIGN KEY (MODIFIER_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);

-- ?????????
CREATE TABLE BS_CONTRACT_LABOUR (
   ID                   NUMBER(19)           NOT NULL,
   DRIVER_ID            NUMBER(19)           NOT NULL,
   CAR_ID               NUMBER(19)           NOT NULL,
   ADDITION_PROTOCOL    NUMBER(1)            NOT NULL,
   PRE_INDUSTRY_NAME    VARCHAR2(255),
   PRE_INDUSTRY_TYPE    NUMBER(1)            NOT NULL,
   HIRING_PROCEDURE     NUMBER(1)            NOT NULL,
   DOLE                 NUMBER(1)            NOT NULL,
   FILING               NUMBER(1)            NOT NULL,
   CERT_NO              VARCHAR2(255)        NOT NULL,
   CONSTRAINT PK_BS_CONTRACT_LABOUR PRIMARY KEY (ID)
);
COMMENT ON TABLE BS_CONTRACT_LABOUR IS '?????????';
COMMENT ON COLUMN BS_CONTRACT_LABOUR.DRIVER_ID IS '???ID';
COMMENT ON COLUMN BS_CONTRACT_LABOUR.CAR_ID IS '????ID';
COMMENT ON COLUMN BS_CONTRACT_LABOUR.ADDITION_PROTOCOL IS '????Э??:0-??,1-??';
COMMENT ON COLUMN BS_CONTRACT_LABOUR.PRE_INDUSTRY_NAME IS '?????????';
COMMENT ON COLUMN BS_CONTRACT_LABOUR.PRE_INDUSTRY_TYPE IS '????????:0-??????,1-????';
COMMENT ON COLUMN BS_CONTRACT_LABOUR.HIRING_PROCEDURE IS '???ù?????:0-δ??,1-???';
COMMENT ON COLUMN BS_CONTRACT_LABOUR.DOLE IS '?????????:0-???,1-δ??';
COMMENT ON COLUMN BS_CONTRACT_LABOUR.FILING IS '????????';
COMMENT ON COLUMN BS_CONTRACT_LABOUR.CERT_NO IS '??????';
ALTER TABLE BS_CONTRACT_LABOUR ADD CONSTRAINT BSFK_CONTRACT4LABOUR_CAR FOREIGN KEY (CAR_ID)
      REFERENCES BS_CAR (ID);
ALTER TABLE BS_CONTRACT_LABOUR ADD CONSTRAINT BSFK_CONTRACT4LABOUR_CARMAN FOREIGN KEY (DRIVER_ID)
      REFERENCES BS_CARMAN (ID);
ALTER TABLE BS_CONTRACT_LABOUR ADD CONSTRAINT BSFK_CONTRACT4LABOUR_CONTRACT FOREIGN KEY (ID)
      REFERENCES BS_CONTRACT (ID);

-- ????????
CREATE TABLE BS_CONTRACT_CHARGER (
   ID                   NUMBER(19)           NOT NULL,
   CAR_ID               NUMBER(19)           NOT NULL,
   SIGN_TYPE            VARCHAR2(255)        NOT NULL,
   LOGOUT               NUMBER(1)            NOT NULL,
   TAKEBACK_ORIGIN      NUMBER(1)            NOT NULL,
   INCLUDE_COST         NUMBER(1)            NOT NULL,
   BS_TYPE		VARCHAR2(255)	     NOT NULL,
   OLD_CONTENT          VARCHAR2(4000),
   CONSTRAINT PK_BS_CONTRACT_CHARGER PRIMARY KEY (ID)
);
COMMENT ON TABLE BS_CONTRACT_CHARGER IS '责任人合同:如承包合同';
COMMENT ON COLUMN BS_CONTRACT_CHARGER.CAR_ID IS '车辆ID';
COMMENT ON COLUMN BS_CONTRACT_CHARGER.SIGN_TYPE IS '签约类型:如新户';
COMMENT ON COLUMN BS_CONTRACT_CHARGER.LOGOUT IS '注销:0-未,1-已';
COMMENT ON COLUMN BS_CONTRACT_CHARGER.TAKEBACK_ORIGIN IS '已经收回原件:0-未1-已';
COMMENT ON COLUMN BS_CONTRACT_CHARGER.INCLUDE_COST IS '包含检审费用:0-不包含,1-包含';
COMMENT ON COLUMN BS_CONTRACT_CHARGER.BS_TYPE IS '合同性质';
COMMENT ON COLUMN BS_CONTRACT_CHARGER.OLD_CONTENT IS '旧合同内容';
ALTER TABLE BS_CONTRACT_CHARGER ADD CONSTRAINT BSFK_CONTRACT4CHARGER_CAR FOREIGN KEY (CAR_ID)
      REFERENCES BS_CAR (ID);
ALTER TABLE BS_CONTRACT_CHARGER ADD CONSTRAINT BSFK_CONTRACT4CHARGER_CONTRACT FOREIGN KEY (ID)
      REFERENCES BS_CONTRACT (ID);

-- ???????????????
CREATE TABLE BS_CARMAN_CONTRACT (
   CONTRACT_ID          NUMBER(19)           NOT NULL,
   CARMAN_ID            NUMBER(19)           NOT NULL,
   CONSTRAINT PK_BS_CARMAN_CONTRACT PRIMARY KEY (CARMAN_ID, CONTRACT_ID)
);
COMMENT ON TABLE BS_CARMAN_CONTRACT IS '???????????????';
COMMENT ON COLUMN BS_CARMAN_CONTRACT.CONTRACT_ID IS '???ID';
COMMENT ON COLUMN BS_CARMAN_CONTRACT.CARMAN_ID IS '??????ID';
ALTER TABLE BS_CARMAN_CONTRACT ADD CONSTRAINT BSFK_CARMANCONTRACT_CARMAN FOREIGN KEY (CARMAN_ID)
      REFERENCES BS_CARMAN (ID);
ALTER TABLE BS_CARMAN_CONTRACT ADD CONSTRAINT BSFK_CARMANCONTRACT_CONTRACT FOREIGN KEY (CONTRACT_ID)
      REFERENCES BS_CONTRACT_CHARGER (ID);

-- ?????????
CREATE TABLE BS_CAR_DRIVER (
   ID                   NUMBER(19)           NOT NULL,
   STATUS_              NUMBER(1)            NOT NULL,
   DRIVER_ID            NUMBER(19)           NOT NULL,
   CAR_ID               NUMBER(19)           NOT NULL,
   CLASSES              NUMBER(1)            NOT NULL,
   START_DATE           DATE,
   END_DATE             DATE,
   FILE_DATE            DATE                 NOT NULL,
   AUTHOR_ID            NUMBER(19)           NOT NULL,
   MODIFIED_DATE        DATE,
   MODIFIER_ID          NUMBER(19),
   DESC_                VARCHAR2(4000),
  CONSTRAINT PK_BS_CAR_DRIVER PRIMARY KEY (ID)
);
COMMENT ON TABLE BS_CAR_DRIVER IS '?????????';
COMMENT ON COLUMN BS_CAR_DRIVER.STATUS_ IS '????0-??????,1-?????,2-?????';
COMMENT ON COLUMN BS_CAR_DRIVER.DRIVER_ID IS '???ID';
COMMENT ON COLUMN BS_CAR_DRIVER.CAR_ID IS '????ID';
COMMENT ON COLUMN BS_CAR_DRIVER.CLASSES IS '?????:??0-δ???壬1-???2-????3-????';
COMMENT ON COLUMN BS_CAR_DRIVER.START_DATE IS '??????';
COMMENT ON COLUMN BS_CAR_DRIVER.END_DATE IS '???????';
COMMENT ON COLUMN BS_CAR_DRIVER.FILE_DATE IS '???????';
COMMENT ON COLUMN BS_CAR_DRIVER.AUTHOR_ID IS '??????ID';
COMMENT ON COLUMN BS_CAR_DRIVER.MODIFIED_DATE IS '?????????';
COMMENT ON COLUMN BS_CAR_DRIVER.MODIFIER_ID IS '????????ID';
COMMENT ON COLUMN BS_CAR_DRIVER.DESC_ IS '???';
ALTER TABLE BS_CAR_DRIVER ADD CONSTRAINT BSFK_CARDRIVER_AUTHOR FOREIGN KEY (AUTHOR_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
ALTER TABLE BS_CAR_DRIVER ADD CONSTRAINT BSFK_CARDRIVER_MODIFIER FOREIGN KEY (MODIFIER_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
ALTER TABLE BS_CAR_DRIVER ADD CONSTRAINT BSFK_CARDRIVER_CAR FOREIGN KEY (CAR_ID)
      REFERENCES BS_CAR (ID);
ALTER TABLE BS_CAR_DRIVER ADD CONSTRAINT BSFK_CARDRIVER_CARMAN FOREIGN KEY (DRIVER_ID)
      REFERENCES BS_CARMAN (ID);
      
-- ?????????
CREATE TABLE BS_CARMAN_HISTORY (
   ID                   NUMBER(19)           NOT NULL,
   TYPE_                VARCHAR2(255)        NOT NULL,
   DRIVER_ID            NUMBER(19)           NOT NULL,
   SUBJECT              VARCHAR2(1000),
   FROM_CARID           NUMBER(19),
   TO_CARID             NUMBER(19)           NOT NULL,
   FROM_CLASSES         VARCHAR2(255),
   TO_CLASSES           VARCHAR2(255)        NOT NULL,
   SHIFT_DATE           DATE                 NOT NULL,
   FROM_MOTORCADEID     NUMBER(19),
   TO_MOTORCADEID       NUMBER(19)           NOT NULL,
   FILE_DATE            DATE                 NOT NULL,
   AUTHOR_ID            NUMBER(19)           NOT NULL,
   MODIFIED_DATE        DATE,
   MODIFIER_ID          NUMBER(19),
   CONSTRAINT PK_BS_CARMAN_HISTORY PRIMARY KEY (ID)
);
COMMENT ON TABLE BS_CARMAN_HISTORY IS '?????????';
COMMENT ON COLUMN BS_CARMAN_HISTORY.TYPE_ IS '???????????????';
COMMENT ON COLUMN BS_CARMAN_HISTORY.DRIVER_ID IS '???ID';
COMMENT ON COLUMN BS_CARMAN_HISTORY.SUBJECT IS '????';
COMMENT ON COLUMN BS_CARMAN_HISTORY.FROM_CARID IS '??????ID';
COMMENT ON COLUMN BS_CARMAN_HISTORY.TO_CARID IS '?????ID';
COMMENT ON COLUMN BS_CARMAN_HISTORY.FROM_CLASSES IS '??????:?????????????';
COMMENT ON COLUMN BS_CARMAN_HISTORY.TO_CLASSES IS '???????:?????????????';
COMMENT ON COLUMN BS_CARMAN_HISTORY.SHIFT_DATE IS '???????';
COMMENT ON COLUMN BS_CARMAN_HISTORY.FROM_MOTORCADEID IS '?????ID';
COMMENT ON COLUMN BS_CARMAN_HISTORY.TO_MOTORCADEID IS '????ID';
COMMENT ON COLUMN BS_CARMAN_HISTORY.FILE_DATE IS '???????';
COMMENT ON COLUMN BS_CARMAN_HISTORY.AUTHOR_ID IS '??????ID';
COMMENT ON COLUMN BS_CARMAN_HISTORY.MODIFIED_DATE IS '?????????';
COMMENT ON COLUMN BS_CARMAN_HISTORY.MODIFIER_ID IS '????????ID';
ALTER TABLE BS_CARMAN_HISTORY ADD CONSTRAINT BS_CARMANHISTORY_DRIVER FOREIGN KEY (DRIVER_ID)
      REFERENCES BS_CARMAN (ID);
ALTER TABLE BS_CARMAN_HISTORY ADD CONSTRAINT BS_CARMANHISTORY_FROMCAR FOREIGN KEY (FROM_CARID)
      REFERENCES BS_CAR (ID);
ALTER TABLE BS_CARMAN_HISTORY ADD CONSTRAINT BS_CARMANHISTORY_TOCAR FOREIGN KEY (TO_CARID)
      REFERENCES BS_CAR (ID);
ALTER TABLE BS_CARMAN_HISTORY ADD CONSTRAINT BS_CARMANHISTORY_FROMMOTORCADE FOREIGN KEY (FROM_MOTORCADEID)
      REFERENCES BS_MOTORCADE (ID);
ALTER TABLE BS_CARMAN_HISTORY ADD CONSTRAINT BS_CARMANHISTORY_TOMOTORCADE FOREIGN KEY (TO_MOTORCADEID)
      REFERENCES BS_MOTORCADE (ID);
ALTER TABLE BS_CARMAN_HISTORY ADD CONSTRAINT BSFK_CARMANHISTORY_AUTHOR FOREIGN KEY (AUTHOR_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
ALTER TABLE BS_CARMAN_HISTORY ADD CONSTRAINT BSFK_CARMANHISTORY_MODIFIER FOREIGN KEY (MODIFIER_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);

-- ????ALTER TABLE BS_BLACKLIST
CREATE TABLE BS_BLACKLIST (
   ID                   NUMBER(19)           NOT NULL,
   TYPE_                VARCHAR2(255)        NOT NULL,
   UNIT_ID              number(19),
   DRIVER_ID            NUMBER(19)           NOT NULL,
   CAR_ID               NUMBER(19)           NOT NULL,
   MOTORCADE_ID         NUMBER(19),
   SUBJECT              VARCHAR2(1000)       NOT NULL,
   LOCK_DATE            DATE                 NOT NULL,
   UNLOCK_DATE          DATE,
   LOCKER_ID            NUMBER(19)           NOT NULL,
   UNLOCKER_ID          NUMBER(19),
   LOCK_REASON          VARCHAR2(4000),
   UNLOCK_REASON        VARCHAR2(4000),
   LEVEL_               VARCHAR2(255),
   CODE                 VARCHAR2(255),
   FILE_DATE            DATE                 NOT NULL,
   AUTHOR_ID            NUMBER(19)           NOT NULL,
   MODIFIED_DATE        DATE,
   MODIFIER_ID          NUMBER(19),
   CONSTRAINT PK_BS_BLACKLIST PRIMARY KEY (ID)
);
COMMENT ON TABLE BS_BLACKLIST IS '????';
COMMENT ON COLUMN BS_BLACKLIST.TYPE_ IS '???????';
COMMENT ON COLUMN BS_BLACKLIST.UNIT_ID IS '??????λID';
COMMENT ON COLUMN BS_BLACKLIST.DRIVER_ID IS '???ID';
COMMENT ON COLUMN BS_BLACKLIST.CAR_ID IS '????ID';
COMMENT ON COLUMN BS_BLACKLIST.MOTORCADE_ID IS '????ID';
COMMENT ON COLUMN BS_BLACKLIST.SUBJECT IS '????';
COMMENT ON COLUMN BS_BLACKLIST.LOCK_DATE IS '?????';
COMMENT ON COLUMN BS_BLACKLIST.UNLOCK_DATE IS '???????';
COMMENT ON COLUMN BS_BLACKLIST.LOCKER_ID IS '????ID';
COMMENT ON COLUMN BS_BLACKLIST.UNLOCKER_ID IS '??????ID';
COMMENT ON COLUMN BS_BLACKLIST.LOCK_REASON IS '?????';
COMMENT ON COLUMN BS_BLACKLIST.UNLOCK_REASON IS '???????';
COMMENT ON COLUMN BS_BLACKLIST.LEVEL_ IS '???';
COMMENT ON COLUMN BS_BLACKLIST.CODE IS '???';
COMMENT ON COLUMN BS_BLACKLIST.FILE_DATE IS '???????';
COMMENT ON COLUMN BS_BLACKLIST.AUTHOR_ID IS '??????ID';
COMMENT ON COLUMN BS_BLACKLIST.MODIFIED_DATE IS '?????????';
COMMENT ON COLUMN BS_BLACKLIST.MODIFIER_ID IS '????????ID';
ALTER TABLE BS_BLACKLIST ADD CONSTRAINT BS_BLACKLIST_AUTHOR FOREIGN KEY (AUTHOR_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
ALTER TABLE BS_BLACKLIST ADD CONSTRAINT BS_BLACKLIST_MODIFIER FOREIGN KEY (MODIFIER_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
ALTER TABLE BS_BLACKLIST ADD CONSTRAINT BS_BLACKLIST_UNIT FOREIGN KEY (UNIT_ID)
      REFERENCES BC_IDENTITY_ACTOR (ID);
ALTER TABLE BS_BLACKLIST ADD CONSTRAINT BS_BLACKLIST_MOTORCADE FOREIGN KEY (MOTORCADE_ID)
      REFERENCES BS_MOTORCADE (ID);
ALTER TABLE BS_BLACKLIST ADD CONSTRAINT BS_BLACKLIST_CAR FOREIGN KEY (CAR_ID)
      REFERENCES BS_CAR (ID);
ALTER TABLE BS_BLACKLIST ADD CONSTRAINT BS_BLACKLIST_DIRVER FOREIGN KEY (DRIVER_ID)
      REFERENCES BS_CARMAN (ID);
ALTER TABLE BS_BLACKLIST ADD CONSTRAINT BS_BLACKLIST_LOCKER FOREIGN KEY (LOCKER_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
ALTER TABLE BS_BLACKLIST ADD CONSTRAINT BS_BLACKLIST_UNLOCKER FOREIGN KEY (UNLOCKER_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);