-- ##bc营运管理子系统的 oracle 删表脚本##
-- ##运行此脚本之后再运行平台的删表脚本framework.db.oracle.drop.sql##

-- 车辆与证件的关联
CALL DROP_USER_TABLE('BS_CAR_CERT');

-- 车辆
CALL DROP_USER_TABLE('BS_CAR');

-- 车队历史车辆数
CALL DROP_USER_TABLE('BS_MOTORCADE_CARQUANTITY');

-- 车队
CALL DROP_USER_TABLE('BS_MOTORCADE');

-- 司机责任人与证件的关联
CALL DROP_USER_TABLE('BS_CARMAN_CERT');

-- 证件
CALL DROP_USER_TABLE('BS_CERT_IDENTITY');
CALL DROP_USER_TABLE('BS_CERT_DRIVING');
CALL DROP_USER_TABLE('BS_CERT_CYZG');
CALL DROP_USER_TABLE('BS_CERT_FWZG');
CALL DROP_USER_TABLE('BS_CERT_JSPX');
CALL DROP_USER_TABLE('BS_CERT_ROADTRANSPORT');
CALL DROP_USER_TABLE('BS_CERT_VEHICELICENSE');
CALL DROP_USER_TABLE('BS_CERT');

-- 司机责任人
CALL DROP_USER_TABLE('BS_CARMAN');
