-- 数据转换记录
CREATE TABLE DC_RECORD(
  TYPE_         VARCHAR(255) NOT NULL COMMENT '类型',
  FROM_ID       BIGINT NOT NULL COMMENT '旧表数据ID',
  TO_ID         BIGINT NOT NULL COMMENT '新表数据的ID',
  FROM_TABLE    VARCHAR(255) COMMENT '旧数据表名',
  TO_TABLE      VARCHAR(255) COMMENT '新数据表名',
  CREATE_DATE   DATETIME NOT NULL COMMENT '创建时间',
  REMARK        VARCHAR(4000) COMMENT '备注说明',
  MODIFIED_DATE DATETIME COMMENT '最后修改时间'
) COMMENT '数据转换记录';
ALTER TABLE DC_RECORD ADD CONSTRAINT BSUK_RECORD UNIQUE (TYPE_, FROM_ID);


-- bc营运管理子系统的建表脚本,所有表名须附带前缀"BS_"
-- 运行此脚本之前需先运行平台的建表脚本framework.db.mysql.create.sql

-- 车队信息
CREATE TABLE BS_MOTORCADE(
   ID                   BIGINT NOT NULL auto_increment,
   UID_                 VARCHAR(36),
   CODE                 VARCHAR(255) COMMENT '编码',
   NAME                 VARCHAR(255) NOT NULL COMMENT '简称',
   STATUS_              INT(1) NOT NULL COMMENT '状态：0-已禁用,1-启用中,2-已删除',
   UNIT_ID              BIGINT          NOT NULL COMMENT '所属单位ID', 
   PRINCIPAL_ID         BIGINT  COMMENT '负责人ID',
   PRINCIPAL_NAME       VARCHAR(255) COMMENT '负责人姓名', 
   TYPE_                int(1)     NOT NULL COMMENT '类别：0-分队,1-分组',
   PID                  BIGINT COMMENT '所属父类ID',
   DESC_                VARCHAR(4000) COMMENT '备注',
   PAYMENT_DATE         VARCHAR(255) COMMENT '缴费日期',
   COLOR                VARCHAR(255) COMMENT '颜色',
   ADDRESS              VARCHAR(255) COMMENT '地址',
   PHONE                VARCHAR(255) COMMENT '电话',
   FAX                  VARCHAR(255) COMMENT '传真',
   FILE_DATE            DATETIME NOT NULL COMMENT '创建时间',
   AUTHOR_ID            BIGINT NOT NULL COMMENT '创建人ID',
   MODIFIER_ID          BIGINT COMMENT '最后修改人ID',
   MODIFIED_DATE        DATETIME COMMENT '最后修改时间',
   PRIMARY KEY (ID)
) COMMENT '车队信息';
ALTER TABLE BS_MOTORCADE ADD CONSTRAINT BSFK_MOTORCADE_AUTHORID FOREIGN KEY (AUTHOR_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
ALTER TABLE BS_MOTORCADE ADD CONSTRAINT BSFK_MOTORCADE_MODIFIER FOREIGN KEY (MODIFIER_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
ALTER TABLE BS_MOTORCADE ADD CONSTRAINT BSFK_MOTORCADE_PID FOREIGN KEY (PID)
      REFERENCES BS_MOTORCADE (ID);
ALTER TABLE BS_MOTORCADE ADD CONSTRAINT BSFK_MOTORCADE_PRINCIPAL FOREIGN KEY (PRINCIPAL_ID)
      REFERENCES BC_IDENTITY_ACTOR (ID);
ALTER TABLE BS_MOTORCADE ADD CONSTRAINT BSFK_MOTORCADE_UNIT FOREIGN KEY (UNIT_ID)
      REFERENCES BC_IDENTITY_ACTOR (ID);
CREATE INDEX BSIDX_MOTORCADE_STATUS ON BS_MOTORCADE (STATUS_);

-- 车队历史车辆数
CREATE TABLE BS_MOTORCADE_CARQUANTITY(
   ID                   BIGINT NOT NULL auto_increment,
   MOTORCADE_ID         BIGINT NOT NULL COMMENT '所属车队ID',
   YEAR_                DECIMAL(4,0) NOT NULL COMMENT '年份',
   MONTH_               DECIMAL(2,0) NOT NULL COMMENT '月份',
   QUANTITY             BIGINT NOT NULL COMMENT '车辆数',
   FILE_DATE            DATETIME NOT NULL COMMENT '创建时间',
   AUTHOR_ID            BIGINT NOT NULL COMMENT '创建人ID',
   MODIFIER_ID          BIGINT COMMENT '最后修改人ID',
   MODIFIED_DATE        DATETIME COMMENT '最后修改时间',
   PRIMARY KEY (ID)
) COMMENT '车队历史车辆数';
ALTER TABLE BS_MOTORCADE_CARQUANTITY ADD CONSTRAINT BSFK_CARQUANTITY_AUTHOR FOREIGN KEY (AUTHOR_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
ALTER TABLE BS_MOTORCADE_CARQUANTITY ADD CONSTRAINT BSFK_CARQUANTITY_MODIFIER FOREIGN KEY (MODIFIER_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
ALTER TABLE BS_MOTORCADE_CARQUANTITY ADD CONSTRAINT BSFK_CARQUANTITY_MOTORCADE FOREIGN KEY (MOTORCADE_ID)
      REFERENCES BS_MOTORCADE (ID);


-- 车队负责人信息
create table BS_CHARGER (
    ID BIGINT NOT NULL auto_increment,
    UID_ varchar(36) NOT NULL  COMMENT '关联附件的标识号',
    CARD varchar(255)  COMMENT '身份证',
    NAME varchar(255) NOT NULL COMMENT '姓名',
    SEX varchar(100)  COMMENT '性别',
    IDADDRESS varchar(255)  COMMENT '身份证地址',
    TWIC varchar(255)  COMMENT '资格证',
    BRITHDATE datetime COMMENT '出生日期',
    PHONE varchar(255)  COMMENT '电话',
    ORDERID varchar(255)  COMMENT '排序号',
    UNIT varchar(255)  COMMENT '分支机构',
    AREA varchar(255)  COMMENT '区域',
    TEMPORARYADDRESS varchar(255)  COMMENT '暂住地址',
    NATIVEPLACE varchar(255)  COMMENT '籍贯',
    DESC_ text COMMENT '备注',
   
    FILE_DATE datetime NOT NULL COMMENT '创建时间',
    AUTHOR_ID BIGINT NOT NULL COMMENT '创建人ID',
    MODIFIER_ID BIGINT COMMENT '最后修改人ID',
    MODIFIED_DATE datetime COMMENT '最后修改时间',
    STATUS_ int(1)  COMMENT '状态：0-已禁用,1-启用中,2-已删除',
    
    primary key (ID)
) COMMENT='车队负责人信息';
ALTER TABLE BS_CHARGER ADD CONSTRAINT BS_CHARGER_AUTHOR FOREIGN KEY (AUTHOR_ID) 
	REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
	

-- 证件
create table BS_CERT (
    ID BIGINT NOT NULL auto_increment,
    STATUS_ int(1) NOT NULL COMMENT '状态：0-已禁用,1-启用中,2-已删除',
    UID_ varchar(36) NOT NULL,
    TYPE_ int(1) NOT NULL COMMENT '证件类型：居民身份证、机动车驾驶证、从业资格证、服务资格证、驾驶培训证、机动车行驶证、道路运输证',
    CERT_CODE varchar(255) NOT NULL COMMENT '证件号',
    CERT_NAME varchar(255) NOT NULL COMMENT '证件简称',
    CERT_FULL_NAME varchar(255) COMMENT '证件全称',
    LICENCER varchar(255) COMMENT '发证机关',
    ISSUE_DATE datetime COMMENT '发证日期',
    START_DATE datetime COMMENT '生效日期',
    END_DATE datetime COMMENT '到期日期',
    EXT_STR1 varchar(255),
    EXT_STR2 varchar(255),
    EXT_STR3 varchar(255),
    EXT_NUM1 int(19),
    EXT_NUM2 int(19),
    EXT_NUM3 int(19),
    
    FILE_DATE datetime NOT NULL COMMENT '创建时间',
    AUTHOR_ID BIGINT NOT NULL COMMENT '创建人ID',
    MODIFIER_ID BIGINT COMMENT '最后修改人ID',
    MODIFIED_DATE datetime COMMENT '最后修改时间',
    primary key (ID)
) COMMENT='证件';
ALTER TABLE BS_CERT ADD CONSTRAINT BS_CERT_AUTHOR FOREIGN KEY (AUTHOR_ID) 
	REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
ALTER TABLE BS_CERT ADD CONSTRAINT BS_CERT_MODIFIER FOREIGN KEY (MODIFIER_ID) 
	REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
ALTER TABLE BS_CERT ADD INDEX BSIDX_CERT_CODE (CERT_CODE);
ALTER TABLE BS_CERT ADD INDEX BSIDX_CERT_NAME (CERT_NAME);

-- 证件:居民身份证
create table BS_CERT_IDENTITY (
    ID BIGINT NOT NULL,
    NAME varchar(255) COMMENT '姓名',
    SEX int(1) COMMENT '性别(0-未设置,1-男,2-女)',
    BIRTHDATE datetime COMMENT '出生日期',
    NATION varchar(255) COMMENT '民族',
    ADDRESS varchar(500) COMMENT '住址',
    primary key (ID)
) COMMENT='证件:居民身份证';
ALTER TABLE BS_CERT_IDENTITY ADD CONSTRAINT BSFK_CERT4IDENTITY_CERT FOREIGN KEY (ID) 
	REFERENCES BS_CERT (ID);

-- 证件:机动车驾驶证
create table BS_CERT_DRIVING (
    ID BIGINT NOT NULL,
    NAME varchar(255) COMMENT '姓名',
    SEX int(1) COMMENT '性别(0-未设置,1-男,2-女)',
    BIRTHDATE datetime COMMENT '出生日期',
    NATION varchar(255) COMMENT '国籍',
    ADDRESS varchar(500) COMMENT '地址',
    MODEL varchar(255) COMMENT '准驾车型',
    RECEIVEDATE datetime COMMENT '初次领证日期',
    VALIDFOR varchar(255) COMMENT '有效期限',
    ARCHIVENO varchar(255) COMMENT '档案编号',
    RECORD varchar(255) COMMENT '记录',
    primary key (ID)
) COMMENT='证件:机动车驾驶证';
ALTER TABLE BS_CERT_DRIVING ADD CONSTRAINT BSFK_CERT4DRIVING_CERT FOREIGN KEY (ID) 
	REFERENCES BS_CERT (ID);

-- 证件:从业资格证
create table BS_CERT_CYZG (
    ID BIGINT NOT NULL,
   NAME                 varchar(255) comment '姓名',
   SEX                  int(1) comment '性别(0-未设置,1-男,2-女)',
   BIRTHDATE            datetime comment '出生日期',
   NATION               varchar(255) comment '民族',
   ADDRESS              varchar(500) comment '住址',
   SCOPE_               varchar(255) comment '从业资格',
   IDENTITY_NO          varchar(255) comment '身份证件号',
   SERVICE_UNIT         varchar(500) comment '服务单位',
   primary key (ID)
) COMMENT '证件:从业资格证';
ALTER TABLE BS_CERT_CYZG ADD CONSTRAINT BSFK_CERT4CYZG_CERT FOREIGN KEY (ID) 
	REFERENCES BS_CERT (ID);

-- 证件:服务资格证
create table BS_CERT_FWZG (
    ID BIGINT NOT NULL,
   NAME                 varchar(255) comment '姓名',
   SEX                  int(1) comment '性别(0-未设置,1-男,2-女)',
   BIRTHDATE            datetime comment '出生日期',
   NATION               varchar(255) comment '民族',
   ADDRESS              varchar(500) comment '住址',
   LEVEL_               varchar(255) comment '等级',
   SERVICE_UNIT         varchar(500) comment '服务单位',
   primary key (ID)
)COMMENT '证件:服务资格证';
ALTER TABLE BS_CERT_FWZG ADD CONSTRAINT BSFK_CERT4FWZG_CERT FOREIGN KEY (ID) 
	REFERENCES BS_CERT (ID);

-- 证件:驾驶培训证
create table BS_CERT_JSPX (
    ID BIGINT NOT NULL,
   NAME                 varchar(255) comment '姓名',
   SEX                  int(1) comment '性别(0-未设置,1-男,2-女)',
   BIRTHDATE            datetime comment '出生日期',
   NATION               varchar(255) comment '民族',
   ADDRESS              varchar(500) comment '住址',
   DOMAIN               varchar(255) comment '培训专业',
   TRAIN_DATE           datetime comment '培训时间',
   TRAIN_HOUR           int(3) comment '培训学时',
   GRADE1               int(3) comment '理论知识考核成绩',
   GRADE2               varchar(10) comment '操作技能考核成绩',
   GRADE3               varchar(10) comment '评定成绩',
   IDENTITY_NO          varchar(255) comment '身份证件号',
   primary key (ID)
)COMMENT '证件:驾驶培训证';
ALTER TABLE BS_CERT_JSPX ADD CONSTRAINT BSFK_CERT4JSPX_CERT FOREIGN KEY (ID) 
	REFERENCES BS_CERT (ID);
    
-- 证件：机动车行驶证
CREATE TABLE BS_CERT_VEHICELICENSE(
   ID                   BIGINT NOT NULL,
   FACTORY              VARCHAR(255) COMMENT '品牌型号，如“桑塔纳SVW7182QQD”',
   PLATE                VARCHAR(255) COMMENT '车牌及号码，如“粤AC4X74”',
   OWNER                VARCHAR(255) COMMENT '业户名称',
   ADDRESS              VARCHAR(255) COMMENT '地址',
   USE_CHARACTER        VARCHAR(255) COMMENT '使用性质',
   VEHICE_TYPE          VARCHAR(255) COMMENT '车辆类型',
   VIN                  VARCHAR(255) COMMENT '车辆识别代号',
   ENGINE_NO            VARCHAR(255) COMMENT '发动机号码',
   REGISTER_DATE        DATETIME COMMENT '注册日期',
   ARCHIVE_NO           VARCHAR(255) COMMENT '档案编号',
   DIM_LEN              BIGINT COMMENT '外廓尺寸：长，单位MM',
   DIM_WIDTH            BIGINT COMMENT '外廓尺寸：宽，单位MM',
   DIM_HEIGHT           BIGINT COMMENT '外廓尺寸：高，单位MM',
   TOTAL_WEIGHT         BIGINT COMMENT '总质量，单位KG',
   CURB_WEIGHT          BIGINT COMMENT '整备质量，单位KG',
   ACCESS_WEIGHT        BIGINT COMMENT '核定载质量，单位KG',
   PULL_WEIGHT          BIGINT COMMENT '准牵引总质量，单位KG',
   ACCESS_COUNT         BIGINT COMMENT '核定载人数',
   SCRAP_DATE           DATETIME COMMENT '强制报废日期',
   DESC_                VARCHAR(500) COMMENT '备注',
   RECORD_              VARCHAR(500) COMMENT '检验记录',
   PRIMARY KEY (ID)
) COMMENT '证件：机动车行驶证';
ALTER TABLE BS_CERT_VEHICELICENSE ADD CONSTRAINT BSFK_CERT4VEHICELICENSE_CERT FOREIGN KEY (ID)
      REFERENCES BS_CERT (ID);
	  
-- 证件：道路运输证
CREATE TABLE BS_CERT_ROADTRANSPORT(
   ID                   BIGINT NOT NULL,
   FACTORY              VARCHAR(255) COMMENT '品牌型号，如“桑塔纳SVW7182QQD”',
   PLATE                VARCHAR(255) COMMENT '车牌及号码，如“粤AC4X74”',
   OWNER                VARCHAR(255) COMMENT '业户名称',
   ADDRESS              VARCHAR(255) COMMENT '地址',
   BS_CERT_NO           VARCHAR(255) COMMENT '经营许可证号',
   SEAT                 VARCHAR(255) COMMENT '吨（座）位',
   DIM_LEN              BIGINT COMMENT '外廓尺寸：长，单位MM',
   DIM_WIDTH            BIGINT COMMENT '外廓尺寸：宽，单位MM',
   DIM_HEIGHT           BIGINT COMMENT '外廓尺寸：高，单位MM',
   SCOPE_               VARCHAR(255) COMMENT '经营范围',
   LEVEL_               VARCHAR(255) COMMENT '技术等级',
   DESC_                VARCHAR(255) COMMENT '备注',
   PRIMARY KEY (ID)
) COMMENT '证件：道路运输证';
ALTER TABLE BS_CERT_ROADTRANSPORT ADD CONSTRAINT BSFK_CERT4ROADTRANSPORT_CERT FOREIGN KEY (ID)
      REFERENCES BS_CERT (ID);


-- 司机责任人
create table BS_CARMAN (
    ID BIGINT NOT NULL auto_increment,
    UID_ varchar(36) NOT NULL COMMENT 'UID',
    STATUS_ int(1) NOT NULL COMMENT '状态：0-已禁用,1-启用中,2-已删除',
    TYPE_ int(1) default 0 NOT NULL COMMENT '类别:0-司机,1-责任人,2-司机和责任人',
    NAME varchar(255) NOT NULL COMMENT '姓名',
    ORDER_ varchar(100) COMMENT '排序号',
    SEX int(1) default 0 NOT NULL COMMENT 'user-性别：0-未设置,1-男,2-女',
    WORK_DATE datetime COMMENT '入职日期',
    ORIGIN               varchar(255) comment '籍贯',
    REGION_              varchar(255) comment '区域',
    HOUSE_TYPE           varchar(255) comment '户口类型',
    BIRTHDATE datetime comment '出生日期',
    FORMER_UNIT          varchar(255) comment '入职原单位',
    ADDRESS              varchar(500) comment '身份证住址',
    ADDRESS1             varchar(500) comment '暂住地址',
    PHONE                varchar(500) comment '电话',
    PHONE1               varchar(500) comment '电话1',
    MODEL_               varchar(255) comment '准驾车型',
	LEVEL_               VARCHAR(255) comment '司机等级',
    CERT_IDENTITY        varchar(255) comment '身份证号',
    CERT_DRIVING         varchar(255) comment '驾驶证号',
    CERT_DRIVING_ARCHIVE varchar(255) comment '驾驶证档案号',
    CERT_DRIVING_FIRST_DATE datetime comment '初次领证日期',
    CERT_DRIVING_START_DATE datetime comment '驾驶证起效日期',
    CERT_DRIVING_END_DATE datetime comment '驾驶证过期日期',
    CERT_FWZG            varchar(255) comment '服务资格证号',
    CERT_FWZG_ID            varchar(255) comment '服务资格ID',
    CERT_CYZG            varchar(255) comment '从业资格证号',
    DRIVING_STATUS       varchar(255) comment '驾驶状态',
    OLD_UNIT_NAME             varchar(255) comment '分支机构：用于历史数据的保存',
    CHARGER	             varchar(255) comment '责任人信息',
    GZ                   int(1) default 0 comment '驾驶证是否广州:0-否,1-是',
    ACCESS_CERTS         varchar(255) comment '已考取证件：历史数据保存',
    DESC_                varchar(4000) comment '备注',
    FILE_DATE datetime NOT NULL COMMENT '创建时间',
    AUTHOR_ID BIGINT NOT NULL COMMENT '创建人ID',
    MODIFIER_ID BIGINT COMMENT '最后修改人ID',
    MODIFIED_DATE datetime COMMENT '最后修改时间',
    primary key (ID)
) COMMENT='司机责任人';
ALTER TABLE BS_CARMAN ADD CONSTRAINT BSFK_CARMAN_AUTHOR FOREIGN KEY (AUTHOR_ID) 
	REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
ALTER TABLE BS_CARMAN ADD CONSTRAINT BSFK_CARMAN_MODIFIER FOREIGN KEY (MODIFIER_ID) 
	REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
CREATE INDEX BSIDX_CARMAN_STATUS ON BS_CARMAN (STATUS_);
-- 司机责任人与证件的关联
CREATE TABLE BS_CARMAN_CERT (
    MAN_ID BIGINT NOT NULL COMMENT '司机责任人ID',
    CERT_ID BIGINT NOT NULL COMMENT '证件ID',
    PRIMARY KEY (MAN_ID,CERT_ID)
) COMMENT='司机责任人与证件的关联';
ALTER TABLE BS_CARMAN_CERT ADD CONSTRAINT BSFK_CARMANCERT_MAN FOREIGN KEY (MAN_ID) 
	REFERENCES BS_CARMAN (ID);
ALTER TABLE BS_CARMAN_CERT ADD CONSTRAINT BSFK_CARMANCERT_CERT FOREIGN KEY (CERT_ID) 
	REFERENCES BS_CERT (ID);
    
-- 车辆
CREATE TABLE BS_CAR(
   ID                   BIGINT NOT NULL auto_increment,
   UID_                 VARCHAR(36) NOT NULL,
   STATUS_              INT(1) NOT NULL COMMENT '状态：0-已禁用,1-启用中,2-已删除',
   OLD_UNIT_NAME        VARCHAR(255) COMMENT '所属单位',
   MOTORCADE_ID         BIGINT NOT NULL COMMENT '所属车队ID',
   BS_TYPE              VARCHAR(255) COMMENT '营运性质',
   CODE                 VARCHAR(255) COMMENT '自编号',
   ORIGIN_NO            VARCHAR(255) COMMENT '原车号',
   PLATE_TYPE           VARCHAR(255) COMMENT '车牌归属，如“粤A”',
   PLATE_NO             VARCHAR(255) COMMENT '车牌号码，如“C4X74”',
   VIN                  VARCHAR(255) COMMENT '车辆识别代号',
   FACTORY_TYPE         VARCHAR(255) COMMENT '厂牌类型，如“桑塔纳”',
   FACTORY_MODEL        VARCHAR(255) COMMENT '厂牌型号，如“SVW7182QQD”',
   REGISTER_DATE        DATETIME COMMENT '登记日期',
   OPERATE_DATE         DATETIME COMMENT '投产日期',
   SCRAP_DATE           DATETIME COMMENT '报废日期',
   FACTORY_DATE         DATETIME COMMENT '出厂日期',
   REGISTER_NO          VARCHAR(255) COMMENT '机动车登记编号',
   LEVEL_               VARCHAR(255) COMMENT '车辆定级',
   COLOR                VARCHAR(255) COMMENT '颜色',
   ENGINE_NO            VARCHAR(255) COMMENT '发动机号码',
   ENGINE_TYPE          VARCHAR(255) COMMENT '发动机类型',
   FUEL_TYPE            VARCHAR(255) COMMENT '燃料类型，如“汽油”',
   DISPLACEMENT         BIGINT COMMENT '排量，单位ML',
   POWER                DECIMAL(19,2) COMMENT '功率，单位KW',
   TURN_TYPE            VARCHAR(255) COMMENT '转向方式，如“方向盘”',
   TIRE_COUNT           BIGINT COMMENT '轮胎数',
   TIRE_STANDARD        VARCHAR(255) COMMENT '轮胎规格',
   AXIS_DISTANCE        BIGINT COMMENT '轴距',
   AXIS_COUNT           BIGINT COMMENT '轴数',
   PIECE_COUNT          BIGINT COMMENT '后轴钢板弹簧片数',
   DIM_LEN              BIGINT COMMENT '外廓尺寸：长，单位MM',
   DIM_WIDTH            BIGINT COMMENT '外廓尺寸：宽，单位MM',
   DIM_HEIGHT           BIGINT COMMENT '外廓尺寸：高，单位MM',
   TOTAL_WEIGHT         BIGINT COMMENT '总质量，单位KG',
   ACCESS_WEIGHT        BIGINT COMMENT '核定载质量，单位KG',
   ACCESS_COUNT         BIGINT COMMENT '核定载人数',
   ORIGINAL_VALUE       DECIMAL(19,2) COMMENT '固定资产原值，单位元',
   INVOICE_NO1          VARCHAR(255) COMMENT '购车发票号',
   INVOICE_NO2          VARCHAR(255) COMMENT '购置税发票号',
   PAYMENT_TYPE         VARCHAR(255) COMMENT '缴费日',
   CERT_NO1             VARCHAR(255) COMMENT '购置税证号',
   CERT_NO2             VARCHAR(255) COMMENT '经营权使用证号',
   CERT_NO3             VARCHAR(255) COMMENT '强检证号',
   TAXIMETER_FACTORY    VARCHAR(255) COMMENT '计价器制造厂',
   TAXIMETER_TYPE       VARCHAR(255) COMMENT '计价器型号',
   TAXIMETER_NO         VARCHAR(255) COMMENT '计价器出厂编号',
   DESC1                VARCHAR(4000) COMMENT '备注1',
   DESC2                VARCHAR(4000) COMMENT '备注2',
   DESC3                VARCHAR(4000) COMMENT '备注3',
   FILE_DATE            DATETIME NOT NULL COMMENT '创建时间',
   AUTHOR_ID            BIGINT NOT NULL COMMENT '创建人ID',
   MODIFIER_ID          BIGINT COMMENT '最后修改人ID',
   MODIFIED_DATE        DATETIME COMMENT '最后修改时间',
   COMPANY              VARCHAR(255) COMMENT '旧分支机构',
   DRIVER               VARCHAR(255) COMMENT '当前营运司机的描述信息',
   CHARGER              VARCHAR(255) COMMENT '当前责任人的描述信息',
   PRIMARY KEY (ID)
) COMMENT '车辆';
ALTER TABLE BS_CAR ADD CONSTRAINT BSFK_CAR_AUTHOR FOREIGN KEY (AUTHOR_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
ALTER TABLE BS_CAR ADD CONSTRAINT BSFK_CAR_MODIFIER FOREIGN KEY (MODIFIER_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
ALTER TABLE BS_CAR ADD CONSTRAINT BSFK_CAR_MOTORCADEID FOREIGN KEY (MOTORCADE_ID)
      REFERENCES BS_MOTORCADE (ID);
CREATE INDEX BSIDX_CAR_STATUS ON BS_CAR (STATUS_);
CREATE INDEX BSIDX_CAR_MOTORCADE ON BS_CAR (MOTORCADE_ID);

-- 车辆与证件的关联
CREATE TABLE BS_CAR_CERT(
   CAR_ID               BIGINT NOT NULL COMMENT '车辆ID',
   CERT_ID              BIGINT NOT NULL COMMENT '证件ID',
   PRIMARY KEY (CAR_ID, CERT_ID)
) COMMENT '车辆与证件的关联';
ALTER TABLE BS_CAR_CERT ADD CONSTRAINT BSFK_CAR_CERT_CARID FOREIGN KEY (CAR_ID)
      REFERENCES BS_CAR (ID) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE BS_CAR_CERT ADD CONSTRAINT BSFK_CAR_CERT_CERTID FOREIGN KEY (CERT_ID)
      REFERENCES BS_CERT (ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- 合同
CREATE TABLE BS_CONTRACT(
   ID                   BIGINT NOT NULL AUTO_INCREMENT,
   UID_                 VARCHAR(36) NOT NULL,
   PID                  BIGINT,
   STATUS_              BIGINT NOT NULL COMMENT '状态：0-在案,1-失效,2-离职',
   VER_MAJOR            BIGINT COMMENT '主版本号',
   VER_MINOR            BIGINT COMMENT '次版本号',
   PATCH_NO             VARCHAR(255) NOT NULL COMMENT '批号',
   MAIN                 INT(1) NOT NULL COMMENT '主体: 0-当前版本,1-历史版本',
   WORD_NO              VARCHAR(255) COMMENT '文书号',
   CODE                 VARCHAR(255) NOT NULL COMMENT '合同号',
   TYPE_                INT(1) NOT NULL COMMENT '合同类型：1-司机劳动合同、2-责任人合同',
   OP_TYPE              INT(1) NOT NULL COMMENT '操作类型',
   TRANSACTOR_ID        BIGINT COMMENT '经办人ID',
   TRANSACTOR_NAME      VARCHAR(255) COMMENT '经办人姓名',
   SIGN_DATE            DATETIME COMMENT '签订日期',
   START_DATE           DATETIME NOT NULL COMMENT '生效日期',
   END_DATE             DATETIME NOT NULL COMMENT '到期日期',
   CONTENT              VARCHAR(4000) COMMENT '合同内容',
   EXT_STR1             VARCHAR(255) COMMENT '车牌',
   EXT_STR2             VARCHAR(255) COMMENT '司机责任人姓名',
   EXT_STR3             VARCHAR(255) COMMENT '字符扩展域3',
   EXT_NUM1             BIGINT COMMENT '数字扩展域1',
   EXT_NUM2             BIGINT COMMENT '数字扩展域2',
   EXT_NUM3             BIGINT COMMENT '数字扩展域3',
   FILE_DATE            DATETIME NOT NULL COMMENT '创建时间',
   AUTHOR_ID            BIGINT NOT NULL COMMENT '创建人ID',
   MODIFIER_ID          BIGINT COMMENT '最后修改人ID',
   MODIFIED_DATE        DATETIME COMMENT '最后修改时间',
   PRIMARY KEY (ID)
) COMMENT '合同';
ALTER TABLE BS_CONTRACT ADD CONSTRAINT BSFK_CONTRACT_AUTHOR FOREIGN KEY (AUTHOR_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
ALTER TABLE BS_CONTRACT ADD CONSTRAINT BSFK_CONTRACT_MODIFIER FOREIGN KEY (MODIFIER_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
ALTER TABLE BS_CONTRACT ADD CONSTRAINT FK_REFERENCE_77 FOREIGN KEY (PID)
      REFERENCES BS_CONTRACT (ID);
CREATE INDEX BSIDX_CONTRACT_STATUS ON BS_CONTRACT (STATUS_);
CREATE INDEX BSIDX_CONTRACT_PATCH_NO ON BS_CONTRACT (PATCH_NO);

-- 司机责任人与合同的关联
CREATE TABLE BS_CARMAN_CONTRACT(
   MAN_ID               BIGINT NOT NULL COMMENT '司机责任人ID',
   CONTRACT_ID          BIGINT NOT NULL COMMENT '合同ID',
   PRIMARY KEY (MAN_ID, CONTRACT_ID)
)COMMENT '司机责任人与合同的关联';
ALTER TABLE BS_CARMAN_CONTRACT ADD CONSTRAINT BSFK_CARMANCONTRACT_CONTRACT FOREIGN KEY (CONTRACT_ID)
      REFERENCES BS_CONTRACT (ID) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE BS_CARMAN_CONTRACT ADD CONSTRAINT BSFK_CARMANCONTRACT_MAN FOREIGN KEY (MAN_ID)
      REFERENCES BS_CARMAN (ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- 车辆与合同的关联
CREATE TABLE BS_CAR_CONTRACT(
   CAR_ID               BIGINT NOT NULL COMMENT '车辆ID',
   CONTRACT_ID          BIGINT NOT NULL COMMENT '合同ID',
   PRIMARY KEY (CAR_ID, CONTRACT_ID)
) COMMENT '车辆与合同的关联';
ALTER TABLE BS_CAR_CONTRACT ADD CONSTRAINT BSFK_CARCONTRACT_CAR FOREIGN KEY (CAR_ID)
      REFERENCES BS_CAR (ID) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE BS_CAR_CONTRACT ADD CONSTRAINT BSFK_CARCONTRACT_CONTRACT FOREIGN KEY (CONTRACT_ID)
      REFERENCES BS_CONTRACT (ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- 司机劳动合同
CREATE TABLE BS_CONTRACT_LABOUR(
   ID                   BIGINT NOT NULL,
   CERT_NO              VARCHAR(255) NOT NULL COMMENT '资格证号',
   CERT_IDENTITY        VARCHAR(255)  COMMENT '身份证号',
   SEX                  INT(1) COMMENT '性别(0-未设置,1-男,2-女)',
   BIRTHDATE            DATETIME COMMENT '出生日期',
   AGE                  BIGINT COMMENT '年龄: 通过出生年月算出',
   ORIGIN               VARCHAR(255) COMMENT '籍贯',
   HOUSE_TYPE           VARCHAR(255) COMMENT '户口类型',
   DOLE                 INT(1) DEFAULT 0 COMMENT '个人岗位补贴:0-无,1-有',
   FUNDING              INT(1) DEFAULT 0 COMMENT '对公社保资助',
   INSURCODE            VARCHAR(255) COMMENT '社保号',
   JOINDATE             DATETIME  COMMENT '参保日期',
   REGISTER_DATE        DATETIME COMMENT '车辆登记日期',
   INSURE_DATE          DATETIME COMMENT '申领日期',
   BS_TYPE              VARCHAR(255) COMMENT '营运性质',
   BUY_UNIT             VARCHAR(255)  COMMENT '购买单位',
   INSURANCE_TYPE       VARCHAR(255) COMMENT '社保险种',
   IS_IQAMA             INT(1) DEFAULT 0 COMMENT '是否缴交暂住证',
   IS_ACCOUNT_BOOK      INT(1) DEFAULT 0 COMMENT '是否缴交户口薄',
   IS_IDENTITY_CARDS    INT(1) DEFAULT 0 COMMENT '是否缴交身份证',
   IS_FPC               INT(1) DEFAULT 0 COMMENT '是否缴交计生证',
   IS_UNEMPLOYED        INT(1) DEFAULT 0 COMMENT '是否缴交失业就业手册',
   IS_HEALTHFORM        INT(1) DEFAULT 0 COMMENT '是否缴交体检表',
   IS_PHOTO             INT(1) DEFAULT 0 COMMENT '是否缴交照片',
   BREEDING_DATE        DATETIME COMMENT '生育日期',
   GET_STARTDATE        DATETIME COMMENT '申领开始日期',
   GET_ENDDATE          DATETIME COMMENT '申领结束日期',
   REMARK               VARCHAR(255) COMMENT '备注',
   STOPDATE		DATETIME COMMENT '停保日期',
   LEAVEDATE		DATETIME COMMENT '离职日期',
   PRIMARY KEY (ID)
) COMMENT '司机劳动合同';
ALTER TABLE BS_CONTRACT_LABOUR ADD CONSTRAINT BSFK_CONTRACT4LABOUR_CONTRACT FOREIGN KEY (ID)
      REFERENCES BS_CONTRACT (ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- 责任人合同
CREATE TABLE BS_CONTRACT_CHARGER(
   ID                   BIGINT NOT NULL,
   SIGN_TYPE            VARCHAR(255) NOT NULL COMMENT '签约类型:如新户',
   LOGOUT               INT(1) DEFAULT 0 COMMENT '注销:0-未,1-已',
   TAKEBACK_ORIGIN      INT(1) DEFAULT 0 COMMENT '已经收回原件:0-未1-已',
   INCLUDE_COST         INT(1) DEFAULT 0 COMMENT '包含检审费用:0-不包含,1-包含',
   OLD_CONTENT          VARCHAR(4000) COMMENT '旧合同内容',
   BS_TYPE              VARCHAR(255) COMMENT '合同性质',
   PRIMARY KEY (ID)
)COMMENT '责任人合同:如承包合同';
ALTER TABLE BS_CONTRACT_CHARGER ADD CONSTRAINT BSFK_CONTRACT4CHARGER_CONTRACT FOREIGN KEY (ID)
      REFERENCES BS_CONTRACT (ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- 工伤
CREATE TABLE BS_INDUSTRIAL_INJURY(
   ID                   BIGINT NOT NULL AUTO_INCREMENT,
   UID_			VARCHAR(36) NOT NULL,
   CONTRACT_ID          BIGINT NOT NULL COMMENT '合同ID',
   STATUS_              INT(1) NOT NULL COMMENT '状态：0-正常,1-已禁用',
   CODE                 VARCHAR(255) NOT NULL COMMENT '工伤号',
   HAPPEN_DATE          DATETIME COMMENT '工伤时间',
   CONFIRM_DATE         DATETIME COMMENT '认定日期',
   START_DATE           DATETIME COMMENT '医疗开始日期',
   END_DATE             DATETIME COMMENT '医疗结束日期',
   COMPENSATION         VARCHAR(255) COMMENT '赔偿项目',
   MONEY                DECIMAL(10,2) COMMENT '金额',
   IS_OAS               INT(1) DEFAULT 0 COMMENT '是否门诊',
   IS_IN_HOSPITAL       INT(1) DEFAULT 0 COMMENT '是否住院',
   IS_LI                INT(1) DEFAULT 0 COMMENT '是否劳动鉴别',
   DESCRIPTION          VARCHAR(4000) COMMENT '概况描述',
   FILE_DATE            DATETIME NOT NULL COMMENT '创建时间',
   AUTHOR_ID            BIGINT NOT NULL COMMENT '创建人ID',
   MODIFIER_ID          BIGINT COMMENT '最后修改人ID',
   MODIFIED_DATE        DATETIME COMMENT '最后修改时间',
   PRIMARY KEY (ID)
) COMMENT '工伤';
ALTER TABLE BS_INDUSTRIAL_INJURY ADD CONSTRAINT FK_REFERENCE_74 FOREIGN KEY (CONTRACT_ID)
      REFERENCES BS_CONTRACT_LABOUR (ID) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE BS_INDUSTRIAL_INJURY ADD CONSTRAINT FK_REFERENCE_75 FOREIGN KEY (AUTHOR_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
ALTER TABLE BS_INDUSTRIAL_INJURY ADD CONSTRAINT FK_REFERENCE_76 FOREIGN KEY (MODIFIER_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);


-- 司机营运车辆
CREATE TABLE BS_CAR_DRIVER(
   ID                   BIGINT NOT NULL auto_increment,
   STATUS_ int(1) NOT NULL COMMENT '状态：0-已禁用,1-启用中,2-已删除',
   DRIVER_ID            BIGINT NOT NULL COMMENT '司机ID',
   CAR_ID               BIGINT NOT NULL COMMENT '车辆ID',
   CLASSES              int(1) NOT NULL COMMENT '营运班次:如0-未定义，1-正班、2-副班、3-顶班',
   FILE_DATE            DATETIME NOT NULL COMMENT '创建时间',
   AUTHOR_ID            BIGINT NOT NULL COMMENT '创建人ID',
   MODIFIED_DATE        DATETIME COMMENT '最后修改时间',
   MODIFIER_ID          BIGINT COMMENT '最后修改人ID',
   DESC_                VARCHAR(4000) COMMENT '备注',
   PRIMARY KEY (ID)
) COMMENT '司机营运车辆';
ALTER TABLE BS_CAR_DRIVER ADD CONSTRAINT BSFK_CARDRIVER_AUTHOR FOREIGN KEY (AUTHOR_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
ALTER TABLE BS_CAR_DRIVER ADD CONSTRAINT BSFK_CARDRIVER_MODIFIER FOREIGN KEY (MODIFIER_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
ALTER TABLE BS_CAR_DRIVER ADD CONSTRAINT BSFK_CARDRIVER_CAR FOREIGN KEY (CAR_ID)
      REFERENCES BS_CAR (ID);
ALTER TABLE BS_CAR_DRIVER ADD CONSTRAINT BSFK_CARDRIVER_CARMAN FOREIGN KEY (DRIVER_ID)
      REFERENCES BS_CARMAN (ID);
      CREATE INDEX BSIDX_CARDRIVER_CAR ON BS_CAR_DRIVER (CAR_ID);
      CREATE INDEX BSIDX_CARDRIVER_DRIVER ON BS_CAR_DRIVER (DRIVER_ID);
-- 迁移记录
CREATE TABLE BS_CAR_DRIVER_HISTORY (
   ID                   BIGINT NOT NULL auto_increment,
   DRIVER_ID            BIGINT  COMMENT '司机ID',
   FROM_CAR_ID          BIGINT  COMMENT  '原车辆ID',
   FROM_MOTORCADE_ID    BIGINT  COMMENT   '原车队ID',
   FROM_CLASSES         int(1)  COMMENT   '营运班次:如1-正班、2-副班、3-顶班',
   TO_CAR_ID            BIGINT  COMMENT   '新车辆ID',
   TO_MOTORCADE_ID      BIGINT  COMMENT   '新车队ID',
   TO_CLASSES           int(1)  COMMENT   '营运班次:如1-正班、2-副班、3-顶班',
   MOVE_DATE            datetime  COMMENT      '迁移日期',
   MOVE_TYPE            int(1)  NOT NULL  COMMENT '迁移类型',  
   FROM_UNIT            VARCHAR(255) COMMENT  '原单位',
   TO_UNIT              VARCHAR(255) COMMENT  '新单位',
   HAND_PAPERS_DATE     datetime COMMENT  '交证日期',
   CANCEL_ID            VARCHAR(255) COMMENT  '注销单号',
   FILE_DATE            datetime   NOT NULL  COMMENT '创建时间',
   AUTHOR_ID            BIGINT NOT NULL  COMMENT '创建人ID',
   MODIFIED_DATE        datetime  COMMENT '最后修改时间',
   MODIFIER_ID          BIGINT  COMMENT  '最后修改人ID',
   DESC_                VARCHAR(4000)  COMMENT '备注',
   PRIMARY KEY (ID)
)COMMENT '迁移记录';

ALTER TABLE BS_CAR_DRIVER_HISTORY ADD CONSTRAINT BSFK_CARDRIVERHISTORY_AUTHOR FOREIGN KEY (AUTHOR_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
ALTER TABLE BS_CAR_DRIVER_HISTORY ADD CONSTRAINT BSFK_CARDRIVERHISTORY_MODIFIER FOREIGN KEY (MODIFIER_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
ALTER TABLE BS_CAR_DRIVER_HISTORY ADD CONSTRAINT BSFK_CARDRIVER_OLD_CAR FOREIGN KEY (FROM_CAR_ID)
      REFERENCES BS_CAR (ID);
ALTER TABLE BS_CAR_DRIVER_HISTORY ADD CONSTRAINT BSFK_CARDRIVER_NEW_CAR FOREIGN KEY (TO_CAR_ID)
      REFERENCES BS_CAR (ID);
ALTER TABLE BS_CAR_DRIVER_HISTORY ADD CONSTRAINT BSFK_CASEBASE_OLD_MOTORCADE FOREIGN KEY (FROM_MOTORCADE_ID)
      REFERENCES BS_MOTORCADE (ID);
ALTER TABLE BS_CAR_DRIVER_HISTORY ADD CONSTRAINT BSFK_CASEBASE_NEW_MOTORCADE FOREIGN KEY (TO_MOTORCADE_ID)
      REFERENCES BS_MOTORCADE (ID);
ALTER TABLE BS_CAR_DRIVER_HISTORY ADD CONSTRAINT BSFK_CARDRIVERHISTORY_CARMAN FOREIGN KEY (DRIVER_ID)
      REFERENCES BS_CARMAN (ID);
      CREATE INDEX BSIDX_CARDRIVERHISTORY_TO_CAR ON BS_CAR_DRIVER_HISTORY (TO_CAR_ID);
      CREATE INDEX BSIDX_CARDRIVERHISTORY_FR_CAR ON BS_CAR_DRIVER_HISTORY (FROM_CAR_ID);
      CREATE INDEX BSIDX_CARDRIVERHISTORY_DRIVER ON BS_CAR_DRIVER_HISTORY (DRIVER_ID); 
      
      
      
-- 司机迁移历史
CREATE TABLE BS_CARMAN_HISTORY (
   ID                   BIGINT NOT NULL auto_increment,
   TYPE_                VARCHAR(255) NOT NULL COMMENT '迁移属性，如新入职',
   DRIVER_ID            BIGINT NOT NULL COMMENT '司机ID',
   SUBJECT              VARCHAR(1000) COMMENT '其他',
   FROM_CARID           BIGINT COMMENT '迁自车辆ID',
   TO_CARID             BIGINT NOT NULL COMMENT '迁往车辆ID',
   FROM_CLASSES         VARCHAR(255) COMMENT '原营运班次:如正班、副班、顶班',
   TO_CLASSES           VARCHAR(255) NOT NULL COMMENT '新营运班次:如正班、副班、顶班',
   SHIFT_DATE           DATETIME NOT NULL COMMENT '迁移日期',
   FROM_MOTORCADEID     BIGINT COMMENT '原车队ID',
   TO_MOTORCADEID       BIGINT NOT NULL COMMENT '迁往车队ID',
   FILE_DATE            DATETIME NOT NULL COMMENT '创建时间',
   AUTHOR_ID            BIGINT NOT NULL COMMENT '创建人ID',
   MODIFIED_DATE        DATETIME COMMENT '最后修改时间',
   MODIFIER_ID          BIGINT COMMENT '最后修改人ID',
   PRIMARY KEY (ID)
) COMMENT '司机迁移历史';
ALTER TABLE BS_CARMAN_HISTORY ADD CONSTRAINT BS_CARMANHISTORY_DRIVER FOREIGN KEY (DRIVER_ID)
      REFERENCES BS_CARMAN (ID);
ALTER TABLE BS_CARMAN_HISTORY ADD CONSTRAINT BS_CARMANHISTORY_FROMCAR FOREIGN KEY (FROM_CARID)
      REFERENCES BS_CAR (ID);
ALTER TABLE BS_CARMAN_HISTORY ADD CONSTRAINT BS_CARMANHISTORY_TOCAR FOREIGN KEY (TO_CARID)
      REFERENCES BS_CAR (ID);
ALTER TABLE BS_CARMAN_HISTORY ADD CONSTRAINT BS_CARMANHISTORY_FROMMOTORCADE FOREIGN KEY (FROM_MOTORCADEID)
      REFERENCES BS_MOTORCADE (ID);
ALTER TABLE BS_CARMAN_HISTORY ADD CONSTRAINT BS_CARMANHISTORY_TOMOTORCADE FOREIGN KEY (TO_MOTORCADEID)
      REFERENCES BS_MOTORCADE (ID);
ALTER TABLE BS_CARMAN_HISTORY ADD CONSTRAINT BSFK_CARMANHISTORY_AUTHOR FOREIGN KEY (AUTHOR_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
ALTER TABLE BS_CARMAN_HISTORY ADD CONSTRAINT BSFK_CARMANHISTORY_MODIFIER FOREIGN KEY (MODIFIER_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);

-- 黑名单
CREATE TABLE BS_BLACKLIST(
   ID                   BIGINT NOT NULL AUTO_INCREMENT,
   STATUS_              int(1)  COMMENT '状态：0-锁定,1-解锁',
   TYPE_                VARCHAR(255) NOT NULL COMMENT '限制项目',
   OLD_UNIT_NAME        VARCHAR(255)  COMMENT '车属单位',
   DRIVER_ID            BIGINT  COMMENT '司机ID',
   CAR_ID               BIGINT  COMMENT '车辆ID',
   MOTORCADE_ID         BIGINT COMMENT '车队ID',
   SUBJECT              VARCHAR(1000) NOT NULL COMMENT '主题',
   LOCK_DATE            DATETIME NOT NULL COMMENT '锁定时间',
   UNLOCK_DATE          DATETIME COMMENT '解锁时间',
   LOCKER_ID            BIGINT NOT NULL COMMENT '锁定人ID',
   UNLOCKER_ID          BIGINT COMMENT '解锁人ID',
   LOCK_REASON          VARCHAR(4000) COMMENT '锁定原因',
   UNLOCK_REASON        VARCHAR(4000) COMMENT '解锁原因',
   LEVEL_               VARCHAR(255) COMMENT '等级',
   CODE                 VARCHAR(255) COMMENT '编号',
   FILE_DATE            DATETIME NOT NULL COMMENT '创建时间',
   AUTHOR_ID            BIGINT NOT NULL COMMENT '创建人ID',
   MODIFIED_DATE        DATETIME COMMENT '最后修改时间',
   MODIFIER_ID          BIGINT COMMENT '最后修改人ID',
   PRIMARY KEY (ID)
) COMMENT '黑名单';
ALTER TABLE BS_BLACKLIST ADD CONSTRAINT BSFK_BLACKLIST_AUTHOR FOREIGN KEY (AUTHOR_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
ALTER TABLE BS_BLACKLIST ADD CONSTRAINT BSFK_BLACKLIST_MODIFIER FOREIGN KEY (MODIFIER_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
ALTER TABLE BS_BLACKLIST ADD CONSTRAINT BSFK_BLACKLIST_MOTORCADE FOREIGN KEY (MOTORCADE_ID)
      REFERENCES BS_MOTORCADE (ID);
ALTER TABLE BS_BLACKLIST ADD CONSTRAINT BSFK_BLACKLIST_CAR FOREIGN KEY (CAR_ID)
      REFERENCES BS_CAR (ID);
ALTER TABLE BS_BLACKLIST ADD CONSTRAINT BSFK_BLACKLIST_DIRVER FOREIGN KEY (DRIVER_ID)
      REFERENCES BS_CARMAN (ID);
ALTER TABLE BS_BLACKLIST ADD CONSTRAINT BSFK_BLACKLIST_LOCKER FOREIGN KEY (LOCKER_ID)
      REFERENCES BC_IDENTITY_ACTOR (ID);
ALTER TABLE BS_BLACKLIST ADD CONSTRAINT BSFK_BLACKLIST_UNLOCKER FOREIGN KEY (UNLOCKER_ID)
      REFERENCES BC_IDENTITY_ACTOR (ID);
      CREATE INDEX BSIDX_BLACKLIST_DRIVER ON BS_BLACKLIST (DRIVER_ID);
      CREATE INDEX BSIDX_BLACKLIST_CAR ON BS_BLACKLIST (CAR_ID);



-- 营运事件基表
CREATE TABLE BS_CASE_BASE(
   ID                   BIGINT NOT NULL AUTO_INCREMENT,
   UID_                 VARCHAR(36) NOT NULL,
   CASE_NO              VARCHAR(255)  COMMENT '案号：营运违章的案号，交通违章的违章顺序号等',
   CODE                 VARCHAR(255) NOT NULL COMMENT '自编号',
   TYPE_                INT(1) NOT NULL COMMENT '内部类型：1-表扬、2-投诉、3-营运违章、4-交通违章、5-事故',
   STATUS_              INT(1) NOT NULL COMMENT '状态：0-在案,1-已结案',
   SOURCE               INT(1) NOT NULL COMMENT '数据来源：1-用户创建、2-接口导入',
   FROM_                VARCHAR(255)  COMMENT '来源(用户填写)',
   SUBJECT              VARCHAR(1000) COMMENT '标题',
   ADDRESS              VARCHAR(1000) COMMENT '事发地点',
   HAPPEN_DATE          DATETIME NOT NULL COMMENT '事发时间',
   MOTORCADE_ID         BIGINT COMMENT '车队ID',
   MOTORCADE_NAME       VARCHAR(255) COMMENT '车队名称',
   CAR_ID               BIGINT COMMENT '车辆ID',
   CAR_PLATE            VARCHAR(255) COMMENT '车辆号码',
   DRIVER_ID            BIGINT COMMENT '司机ID',
   DRIVER_NAME          VARCHAR(255) COMMENT '司机姓名',
   DRIVER_CERT          VARCHAR(255) COMMENT '服务资格证',
   CLOSER_ID            BIGINT  COMMENT '结案人ID',
   CLOSER_NAME          VARCHAR(255) COMMENT '结案人姓名',
   CLOSE_DATE           DATETIME COMMENT '结案日期',
   DESC_                VARCHAR(4000) COMMENT '备注',
   FILE_DATE            DATETIME NOT NULL COMMENT '创建时间',
   AUTHOR_ID            BIGINT NOT NULL COMMENT '创建人ID',
   MODIFIER_ID          BIGINT COMMENT '最后修改人ID',
   MODIFIED_DATE        DATE COMMENT '最后修改时间',
   SYNC_ID              BIGINT  COMMENT '数据同步ID',
   SYNC_UID             VARCHAR(36) COMMENT '旧数据同步的UID',
   PRIMARY KEY (ID)
) COMMENT '营运事件：表扬、投诉、营运违章、交通违法、事故等的基表';
ALTER TABLE BS_CASE_BASE ADD CONSTRAINT BSFK_CASEBASE_AUTHOR FOREIGN KEY (AUTHOR_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
ALTER TABLE BS_CASE_BASE ADD CONSTRAINT BSFK_CASEBASE_MODIFIER FOREIGN KEY (MODIFIER_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
ALTER TABLE BS_CASE_BASE ADD CONSTRAINT BSFK_CASEBASE_MOTORCADE FOREIGN KEY (MOTORCADE_ID)
      REFERENCES BS_MOTORCADE (ID);
ALTER TABLE BS_CASE_BASE ADD CONSTRAINT BSFK_CASEBASE_CAR FOREIGN KEY (CAR_ID)
      REFERENCES BS_CAR (ID);
ALTER TABLE BS_CASE_BASE ADD CONSTRAINT BSFK_CASEBASE_DRIVER FOREIGN KEY (DRIVER_ID)
      REFERENCES BS_CARMAN (ID);
ALTER TABLE BS_CASE_BASE ADD CONSTRAINT BSFK_CASEBASE_CLOSER FOREIGN KEY (CLOSER_ID)
      REFERENCES BC_IDENTITY_ACTOR (ID);
ALTER TABLE BS_CASE_BASE ADD CONSTRAINT BSFK_CASEBASE_SYNC FOREIGN KEY (SYNC_ID)
      REFERENCES BC_SYNC_BASE (ID);
CREATE INDEX BSIDX_CASE_BASE_DRIVER ON BS_CASE_BASE (DRIVER_ID);
CREATE INDEX BSIDX_CASE_BASE_CAR ON BS_CASE_BASE (CAR_ID);


-- 交通违章
CREATE TABLE BS_CASE_INFRACT_TRAFFIC(
   ID                   BIGINT NOT NULL,
   CHARGER1_ID          BIGINT COMMENT '责任人1ID',
   CHARGER1_NAME        VARCHAR(255) COMMENT '责任人1姓名',
   CHARGER2_ID          BIGINT COMMENT '责任人2ID',
   CHARGER2_NAME        VARCHAR(255) COMMENT '责任人2姓名',
   DUTY                 VARCHAR(255) COMMENT '责任',
   SORT                 VARCHAR(255) COMMENT '性质',
   JEOM                 DECIMAL(3,1) DEFAULT 0 COMMENT '扣分',
   COMMENT_             VARCHAR(4000) COMMENT '处理意见',
   IS_DELIVER           INT(1) NOT NULL COMMENT '是否邮递：1-是',
   DELIVER_DATE         DATETIME COMMENT '邮递时间',
   IS_SIGN              INT(1) NOT NULL COMMENT '是否签领：1-是',
   SIGN_DATE            DATETIME COMMENT '签领时间',
   PRIMARY KEY (ID)
) COMMENT '交通违章';
ALTER TABLE BS_CASE_INFRACT_TRAFFIC ADD CONSTRAINT BSFK_INFRACTT_CASEBASE FOREIGN KEY (ID)
      REFERENCES BS_CASE_BASE (ID) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE BS_CASE_INFRACT_TRAFFIC ADD CONSTRAINT BSFK_INFRACTT_CHARGER1 FOREIGN KEY (CHARGER1_ID)
      REFERENCES BS_CARMAN (ID);
ALTER TABLE BS_CASE_INFRACT_TRAFFIC ADD CONSTRAINT BSFK_INFRACTT_CHARGER2 FOREIGN KEY (CHARGER2_ID)
      REFERENCES BS_CARMAN (ID);

-- 营运违章
 CREATE TABLE BS_CASE_INFRACT_BUSINESS(
   ID                   BIGINT NOT NULL,
   RECEIVE_DATE         DATETIME COMMENT '接案日期',
   RECEIVER_ID          BIGINT COMMENT '接案人ID',
   RECEIVER_NAME        VARCHAR(255) COMMENT '接案人姓名',
   CHARGER1_ID		BIGINT COMMENT '责任人1ID',
   CHARGER1_NAME        VARCHAR(255) COMMENT '责任人1姓名',
   CHARGER2_ID          BIGINT COMMENT '责任人2ID',
   CHARGER2_NAME        VARCHAR(255) COMMENT '责任人2姓名',
   DUTY                 VARCHAR(255) COMMENT '责任',
   SORT                 VARCHAR(255) COMMENT '性质',
   EXTENT               VARCHAR(255) COMMENT '程度',
   CERT_KJ_TYPE         VARCHAR(255) COMMENT '没收证件类型',
   CERT_KJ              VARCHAR(255) COMMENT '扣件证号',
   CERT_YY              VARCHAR(255) COMMENT '营运证号',
   DETAIN               VARCHAR(255) COMMENT '扣留物品',
   JEOM                 DECIMAL(3,1) DEFAULT 0 COMMENT '扣分',
   PENALTY              DECIMAL(10,2) DEFAULT 0 COMMENT '罚款',
   PENALTY2             DECIMAL(10,2) DEFAULT 0 COMMENT '违约金',
   AREA                 VARCHAR(255) COMMENT '所属区县',
   PULL_UNIT            VARCHAR(255) COMMENT '拖车单位',
   OPERATOR             VARCHAR(255) COMMENT '执法人',
   OPERATE_UNIT         VARCHAR(255) COMMENT '执法机关',
   RECEIPT              VARCHAR(255) COMMENT '罚没收据编号',
   COMMENT_             VARCHAR(4000) COMMENT '处理意见',
   IS_INVALID           INT(1) NOT NULL COMMENT '是否无效：1-无效',
   IS_SEAL              INT(1) NOT NULL COMMENT '是否盖章：1-盖',
   SEAL_DATE            DATETIME COMMENT '盖章日期',
   IS_DELIVER           INT(1) NOT NULL COMMENT '是否交结案单：1-已交',
   IS_CLOSE             INT(1) NOT NULL COMMENT '是否结案：1-结案',
   IS_OVERDUE           INT(1) NOT NULL COMMENT '是否过期：1-过期',
   IS_STOP              INT(1) NOT NULL COMMENT '是否停场：1-停',
   PRIMARY KEY (ID)
) COMMENT '营运违章';
ALTER TABLE BS_CASE_INFRACT_BUSINESS ADD CONSTRAINT BSFK_INFRACTB_CASEBASE FOREIGN KEY (ID)
      REFERENCES BS_CASE_BASE (ID);
ALTER TABLE BS_CASE_INFRACT_BUSINESS ADD CONSTRAINT BSFK_INFRACTB_RECEIVER FOREIGN KEY (RECEIVER_ID)
      REFERENCES BC_IDENTITY_ACTOR (ID);
ALTER TABLE BS_CASE_INFRACT_BUSINESS ADD CONSTRAINT BSFK_INFRACTB_CHARGER1 FOREIGN KEY (CHARGER1_ID)
      REFERENCES BS_CARMAN (ID);
ALTER TABLE BS_CASE_INFRACT_BUSINESS ADD CONSTRAINT BSFK_INFRACTB_CHARGER2 FOREIGN KEY (CHARGER2_ID)
      REFERENCES BS_CARMAN (ID);

-- 事故理赔
CREATE TABLE BS_CASE_ACCIDENT(
   ID                   BIGINT NOT NULL,
   RECEIVE_DATE         DATETIME COMMENT '受理时间',
   RECEIVER_ID          BIGINT COMMENT '经办人ID',
   RECEIVER_NAME        VARCHAR(255) COMMENT '经办人姓名',
   RECEIVE_CODE         VARCHAR(255) COMMENT '受理编号',
   DEPARTMENT           VARCHAR(255) COMMENT '处理部门',
   CHARGER_ID           BIGINT COMMENT '负责人ID',
   CHARGER_NAME         VARCHAR(255) COMMENT '负责人姓名',
   DUTY                 VARCHAR(255) COMMENT '责任',
   SORT                 VARCHAR(255) COMMENT '性质',
   WEATHER              VARCHAR(255) COMMENT '天气',
   DRIVER_AREA          VARCHAR(255) COMMENT '司机区域',
   DRIVER_TYPE          INT(1) COMMENT '司机类型：车主等',
   DRIVER_CLASSES       INT(1) COMMENT '驾驶状态：如正班等',
   INSURANCE_COMPANY    VARCHAR(255) COMMENT '保险公司',
   INSURANCE_INFO       VARCHAR(4000) COMMENT '相关保单',
   IS_DELIVER           INT(1) NOT NULL COMMENT '是否送保：1-是',
   DELIVER_DATE         DATETIME COMMENT '送保日期',
   DELIVER_MONEY        DECIMAL(10,2) COMMENT '送保金额',
   IS_PAY               INT(1) NOT NULL COMMENT '是否司机受款：1-是',
   PAY_DATE             DATETIME COMMENT '司机受款日期',
   PAY_MONEY            DECIMAL(10,2) COMMENT '司机受款金额',
   PAY_CODE             VARCHAR(255) COMMENT '司机受款收据号',
   IS_CLAIM             INT(1) NOT NULL COMMENT '是否保险公司赔付：1-是',
   CLAIM_DATE           DATE COMMENT '保险公司赔付日期',
   CLAIM_MONEY          DECIMAL(10,2) COMMENT '保险公司赔付金额',
   CLAIM_CODE           VARCHAR(255) COMMENT '保险公司赔付收据号',
   CLAIM_NO1            VARCHAR(255) COMMENT '商业险赔付号',
   CLAIM_NO2            VARCHAR(255) COMMENT '交强险赔付号',
   CASUALTIES           VARCHAR(255) COMMENT '伤亡情况',
   CAR_HURT             VARCHAR(255) COMMENT '车损情况',
   THIRD_PARTY          VARCHAR(255) COMMENT '第三者情况',
   IS_ROB               INT(1) COMMENT '是否抢劫：1-是',
   HURT_COUNT           BIGINT COMMENT '受伤人数',
   DEAD_COUNT           BIGINT COMMENT '死亡人数',
   ACTUAL_LOSS          DECIMAL(10,2) COMMENT '实际损失',
   IS_INNER_FIX         INT(1) COMMENT '是否修理厂内修：1-是',
   FIX_COST             DECIMAL(10,2) COMMENT '修理厂内修金额',
   COST_DETAIL          VARCHAR(4000) COMMENT '损失明细',
   PRIMARY KEY (ID)
) COMMENT '事故理赔';
ALTER TABLE BS_CASE_ACCIDENT ADD CONSTRAINT BSFK_ACCIDENT_CASEBASE FOREIGN KEY (ID)
      REFERENCES BS_CASE_BASE (ID);
ALTER TABLE BS_CASE_ACCIDENT ADD CONSTRAINT BSFK_ACCIDENT_CHARGER FOREIGN KEY (CHARGER_ID)
      REFERENCES BC_IDENTITY_ACTOR (ID);
ALTER TABLE BS_CASE_ACCIDENT ADD CONSTRAINT BSFK_ACCIDENT_RECEIVER FOREIGN KEY (RECEIVER_ID)
      REFERENCES BC_IDENTITY_ACTOR (ID);

-- 投诉与建议
CREATE TABLE BS_CASE_ADVICE(
   ID                   BIGINT NOT NULL,
   ADVICE_TYPE          DECIMAL(1,0) NOT NULL COMMENT '标识是投诉还是建议:0-投诉,1-建议',
   RECEIVE_DATE         DATETIME NOT NULL COMMENT '接诉时间',
   RECEIVE_CODE         VARCHAR(255) COMMENT '受理号',
   RECEIVER_ID          BIGINT COMMENT '经办人ID',
   RECEIVER_NAME        VARCHAR(255) COMMENT '经办人姓名',
   SUBJECT2             VARCHAR(255) COMMENT '投诉项目小类',
   DETAIL               VARCHAR(4000) COMMENT '投诉内容',
   CAR_COLOR            VARCHAR(255) COMMENT '车色',
   DRIVER_SEX           INT(1) NOT NULL COMMENT '司机性别:0-未设,1-男,2-女',
   DRIVER_FEATURE       VARCHAR(255) COMMENT '司机特征',
   ADVISOR_NAME         VARCHAR(255) COMMENT '投诉人姓名',
   ADVISOR_SEX          INT(1) NOT NULL COMMENT '投诉人性别',
   ADVISOR_AGE          DECIMAL(3,0) COMMENT '投诉人年龄',
   ADVISOR_PHONE        VARCHAR(255) COMMENT '投诉人电话',
   ADVISOR_CERT         VARCHAR(255) COMMENT '投诉人证件号',
   DUTY                 VARCHAR(255) COMMENT '责任',
   EXTENT               VARCHAR(255) COMMENT '程度',
   NOTICE_DATE          DATETIME COMMENT '通知时间',
   RESULT_              VARCHAR(4000) COMMENT '处理结果',
   TICKET               VARCHAR(255) COMMENT '车票号码',
   MACHINE_PRICE        BIGINT DEFAULT 0 COMMENT '计费器显示价格',
   CHARGE               BIGINT DEFAULT 0 COMMENT '实际收费',
   RIDING_TIME_START    DATETIME COMMENT '乘车起始时间',
   RIDING_TIME_END      DATETIME COMMENT '乘车结束时间',
   PATH_FROM            VARCHAR(255) COMMENT '乘车路线(从)',
   PATH_TO              VARCHAR(255) COMMENT '乘车路线(到)',
   PATH                 VARCHAR(255) COMMENT '乘车路线',
   PASSENGER_COUNT_MAN  INT(1) COMMENT '乘车人数(男)',
   PASSENGER_COUNT_WOMAN INT(1) COMMENT '乘车人数(女)',
   PASSENGER_COUNT_CHILD INT(1) COMMENT '乘车人数(童)',
   PASSENGER_COUNT      INT(1) COMMENT '乘车人数',
   DELIVER_DATE         DATETIME COMMENT '结案书交回日期',
   IS_INVALID           INT(1) NOT NULL COMMENT '是否无效：1-无效',
   PRIMARY KEY (ID)
) COMMENT '投诉与建议';
ALTER TABLE BS_CASE_ADVICE ADD CONSTRAINT BSFK_ADVICE_CASEBASE FOREIGN KEY (ID)
      REFERENCES BS_CASE_BASE (ID);
ALTER TABLE BS_CASE_ADVICE ADD CONSTRAINT BSFK_ADVICE_RECEIVER FOREIGN KEY (RECEIVER_ID)
      REFERENCES BC_IDENTITY_ACTOR (ID);
  
-- 表扬
CREATE TABLE BS_CASE_PRAISE(
   ID                   BIGINT NOT NULL,
   PRAISE_TYPE          VARCHAR(255) COMMENT '表扬类型',
   RECEIVE_DATE         DATETIME NOT NULL COMMENT '接诉时间',
   RECEIVER_ID          BIGINT COMMENT '经办人ID',
   RECEIVER_NAME        VARCHAR(255) COMMENT '经办人姓名',
   SUBJECT2             VARCHAR(255) COMMENT '表扬项目小类',
   DETAIL               VARCHAR(4000) COMMENT '表扬内容',
   CAR_COLOR            VARCHAR(255) COMMENT '车色',
   DRIVER_SEX           INT(1) NOT NULL COMMENT '司机性别:0-未设,1-男,2-女',
   DRIVER_FEATURE       VARCHAR(255) COMMENT '司机特征',
   ADVISOR_NAME         VARCHAR(255) NOT NULL COMMENT '投诉人姓名',
   ADVISOR_SEX          INT(1) NOT NULL COMMENT '投诉人性别',
   ADVISOR_AGE          DECIMAL(3,0) COMMENT '投诉人年龄',
   ADVISOR_PHONE        VARCHAR(255) COMMENT '投诉人电话',
   ADVISOR_CERT         VARCHAR(255) COMMENT '投诉人证件号',
   NOTICE_DATE          DATETIME COMMENT '通知时间',
   RESULT_              VARCHAR(4000) COMMENT '处理结果',
   TICKET               VARCHAR(255) COMMENT '车票号码',
   MACHINE_PRICE        BIGINT COMMENT '计费器显示价格',
   CHARGE               BIGINT COMMENT '实际收费',
   RIDING_TIME_START    DATETIME COMMENT '乘车起始时间',
   RIDING_TIME_END      DATETIME COMMENT '乘车结束时间',
   PATH_FROM            VARCHAR(255) COMMENT '乘车路线(从)',
   PATH_TO              VARCHAR(255) COMMENT '乘车路线(到)',
   PATH                 VARCHAR(255) COMMENT '乘车路线',
   PASSENGER_COUNT_MAN  INT(1) COMMENT '乘车人数(男)',
   PASSENGER_COUNT_WOMAN INT(1) COMMENT '乘车人数(女)',
   PASSENGER_COUNT_CHILD INT(1) COMMENT '乘车人数(童)',
   PASSENGER_COUNT      INT(1) COMMENT '乘车人数',
   REWARD_MONEY         DECIMAL(10,2) COMMENT '获奖金额',
   PRIMARY KEY (ID)
) COMMENT '表扬';
ALTER TABLE BS_CASE_PRAISE ADD CONSTRAINT BSFK_PRAISE_CASEBASE FOREIGN KEY (ID)
      REFERENCES BS_CASE_BASE (ID);
ALTER TABLE BS_CASE_PRAISE ADD CONSTRAINT BSFK_PRAISE_RECEIVER FOREIGN KEY (RECEIVER_ID)
      REFERENCES BC_IDENTITY_ACTOR (ID);


-- 车辆保单
CREATE TABLE BS_CAR_POLICY( 
   ID                                  BIGINT NOT NULL AUTO_INCREMENT,
   UID_                                VARCHAR(36) NOT NULL,
   VER_MAJOR            BIGINT COMMENT '主版本号',
   VER_MINOR            BIGINT COMMENT '次版本号',
   PATCH_NO             VARCHAR(255) NOT NULL COMMENT '批号',
   MAIN                 INT(1) NOT NULL COMMENT '主体: 0-当前版本,1-历史版本'';',
   STATUS_                             INT(1) NOT NULL COMMENT '状态：0-正常,1-注销',
   CAR_ID                              BIGINT NOT NULL COMMENT '投保车号',
   REGISTER_DATE                       DATETIME COMMENT '初登日期',
   ASSURED                             VARCHAR(255)  COMMENT '投保人',
   COMMERIAL_NO                        VARCHAR(255)  COMMENT '商业险号',
   COMMERIAL_COMPANY                   VARCHAR(255)  COMMENT '商业险保险公司',
   COMMERIAL_START_DATE                DATETIME COMMENT '商业险开始日期',
   COMMERIAL_END_DATE                  DATETIME COMMENT '商业险结束日期',
   OWNRISK                             INT(1) DEFAULT 0 COMMENT '是否自保',
   GREENSLIP                           INT(1) DEFAULT 0 COMMENT '是否购买了强制险',
   GREENSLIP_SAME_DATE                 INT(1) DEFAULT 0 COMMENT '强制险是否与商业险同期',
   GREENSLIP_NO                        VARCHAR(255) NOT NULL COMMENT '强险单号',
   GREENSLIP_COMPANY                   VARCHAR(255) COMMENT '强险保险公司',
   GREENSLIP_START_DATE                DATETIME COMMENT '强制险开始日期',
   GREENSLIP_END_DATE                  DATETIME COMMENT '强制险结束日期',
   GREENSLIP_SOURCE                    VARCHAR(255)   COMMENT '强保人来源',
   LIABILITY_NO                        VARCHAR(255) NOT NULL COMMENT '责任险单号',
   AMOUNT                              DECIMAL(10,2) COMMENT'合计',
   FILE_DATE                           DATETIME NOT NULL COMMENT '创建时间',
   AUTHOR_ID                           BIGINT NOT NULL COMMENT '创建人ID',
   MODIFIER_ID                         BIGINT COMMENT '最后修改人ID',
   MODIFIED_DATE                       DATETIME COMMENT '最后修改时间',
  
   PRIMARY KEY (ID)
) COMMENT '车辆保单';
ALTER TABLE BS_CAR_POLICY ADD CONSTRAINT BSFK_CARPOLICY_AUTHOR FOREIGN KEY (AUTHOR_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
ALTER TABLE BS_CAR_POLICY ADD CONSTRAINT BSFK_CARPOLICY_MODIFIER FOREIGN KEY (MODIFIER_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
ALTER TABLE BS_CAR_POLICY ADD CONSTRAINT BSFK_CARPOLICY_CAR FOREIGN KEY (CAR_ID )
      REFERENCES BS_CAR (ID);
CREATE INDEX BS_CAR_POLICY ON BS_CAR_POLICY (CAR_ID);

-- 车保险种
CREATE TABLE  BS_Buy_PLANT(
   ID                   BIGINT NOT NULL AUTO_INCREMENT,
   PID                  BIGINT NOT NULL AUTO_INCREMENT,
   NAME                 VARCHAR(255) NOT NULL COMMENT '险种名称',
   COVERAGE             DECIMAL(10,2) COMMENT '保额',
   PREMIUM              DECIMAL(10,2) COMMENT '保费',
   DESC_                VARCHAR(4000) COMMENT '备注',
   PRIMARY KEY (ID)
) COMMENT '车保险种';
ALTER TABLE BS_Buy_PLANT ADD CONSTRAINT BSFK_BUYPLANT_CARPOLICY FOREIGN KEY (PID)
      REFERENCES BS_CAR_POLICY (ID);

-- 车保险种
CREATE TABLE  BS_INSURANCE_TYPE(
   ID                   BIGINT NOT NULL AUTO_INCREMENT,
   STATUS_              INT(1) NOT NULL COMMENT '状态：0-正常,1-禁用',
   NAME                 VARCHAR(255) NOT NULL COMMENT '险种名称',
   COVERAGE             DECIMAL(10,2) COMMENT '保额',
   PREMIUM              DECIMAL(10,2) COMMENT '保费',
   DESC_                VARCHAR(4000) COMMENT '备注',
   FILE_DATE            DATETIME NOT NULL COMMENT '创建时间',
   AUTHOR_ID            BIGINT NOT NULL COMMENT '创建人ID',
   MODIFIER_ID          BIGINT COMMENT '最后修改人ID',
   MODIFIED_DATE        DATETIME COMMENT '最后修改时间',
   PRIMARY KEY (ID)
) COMMENT '车保险种';
ALTER TABLE BS_INSURANCE_TYPE ADD CONSTRAINT BSFK_INSURANCETYPE_AUTHOR FOREIGN KEY (AUTHOR_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
ALTER TABLE BS_INSURANCE_TYPE ADD CONSTRAINT BSFK_INSURANCETYPE_MODIFIER FOREIGN KEY (MODIFIER_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
  
      
-- 从交委WebService接口同步的交通违章信息
CREATE TABLE BS_SYNC_JIAOWEI_JTWF (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    HAPPEN_DATE DATETIME NOT NULL COMMENT '违章时间',
    CAR_PLATE_TYPE VARCHAR(100) NOT NULL COMMENT '车牌类型',
    CAR_PLATE_NO VARCHAR(100) NOT NULL COMMENT '车牌号',
    DRIVER_CERT VARCHAR(255) COMMENT '服务资格证',
    DRIVER_NAME VARCHAR(255) COMMENT '当事司机姓名',
    JEOM DECIMAL(10,1) NOT NULL COMMENT '本次扣分',
    COMPANY_NAME VARCHAR(255) COMMENT '单位名称',
    CONTENT VARCHAR(4000) NOT NULL COMMENT '违章内容',
    PRIMARY KEY (ID)
) COMMENT '交委WebService接口的交通违章信息';
ALTER TABLE BS_SYNC_JIAOWEI_JTWF ADD CONSTRAINT BSFK_JIAOWEIJTWF2BASE FOREIGN KEY (ID)
      REFERENCES BC_SYNC_BASE (ID);
ALTER TABLE BS_SYNC_JIAOWEI_JTWF ADD INDEX BSIDX_JIAOWEIJTWF_CERT (DRIVER_CERT);
ALTER TABLE BS_SYNC_JIAOWEI_JTWF ADD INDEX BSIDX_JIAOWEIJTWF_CAR (CAR_PLATE_TYPE,CAR_PLATE_NO);


-- 从交委WebService接口同步的营运违章信息
CREATE TABLE BS_SYNC_JIAOWEI_YYWZ (
    ID			BIGINT NOT NULL AUTO_INCREMENT,
    C_ID		VARCHAR(255) NOT NULL,
    STATUS		VARCHAR(100) COMMENT '状态',
    CERT_KJ		VARCHAR(255) COMMENT '扣件证号',
    OPERATOR		VARCHAR(255) COMMENT '执法人',
    OPERATE_UNIT        VARCHAR(255) COMMENT '执法分队',
    VIDEO_OPERATER      VARCHAR(255) COMMENT '摄录员',
    DRIVER_NAME		VARCHAR(255) COMMENT '当事人',
    IDCARD_TYPE         VARCHAR(255) COMMENT '身份证明类型',
    IDCARD_CODE         VARCHAR(255) COMMENT '身份证明编号',
    CAR_PLATE		VARCHAR(255) COMMENT '违章主体',
    COMPANY		VARCHAR(255) COMMENT '违章企业',
    ADDRESS             VARCHAR(1000)COMMENT '违章地段',
    OWNER               VARCHAR(255) COMMENT '业户名称',
    OWNER_ID            VARCHAR(100) COMMENT '业户ID',
    BS_CERT_NO          VARCHAR(255) COMMENT '经营许可证号',
    CONTENT		VARCHAR(4000) NOT NULL COMMENT '违章内容',
    HAPPEN_DATE         DATETIME NOT NULL COMMENT '违章日期',
    EVIDENCE_UNIT       VARCHAR(255) COMMENT '证物保存单位',
    WZ_TYPE		VARCHAR(255) COMMENT '违章类型',
    BUSLINES		VARCHAR(255) COMMENT '公交线路',
    CARPLATE_COLOR	VARCHAR(100) COMMENT '车牌颜色',
    DRIVER_CERT		VARCHAR(255) COMMENT '资格证号',
    COMMIT_STATUS	VARCHAR(255) COMMENT '提交状态',
    RECEIPT             VARCHAR(255) COMMENT '罚没收据编号',
    NOTICE		VARCHAR(255) COMMENT '放行通知书编号',
    CERT_YY             VARCHAR(255) COMMENT '营运证号',
    SEATING		DECIMAL(10,1) COMMENT '座位数',
    OWE_RECORD          VARCHAR(255) COMMENT '欠笔录',
    OWE_SIGNATURE	VARCHAR(255) COMMENT '欠签名',
    LEAVE_TROOPS	VARCHAR(255) COMMENT '留队部',
    AREA                VARCHAR(255) COMMENT '所属区县',
    CLOSE_DATE          DATETIME COMMENT '结案日期',
    DESC_               VARCHAR(4000) COMMENT '备注',
    CLONE               VARCHAR(4000) COMMENT '是否克隆车',
    SUBJECT             VARCHAR(1000) COMMENT '违章项目',
    DETAIN              VARCHAR(255) COMMENT '扣留物品',
    PULL_UNIT           VARCHAR(255) COMMENT '拖车单位',
    PENALTY             DECIMAL(10,2) COMMENT '罚款',

    PRIMARY KEY (ID)
) COMMENT '交委WebService接口的营运违章信息';
ALTER TABLE BS_SYNC_JIAOWEI_YYWZ ADD CONSTRAINT BSFK_JIAOWEIYYWZBASE FOREIGN KEY (ID)
      REFERENCES BC_SYNC_BASE (ID);
ALTER TABLE BS_SYNC_JIAOWEI_YYWZ ADD INDEX BSIDX_JIAOWEIYYWZ_CERT (DRIVER_CERT);


-- 从交委WebService接口同步的投诉与建议信息
CREATE TABLE BS_SYNC_JIAOWEI_ADVICE (
    ID			BIGINT NOT NULL AUTO_INCREMENT,	
    C_ID		VARCHAR(255) NOT NULL,
    RECEIVE_CODE        VARCHAR(255) COMMENT '电话受理号',
    ADVISOR_NAME        VARCHAR(255) NOT NULL COMMENT '投诉人姓名',
    PATH_FROM           VARCHAR(255) COMMENT '乘车路线(从)',
    PATH_TO             VARCHAR(255) COMMENT '乘车路线(到)',
    RIDING_TIME_START   DATETIME COMMENT '乘车起始时间',
    RIDING_TIME_END     DATETIME COMMENT '乘车结束时间',
    ADVISOR_SEX         VARCHAR(100) COMMENT '投诉人性别',
    ADVISOR_AGE         DECIMAL(3,0) COMMENT '投诉人年龄',
    ADVISOR_PHONE       VARCHAR(255) COMMENT '投诉人电话',
    ADVISOR_CERT        VARCHAR(255) COMMENT '投诉人证件号',
    OLD_UNIT_NAME       VARCHAR(255)  COMMENT '车属单位',
    CAR_PLATE		VARCHAR(255) COMMENT '车牌号码',
    DRIVER_ID		VARCHAR(255) COMMENT '资格证号',
    DRIVER_CHAR         VARCHAR(255) COMMENT '司机特征',
    CONTENT		VARCHAR(4000) NOT NULL COMMENT '投诉内容',
    RECEIVE_DATE        DATETIME COMMENT '受理时间',
    RESULT_             VARCHAR(4000) COMMENT '处理结果',
    ADVICE_TYPE		VARCHAR(255) COMMENT '投诉或建议',
    ADVICE_BS		VARCHAR(255) COMMENT '投诉行业',
    SUBJECT             VARCHAR(255) COMMENT '投诉项目大类',
    SUBJECT2            VARCHAR(255) COMMENT '投诉项目小类',
    MACHINE_PRICE       BIGINT COMMENT '计费器显示价格',
    TICKET              VARCHAR(255) COMMENT '车票号码',
    CHARGE              VARCHAR(255) COMMENT '实际收费',
    DRIVER_SEX          VARCHAR(10) COMMENT '司机性别',
    SUGGEST_BS		VARCHAR(255) COMMENT '建议行业',
    BUSLINES            VARCHAR(255) COMMENT '公交线路或站场',
    BUS_COLOR		VARCHAR(255) COMMENT '颜色',
    REPLY		VARCHAR(255) COMMENT '是否回复',

    PRIMARY KEY (ID)
) COMMENT '交委WebService接口的投诉与建议信息';
ALTER TABLE BS_SYNC_JIAOWEI_ADVICE ADD CONSTRAINT BSFK_JIAOWEIADVICEBASE FOREIGN KEY (ID)
      REFERENCES BC_SYNC_BASE (ID);
ALTER TABLE BS_SYNC_JIAOWEI_ADVICE ADD INDEX BSIDX_JIAOWEIADVICE_CERT (DRIVER_CERT);


-- 从金盾网抓取的交通违法信息
CREATE TABLE BS_SYNC_JINDUN_JTWF (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    CAR_TYPE VARCHAR(10) NOT NULL COMMENT '号牌种类',
    CAR_TYPE_DESC VARCHAR(100) NOT NULL COMMENT '号牌种类的中文描述',
    CAR_PLATE_TYPE VARCHAR(100) NOT NULL COMMENT '车牌类型',
    CAR_PLATE_NO VARCHAR(100) NOT NULL COMMENT '车牌号',
    ENGINE_NO VARCHAR(255) COMMENT '发动机号',
    HAPPEN_DATE DATETIME NOT NULL COMMENT '违法时间',
    ADDRESS VARCHAR(1000) COMMENT '违法地点',
    DRIVER_NAME VARCHAR(255) COMMENT '当事人',
    JEOM DECIMAL(10,1) NOT NULL COMMENT '违法记分数',
    PENALTY DECIMAL(10,1) NOT NULL COMMENT '罚款金额',
    OVERDUE_PAYMENT DECIMAL(10,1) NOT NULL COMMENT '滞纳金',
    DECISION_NO VARCHAR(255) COMMENT '决定书编号',
    DECISION_TYPE VARCHAR(255) COMMENT '决定书类别',
    SOURCE VARCHAR(255) COMMENT '违法来源',
    TRAFFIC VARCHAR(255) COMMENT '交通方式',
    BREAK_TYPE VARCHAR(255) COMMENT '违法行为',
    PRIMARY KEY (ID)
) COMMENT '从金盾网抓取的交通违法信息';
ALTER TABLE BS_SYNC_JINDUN_JTWF ADD CONSTRAINT BSFK_JINDUNJTWF2BASE FOREIGN KEY (ID)
      REFERENCES BC_SYNC_BASE (ID);
ALTER TABLE BS_SYNC_JINDUN_JTWF ADD INDEX BSIDX_JINDUNJTWF_CAR (CAR_PLATE_TYPE,CAR_PLATE_NO);

-- 考勤成员配置
CREATE TABLE BS_MEMBER(
   ID                   BIGINT NOT NULL,
   MEMBER_ID            BIGINT NOT NULL COMMENT '成员ID',
   MEMBER_TYPE          INT(1) NOT NULL COMMENT '成员类型：10-司机',
   MEMBER_NAME          VARCHAR(255) NOT NULL COMMENT '成员名称',
   AUTH_TYPE            INT(1) NOT NULL COMMENT '验证方式:1-刷卡,2-指纹',
   CODE                 VARCHAR(5) NOT NULL COMMENT '考勤者工号',
   CARD_ID              VARCHAR(20) COMMENT '考勤者卡号',
   DESC_                VARCHAR(4000) COMMENT '补充说明',
   FILE_DATE            DATETIME NOT NULL COMMENT '创建时间',
   AUTHOR_ID            BIGINT NOT NULL COMMENT '创建人ID',
   MODIFIER_ID          BIGINT COMMENT '最后修改人ID',
   MODIFIED_DATE        DATETIME COMMENT '最后修改时间',
   PRIMARY KEY (ID)
) COMMENT '考勤成员配置';
ALTER TABLE BS_MEMBER ADD CONSTRAINT BCFK_MEMBER_AUTHOR FOREIGN KEY (AUTHOR_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
ALTER TABLE BS_MEMBER ADD CONSTRAINT BCFK_MEMBER_MODIFIER FOREIGN KEY (MODIFIER_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
ALTER TABLE BS_MEMBER ADD UNIQUE INDEX BSUK_MEMBER_CODE (CODE);
ALTER TABLE BS_MEMBER ADD UNIQUE INDEX BSUK_MEMBER_MEMBER (MEMBER_TYPE,MEMBER_ID);
ALTER TABLE BS_MEMBER ADD INDEX BSIDX_MEMBER_CARD (CARD_ID);

-- 考勤安排
CREATE TABLE BS_ARRANGE(
   ID                   BIGINT NOT NULL,
   UID_                 VARCHAR(36) NOT NULL,
   TYPE_                INT(1) NOT NULL COMMENT '类型：0-司机安全学习,1-车辆回场检,2-会议安排',
   STATUS_              INT(1) NOT NULL COMMENT '状态：0-正常,1-锁定',
   UNIT_ID              BIGINT NOT NULL COMMENT '所属单位ID',
   YEAR                 NUMERIC(4,0) NOT NULL COMMENT '所属年份',
   MONTH                NUMERIC(2,0) NOT NULL COMMENT '所属月份',
   START_DATE           DATETIME NOT NULL COMMENT '开始时间',
   END_DATE             DATETIME NOT NULL COMMENT '结束时间',
   SUBJECT              VARCHAR(255) NOT NULL COMMENT '标题',
   DESC_                VARCHAR(255) COMMENT '备注',
   FILE_DATE            DATETIME NOT NULL COMMENT '创建时间',
   AUTHOR_ID            BIGINT NOT NULL COMMENT '创建人ID',
   MODIFIER_ID          BIGINT COMMENT '最后修改人ID',
   MODIFIED_DATE        DATETIME COMMENT '最后修改时间',
   PRIMARY KEY (ID)
) COMMENT '考勤安排';
ALTER TABLE BS_ARRANGE ADD CONSTRAINT BCFK_ARRANGE_AUTHOR FOREIGN KEY (AUTHOR_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
ALTER TABLE BS_ARRANGE ADD CONSTRAINT BCFK_ARRANGE_MODIFIER FOREIGN KEY (MODIFIER_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
ALTER TABLE BS_ARRANGE ADD INDEX BSIDX_UNIT_STATUS (UNIT_ID,STATUS_);

-- 安排的成员
CREATE TABLE BS_ARRANGE_MEMBER(
   ID                   BIGINT NOT NULL,
   PID                  BIGINT NOT NULL COMMENT '所属安排ID',
   STATUS_              INT(1) NOT NULL COMMENT '状态：0-未签到,1-已签到',
   MEMBER_ID            BIGINT NOT NULL COMMENT '成员ID',
   MEMBER_TYPE          INT(1) NOT NULL COMMENT '成员类型：10-司机,11-车辆',
   MEMBER_NAME          VARCHAR(255) NOT NULL COMMENT '成员名称',
   SIGN_TYPE            VARCHAR(255) NOT NULL COMMENT '签到方式描述：多中签到类型间用逗号连接,如刷卡+补录',
   SIGN_DATE            VARCHAR(255) NOT NULL COMMENT '签到时间描述:多次签到时间用逗号连接,如2011-01-01,2011-01-10',
   SIGN_COUNT           INT(2) NOT NULL COMMENT '签到次数',
   DESC_                VARCHAR(4000) COMMENT '补充说明',
   FILE_DATE            DATETIME NOT NULL COMMENT '创建时间',
   AUTHOR_ID            BIGINT NOT NULL COMMENT '创建人ID',
   MODIFIER_ID          BIGINT COMMENT '最后修改人ID',
   MODIFIED_DATE        DATETIME COMMENT '最后修改时间',
   PRIMARY KEY (ID)
) COMMENT '安排的成员';
ALTER TABLE BS_ARRANGE_MEMBER ADD CONSTRAINT BCFK_AMEMBER_AUTHOR FOREIGN KEY (AUTHOR_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
ALTER TABLE BS_ARRANGE_MEMBER ADD CONSTRAINT BCFK_AMEMBER_MODIFIER FOREIGN KEY (MODIFIER_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
ALTER TABLE BS_ARRANGE_MEMBER ADD CONSTRAINT BCFK_AMEMBER_ARRANGE FOREIGN KEY (PID)
      REFERENCES BS_ARRANGE (ID);
ALTER TABLE BS_ARRANGE_MEMBER ADD INDEX BSUK_AMEMBER_MEMBER (MEMBER_ID);
ALTER TABLE BS_ARRANGE_MEMBER ADD INDEX BSIDX_AMEMBER_COUNT (SIGN_COUNT);

-- 成员的签到记录
CREATE TABLE BS_SIGN_RECORD(
   ID                   BIGINT NOT NULL,
   PID                  BIGINT COMMENT '隶属ID',
   DATA_TYPE            INT(1) NOT NULL COMMENT '数据分类：0-安全学习,1-回场检,2-会议签到',
   SIGN_TYPE            INT(1) NOT NULL COMMENT '签到方式：0-手工补录,1-刷卡,2-指纹',
   SIGN_DATE            DATETIME NOT NULL COMMENT '签到时间',
   CODE                 VARCHAR(10) NOT NULL COMMENT '工号',
   CARD_ID              VARCHAR(20) COMMENT '卡号',
   NAME                 VARCHAR(255) COMMENT '姓名',
   PATCH_NO             VARCHAR(32) NOT NULL COMMENT '批号',
   AUTHOR_ID            BIGINT NOT NULL COMMENT '创建人',
   FILE_DATE            DATETIME NOT NULL COMMENT '创建时间',
   PRIMARY KEY (ID)
) COMMENT '成员的签到记录';
ALTER TABLE BS_SIGN_RECORD ADD CONSTRAINT BCFK_RECORD_AUTHOR FOREIGN KEY (AUTHOR_ID)
      REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID);
ALTER TABLE BS_SIGN_RECORD ADD CONSTRAINT BCFK_RECORD_MEMBER FOREIGN KEY (PID)
      REFERENCES BS_ARRANGE_MEMBER (ID);
ALTER TABLE BS_SIGN_RECORD ADD INDEX BSIDX_RECORD_CODE (CODE);
ALTER TABLE BS_SIGN_RECORD ADD INDEX BSIDX_RECORD_CARD (CARD_ID);

-- 安全学习司机
CREATE TABLE BS_ARRANGE_DRIVER(
   ID                   BIGINT NOT NULL,
   UNIT_ID              BIGINT NOT NULL COMMENT '单位ID',
   UNIT_NAME            VARCHAR(255) NOT NULL COMMENT '单位名称',
   MOTORCADE_ID         BIGINT NOT NULL COMMENT '车队ID',
   MOTORCADE_NAME       VARCHAR(255) NOT NULL COMMENT '车队名称',
   CAR_ID               BIGINT NOT NULL COMMENT '车辆ID',
   CAR_PLATE_TYPE       VARCHAR(10) NOT NULL COMMENT '车牌类型：如粤A',
   CAR_PLATE_NO       	VARCHAR(10) NOT NULL COMMENT '车牌号码：如368P1',
   CARD_NO              VARCHAR(255) COMMENT '服务资格证号',
   PRIMARY KEY (ID)
) COMMENT '安全学习司机';
ALTER TABLE BS_ARRANGE_DRIVER ADD CONSTRAINT BSFK_ADRIVER_AMEMBER FOREIGN KEY (ID)
      REFERENCES BS_ARRANGE_MEMBER (ID);
ALTER TABLE BS_ARRANGE_DRIVER ADD CONSTRAINT BSFK_ADRIVER_UNIT FOREIGN KEY (UNIT_ID)
      REFERENCES BC_IDENTITY_ACTOR (ID);
ALTER TABLE BS_ARRANGE_DRIVER ADD CONSTRAINT BSFK_ADRIVER_MOTORCADE FOREIGN KEY (MOTORCADE_ID)
      REFERENCES BS_MOTORCADE (ID);
ALTER TABLE BS_ARRANGE_DRIVER ADD CONSTRAINT BSFK_ADRIVER_CAR FOREIGN KEY (CAR_ID)
      REFERENCES BS_CAR (ID);
ALTER TABLE BS_ARRANGE_DRIVER ADD INDEX BSIDX_ADRIVER_UNITM (UNIT_ID,MOTORCADE_ID);
ALTER TABLE BS_ARRANGE_DRIVER ADD INDEX BSIDX_ADRIVER_CARPLATE (CAR_PLATE_TYPE,CAR_PLATE_NO);
ALTER TABLE BS_ARRANGE_DRIVER ADD INDEX BSIDX_ADRIVER_CARDNO (CARD_NO);

-- 回场检车辆
CREATE TABLE BS_ARRANGE_CAR(
   ID                   BIGINT NOT NULL,
   UNIT_ID              BIGINT NOT NULL COMMENT '单位ID',
   UNIT_NAME            VARCHAR(255) NOT NULL COMMENT '单位名称',
   MOTORCADE_ID         BIGINT NOT NULL COMMENT '车队ID',
   MOTORCADE_NAME       VARCHAR(255) NOT NULL COMMENT '车队名称',
   CAR_PLATE_TYPE       VARCHAR(10) NOT NULL COMMENT '车牌类型：如粤A',
   CAR_PLATE_NO       	VARCHAR(10) NOT NULL COMMENT '车牌号码：如368P1',
   PRIMARY KEY (ID)
) COMMENT '回场检车辆';
ALTER TABLE BS_ARRANGE_CAR ADD CONSTRAINT BSFK_ACAR_AMEMBER FOREIGN KEY (ID)
      REFERENCES BS_ARRANGE_MEMBER (ID);
ALTER TABLE BS_ARRANGE_CAR ADD CONSTRAINT BSFK_ACAR_UNIT FOREIGN KEY (UNIT_ID)
      REFERENCES BC_IDENTITY_ACTOR (ID);
ALTER TABLE BS_ARRANGE_CAR ADD CONSTRAINT BSFK_ACAR_MOTORCADE FOREIGN KEY (MOTORCADE_ID)
      REFERENCES BS_MOTORCADE (ID);
ALTER TABLE BS_ARRANGE_CAR ADD INDEX BSIDX_ACAR_CARPLATE (CAR_PLATE_TYPE,CAR_PLATE_NO);
